bool __thiscall cocos2d::Layer::init(Layer *this);
void __thiscall cocos2d::Layer::getDescription(Layer *this);
void __thiscall cocos2d::Layer::setKeypadEnabled(Layer *this,bool param_1);
void __thiscall cocos2d::Layer::onKeyReleased(Layer *this,KeyCode param_1,Event *param_2);
void __thiscall cocos2d::Layer::onKeyPressed(Layer *this,KeyCode param_1,Event *param_2);
void __thiscall cocos2d::Layer::setKeyboardEnabled(Layer *this,bool param_1);
bool __thiscall cocos2d::Layer::isKeyboardEnabled(Layer *this);
void __thiscall cocos2d::Layer::setAccelerometerInterval(Layer *this,double param_1);
void __thiscall cocos2d::Layer::setAccelerometerEnabled(Layer *this,bool param_1);
bool __thiscall cocos2d::Layer::isAccelerometerEnabled(Layer *this);
bool __thiscall cocos2d::Layer::isSwallowsTouches(Layer *this);
void __thiscall cocos2d::Layer::setSwallowsTouches(Layer *this,bool param_1);
DispatchMode __thiscall cocos2d::Layer::getTouchMode(Layer *this);
void __thiscall cocos2d::Layer::setTouchMode(Layer *this,DispatchMode param_1);
void __thiscall cocos2d::Layer::onAcceleration(Layer *this,Acceleration *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchesCancelled(Layer *this,vector<> *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchesEnded(Layer *this,vector<> *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchesMoved(Layer *this,vector<> *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchesBegan(Layer *this,vector<> *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchCancelled(Layer *this,Touch *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchEnded(Layer *this,Touch *param_1,Event *param_2);
void __thiscall cocos2d::Layer::onTouchMoved(Layer *this,Touch *param_1,Event *param_2);
bool __thiscall cocos2d::Layer::onTouchBegan(Layer *this,Touch *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchesCancelled(Layer *this,__Set *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchesEnded(Layer *this,__Set *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchesMoved(Layer *this,__Set *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchesBegan(Layer *this,__Set *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchCancelled(Layer *this,Touch *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchEnded(Layer *this,Touch *param_1,Event *param_2);
void __thiscall cocos2d::Layer::ccTouchMoved(Layer *this,Touch *param_1,Event *param_2);
bool __thiscall cocos2d::Layer::ccTouchBegan(Layer *this,Touch *param_1,Event *param_2);
void __thiscall cocos2d::Layer::keyMenuClicked(Layer *this);
void __thiscall cocos2d::Layer::keyBackClicked(Layer *this);
bool __thiscall cocos2d::Layer::isKeypadEnabled(Layer *this);
void __thiscall cocos2d::Layer::keyReleased(Layer *this,int param_1);
void __thiscall cocos2d::Layer::keyPressed(Layer *this,int param_1);
void __thiscall cocos2d::Layer::registerWithTouchDispatcher(Layer *this);
void __thiscall cocos2d::Layer::didAccelerate(Layer *this,Acceleration *param_1);
