void __thiscall cocos2d::Sprite::setDirtyRecursively(Sprite *this,bool param_1);
void __thiscall cocos2d::Sprite::setReorderChildDirtyRecursively(Sprite *this);
void __thiscall cocos2d::Sprite::updateBlendFunc(Sprite *this);
void __thiscall cocos2d::Sprite::setVertexCoords(Sprite *this,Rect *param_1,V3F_C4B_T2F_Quad *param_2);
void __thiscall cocos2d::Sprite::setTextureCoords(Sprite *this,Rect *param_1);
void __thiscall cocos2d::Sprite::setTextureCoords(Sprite *this,Rect *param_1,V3F_C4B_T2F_Quad *param_2);
void __thiscall cocos2d::Sprite::updateColor(Sprite *this);
bool __thiscall cocos2d::Sprite::initWithFile(Sprite *this,basic_string<> *param_1);
bool __thiscall cocos2d::Sprite::initWithFile(Sprite *this,basic_string<> *param_1,Rect *param_2);
bool __thiscall cocos2d::Sprite::initWithSpriteFrameName(Sprite *this,basic_string<> *param_1);
bool __thiscall cocos2d::Sprite::initWithSpriteFrame(Sprite *this,SpriteFrame *param_1);
bool __thiscall cocos2d::Sprite::initWithPolygon(Sprite *this,PolygonInfo *param_1);
bool __thiscall cocos2d::Sprite::initWithTexture(Sprite *this,Texture2D *param_1);
bool __thiscall cocos2d::Sprite::initWithTexture(Sprite *this,Texture2D *param_1,Rect *param_2);
bool __thiscall cocos2d::Sprite::initWithTexture(Sprite *this,Texture2D *param_1,Rect *param_2,bool param_3);
bool __thiscall cocos2d::Sprite::init(Sprite *this);
bool __thiscall cocos2d::Sprite::isOpacityModifyRGB(Sprite *this);
void __thiscall cocos2d::Sprite::setOpacityModifyRGB(Sprite *this,bool param_1);
void __thiscall cocos2d::Sprite::draw(Sprite *this,Renderer *param_1,Mat4 *param_2,uint param_3);
void __thiscall cocos2d::Sprite::setVisible(Sprite *this,bool param_1);
void __thiscall cocos2d::Sprite::setIgnoreAnchorPointForPosition(Sprite *this,bool param_1);
void __thiscall cocos2d::Sprite::setContentSize(Sprite *this,Size *param_1);
void __thiscall cocos2d::Sprite::setAnchorPoint(Sprite *this,Vec2 *param_1);
void __thiscall cocos2d::Sprite::setPositionZ(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::sortAllChildren(Sprite *this);
void __thiscall cocos2d::Sprite::addChild(Sprite *this,Node *param_1,int param_2,int param_3);
void __thiscall cocos2d::Sprite::addChild(Sprite *this,Node *param_1,int param_2,basic_string<> *param_3);
void __thiscall cocos2d::Sprite::reorderChild(Sprite *this,Node *param_1,int param_2);
void __thiscall cocos2d::Sprite::removeAllChildrenWithCleanup(Sprite *this,bool param_1);
void __thiscall cocos2d::Sprite::removeChild(Sprite *this,Node *param_1,bool param_2);
void __thiscall cocos2d::Sprite::setSkewY(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setSkewX(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setRotationSkewY(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setRotationSkewX(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setRotation(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setPosition(Sprite *this,Vec2 *param_1);
void __thiscall cocos2d::Sprite::setPosition(Sprite *this,float param_1,float param_2);
void __thiscall cocos2d::Sprite::setScale(Sprite *this,float param_1,float param_2);
void __thiscall cocos2d::Sprite::setScale(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setScaleY(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::setScaleX(Sprite *this,float param_1);
void __thiscall cocos2d::Sprite::getDescription(Sprite *this);
void __thiscall cocos2d::Sprite::setDisplayFrameWithAnimationName(Sprite *this,basic_string<> *param_1,long param_2);
SpriteFrame * __thiscall cocos2d::Sprite::getSpriteFrame(Sprite *this);
bool __thiscall cocos2d::Sprite::isFrameDisplayed(Sprite *this,SpriteFrame *param_1);
void __thiscall cocos2d::Sprite::setSpriteFrame(Sprite *this,basic_string<> *param_1);
void __thiscall cocos2d::Sprite::setSpriteFrame(Sprite *this,SpriteFrame *param_1);
void __thiscall cocos2d::Sprite::getCenterRect(Sprite *this);
void __thiscall cocos2d::Sprite::setCenterRect(Sprite *this,Rect *param_1);
void __thiscall cocos2d::Sprite::getCenterRectNormalized(Sprite *this);
void __thiscall cocos2d::Sprite::setCenterRectNormalized(Sprite *this,Rect *param_1);
void __thiscall cocos2d::Sprite::setVertexRect(Sprite *this,Rect *param_1);
void __thiscall cocos2d::Sprite::setTextureRect(Sprite *this,Rect *param_1);
void __thiscall cocos2d::Sprite::setTextureRect(Sprite *this,Rect *param_1,bool param_2,Size *param_3);
Texture2D * __thiscall cocos2d::Sprite::getTexture(Sprite *this);
void __thiscall cocos2d::Sprite::setTexture(Sprite *this,basic_string<> *param_1);
void __thiscall cocos2d::Sprite::setTexture(Sprite *this,Texture2D *param_1);
void __thiscall cocos2d::Sprite::setBatchNode(Sprite *this,SpriteBatchNode *param_1);
SpriteBatchNode * __thiscall cocos2d::Sprite::getBatchNode(Sprite *this);
void __thiscall cocos2d::Sprite::updateTransform(Sprite *this);
BlendFunc * __thiscall cocos2d::Sprite::getBlendFunc(Sprite *this);
void __thiscall cocos2d::Sprite::setBlendFunc(Sprite *this,BlendFunc *param_1);
void __thiscall cocos2d::Sprite::setDirty(Sprite *this,bool param_1);
bool __thiscall cocos2d::Sprite::isDirty(Sprite *this);
SpriteFrame * __thiscall cocos2d::Sprite::displayFrame(Sprite *this);
SpriteFrame * __thiscall cocos2d::Sprite::getDisplayFrame(Sprite *this);
void __thiscall cocos2d::Sprite::setDisplayFrame(Sprite *this,SpriteFrame *param_1);
