bool __cdecl DataLoader::loadNewsArticle(undefined4 *param_1);
bool __cdecl DataLoader::loadInfoArticle(void *param_1);
void __cdecl DataLoader::loadChatter(void *param_1);
void __cdecl DataLoader::loadAllChatter(void);
void __cdecl DataLoader::createSector(void);
void __cdecl DataLoader::createGameState(void);
void __cdecl DataLoader::createJunkSpawn(void);
void __cdecl DataLoader::createPlanet(void);
void __cdecl DataLoader::createTextMarker(void);
void __cdecl DataLoader::createNebula(void);
void __cdecl DataLoader::createAsteroidField(void);
void __cdecl DataLoader::createMoon(void);
void __cdecl DataLoader::createPassengerQuirk(void);
void __cdecl DataLoader::createPassenger(void *param_1);
void __cdecl DataLoader::createPassengers(void);
void __cdecl DataLoader::createJunk(void);
void __cdecl DataLoader::createJumpPoint(void);
void __cdecl DataLoader::createSpawnPoint(void);
void __cdecl DataLoader::createZone(void);
void __cdecl DataLoader::createNavpoint(void);
void __cdecl DataLoader::createStar(void);
void __cdecl DataLoader::addBootElement(void *param_1);
void __cdecl DataLoader::addModuleConfiguration(void *param_1);
void __cdecl DataLoader::createModule(void);
void __cdecl DataLoader::createHazard(void);
void __cdecl DataLoader::createGood(void);
void __cdecl DataLoader::createTradeLocation(void);
void __cdecl DataLoader::addDockingElement(void *param_1);
void __cdecl DataLoader::addHullDamageChanceElement(basic_string<> *param_1,int param_2);
void __cdecl DataLoader::addHullStrengthElement(basic_string<> *param_1,int param_2);
void __cdecl DataLoader::createShipClass(void);
void __cdecl DataLoader::addComponentInterfaceSlot(void *param_1);
void __cdecl DataLoader::addComponentInterfaceLine(void *param_1);
void __cdecl DataLoader::createComponentInterface(void);
void __cdecl DataLoader::createComponentClass(void);
void __cdecl DataLoader::addCharacterOverlay(void *param_1);
void __cdecl DataLoader::addCharacterComponent(void *param_1);
void __cdecl DataLoader::addCharacterAddition(void *param_1);
void __cdecl DataLoader::createTrack(void);
void __cdecl DataLoader::createAds(void);
void __cdecl DataLoader::createEmotes(void);
void __cdecl DataLoader::createAnimationFrames(void);
void __cdecl DataLoader::createCharacterClass(void);
void __cdecl DataLoader::createCharacter(void);
void __cdecl DataLoader::createConversation(void);
void __cdecl DataLoader::createConversationElement(void);
void __cdecl DataLoader::createConversationOption(void);
void __cdecl DataLoader::createContract(void);
void __cdecl DataLoader::createWeaponClass(void);
void __cdecl DataLoader::createDepot(void);
void __cdecl DataLoader::createSpaceStation(void);
void __cdecl DataLoader::createJumpgate(void);
void __cdecl DataLoader::configureLocations(LocationManager *param_1);
void __cdecl DataLoader::configureWidgetExistValues(basic_string<> *param_1);
void __cdecl DataLoader::configureTextDataForWidget(void *param_1);
void __cdecl DataLoader::createWidget(void *param_1);
void __cdecl DataLoader::checkAndCreateWidget(void *param_1);
void __cdecl DataLoader::createScreen(void);
void __cdecl DataLoader::createScenario(void);
void __cdecl DataLoader::createNavMarker(void);
void __cdecl DataLoader::addShipDestination(void **param_1);
void __cdecl DataLoader::createShip(void);
void __cdecl DataLoader::createCharacterAnimationSet(void);
void __cdecl DataLoader::createStats(void);
void __cdecl DataLoader::createTimedFlags(void);
void __cdecl DataLoader::createTimedFlag(void);
void __cdecl DataLoader::createEmailFileMetaData(void);
void __cdecl DataLoader::createEmail(void);
void __cdecl DataLoader::createDraftSet(void);
void __cdecl DataLoader::createDraft(void);
void __cdecl DataLoader::createSynthetic(void);
void __cdecl DataLoader::createFaction(void);
void __cdecl DataLoader::createStoryNote(void);
void __cdecl DataLoader::createRoom(void);
void __cdecl DataLoader::createRoomObject(void);
void __cdecl DataLoader::parseGeneric(uchar *param_1);
