typedef struct GameLogic GameLogic, *PGameLogic;


struct GameLogic { // PlaceHolder Structure
};


GameLogic * __thiscall GameLogic::GameLogic(GameLogic *this);
SpaceStation * __thiscall GameLogic::getNearestTowLocation(GameLogic *this);
void __thiscall GameLogic::createWorld(GameLogic *this);
void __thiscall GameLogic::initialiseClient(GameLogic *this,bool param_1);
void __thiscall GameLogic::shutDownCurrentScenario(GameLogic *this);
void __thiscall GameLogic::initialiseScenario(GameLogic *this);
void __thiscall GameLogic::completeMultiplayerScenario(GameLogic *this,int param_1);
void __thiscall GameLogic::completeSingleplayerScenario(GameLogic *this,bool param_1);
void __thiscall GameLogic::runPlayerDockLogic(GameLogic *this);
void __thiscall GameLogic::addSyntheticInstances(GameLogic *this);
void __thiscall GameLogic::resetSyntheticInstances(GameLogic *this);
void __thiscall GameLogic::clearShipsInScenario(GameLogic *this,bool param_1);
void __thiscall GameLogic::removeNonPlayedShips(GameLogic *this);
void __thiscall GameLogic::resetShipsInScenario(GameLogic *this,bool param_1);
void __thiscall GameLogic::recheckStoryShips(GameLogic *this);
void __thiscall GameLogic::spawnShip(GameLogic *this,ShipInstance *param_1);
float __thiscall GameLogic::getOrbitChangeTime(GameLogic *this,OrbitState param_1,Ship *param_2);
bool __thiscall GameLogic::runShipLogic(GameLogic *this,Ship *param_1,float param_2,bool param_3);
bool __thiscall GameLogic::safeForTimeCompression(GameLogic *this,basic_string<> *param_1);
void __thiscall GameLogic::runStateCheckLogic(GameLogic *this);
void __thiscall GameLogic::runTimeLogic(GameLogic *this,float param_1);
void __thiscall GameLogic::runServerLogic(GameLogic *this,float param_1);
void __thiscall GameLogic::runClientLogic(GameLogic *this,float param_1);
void __thiscall GameLogic::dropDebrisFromShip(GameLogic *this,Ship *param_1);
void __thiscall GameLogic::removeShipOnSettingFlag(undefined4 param_1,char *param_2);
void __thiscall GameLogic::entirelyRemoveShip(GameLogic *this,Ship *param_1,bool param_2);
int __thiscall GameLogic::convertedTimeInHours(GameLogic *this);
void __thiscall GameLogic::setHazardState(undefined4 param_1_00,int param_1);
int __thiscall GameLogic::calculateJumpDestination(GameLogic *this,int param_1,int param_2);
SpaceStation * __thiscall GameLogic::generateSpaceStation(undefined4 param_1,basic_string<> *param_2);
Ship * __thiscall GameLogic::generateShip(undefined4 param_1,undefined4 param_2,int param_3,void *param_4);
void __thiscall GameLogic::switchPlayerShipTo(GameLogic *this,Ship *param_1);
ModuleType __thiscall GameLogic::getModuleTypeForIdentifier(undefined4 param_1,void *param_2);
void __thiscall GameLogic::addComponentFilter(GameLogic *this,int param_1,ComponentCategory param_2);
void __thiscall GameLogic::addComponentFilterData(GameLogic *this,int param_1,basic_string<> *param_3);
void __thiscall GameLogic::removeSyntheticObject(GameLogic *this,SyntheticObject *param_1);
void __thiscall GameLogic::removeSensorDataFor(GameLogic *this,Ship *param_1);
void __thiscall GameLogic::addCountermeasure(GameLogic *this,int param_1,float param_3,float param_4,undefined4 param_5,undefined4 param_6,basic_string<> *param_7);
CounterMeasure * __thiscall GameLogic::getClosestCounterMeasureTo(undefined4 param_1_00,CounterMeasure *param_1,undefined4 param_3,undefined4 param_4,char *param_5);
void __thiscall GameLogic::addExplosionSensorData(undefined4 param_1_00,undefined4 param_1,float param_3,float param_4);
void __thiscall GameLogic::explosion(undefined4 param_1_00,int param_1,int param_2,int param_4,undefined4 param_5,float param_6,float param_7);
void __thiscall GameLogic::clearPlayerBounties(GameLogic *this);
void __thiscall GameLogic::clearPlayerContracts(GameLogic *this);
bool __thiscall GameLogic::playerHasContract(GameLogic *this);
int __thiscall GameLogic::contractAmountLeftToDeliver(undefined4 param_1,char *param_2);
bool __thiscall GameLogic::hasPassenger(GameLogic *this);
int __thiscall GameLogic::getDeliveringGoodValueInPlayerContracts(undefined4 param_1,char *param_2);
int __thiscall GameLogic::getPurchaseGoodValueInPlayerContracts(undefined4 param_1,char *param_2);
void __thiscall GameLogic::trackGoodsBought(undefined4 param_1,int param_2,char *param_3);
void __thiscall GameLogic::checkContracts(GameLogic *this);
bool __thiscall GameLogic::playerHostilePiratesInSector(GameLogic *this,int param_1);
bool __thiscall GameLogic::zoneActive(GameLogic *this,Zone *param_1);
void __thiscall GameLogic::writeObituary(GameLogic *this);
void __thiscall GameLogic::skipIntroSequence(GameLogic *this);
void __thiscall GameLogic::setTimeCompressionText(undefined4 param_1,basic_string<> *param_2);
void __thiscall GameLogic::setCombatDifficulty(GameLogic *this,int param_1);
void __thiscall GameLogic::setEconomyDifficulty(GameLogic *this,int param_1);
void __thiscall GameLogic::setStartBonus(GameLogic *this,int param_1);
void __thiscall GameLogic::setStartLocation(GameLogic *this,int param_1);
void __thiscall GameLogic::reportSmuggler(GameLogic *this);
void __thiscall GameLogic::reportPirate(undefined4 param_1,void *param_2);
void __thiscall GameLogic::reportPirate(GameLogic *this,int param_1);
void __thiscall GameLogic::getCurrentLocalServers(GameLogic *this);
void __thiscall GameLogic::setLocalServer(GameLogic *this,char *param_2);
void __thiscall GameLogic::getCurrentPlayersAndShips(GameLogic *this);
bool __thiscall GameLogic::canTakeShip(GameLogic *this);
