_Func_class<> * __cdecl ShipTextData::getTextDataFunction(ShipTextDataType param_1);
Ship * __cdecl ShipTextData::getCopyrightText(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getVersionNotes(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::returnNoString(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getShipName(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getOwnshipCorpLogo(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getDesiredOrbit(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getOrbit(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngComponentFilename(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngAddonFilename(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngComponentData(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngAddonData(Ship *param_1,int param_2);
void __cdecl ShipTextData::getComponentInfo(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngModuleName(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getJmpDestination(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getJmpSolState(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getJmpSpinState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getHullCondition(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngComponentRepair(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngModuleRepair(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngModuleStats(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngModuleData(Ship *param_1,int param_2);
void __cdecl ShipTextData::getEngineeringSummary(Ship *param_1,int param_2);
void __cdecl ShipTextData::getStealthRating(Ship *param_1,int param_2);
void __cdecl ShipTextData::getTubeSummary(Ship *param_1,int param_2);
void __cdecl ShipTextData::getTubeAdvancedSummary(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getSSName(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSSDockingBayString(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSSDockingPermit(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSSRegistration(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSSChangeDetails(Ship *param_1,int param_2);
void __cdecl ShipTextData::getDockingProcessString(Ship *param_1,int param_2);
void __cdecl ShipTextData::getUndockingProcessString(Ship *param_1,int param_2);
void __cdecl ShipTextData::getJumpgateState(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getRTCommsScreen(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getPrivateCommsScreen(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSpaceReadings(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSensorWaveformSummary(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSensorFilterState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getCMState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getCommsSyncData(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCommsSyncState(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCommsDamageState(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCommsModel(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCommsEmailState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getMooringState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getMooredObjectState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getMooredCargoState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getShipCargoState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getShipCargoDetails(Ship *param_1,int param_2);
void __cdecl ShipTextData::getDepotState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getCassandraDetails(Ship *param_1,int param_2);
void __cdecl ShipTextData::getRemoraDockDetails(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getInfopediaArticleDetails(Ship *param_1,int param_2);
void __cdecl ShipTextData::getCassandraDockingBay(Ship *param_1,int param_2);
void __cdecl ShipTextData::getMooredCargoDetails(Ship *param_1,int param_2);
void __cdecl ShipTextData::getPDSState(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSensorSummary(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSensorAdditional(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTabletSummary(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTabletTranslate(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTabletNotes(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getOmegaTabletHeader(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCargoViewText(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getEmailStateText(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getPlayerNote(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMusicPlayer(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getOmegaTabletScreen(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getOmegaTabletFooter(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getShopStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTradeStrBottom(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTradeStrTop(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTradeStrFull(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getTradeCommodityIcon(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCompanyStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getLoanStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getContractStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getBountyStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getPassengerInfo(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMechanicStatusStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMechanicPodStatusStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMechanicModuleStatusStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMechanicHullSectionStatusStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMechanicArmamentStatusStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getSelectedPodIcon(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getShipSelectedText(Ship *param_1,int param_2);
void __cdecl ShipTextData::getWreckStatusText(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getCredits(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getGameOverText(Ship *param_1,int param_2);
void __cdecl ShipTextData::getLogStr(Ship *param_1,int param_2);
void __cdecl ShipTextData::getSelectedScenarioStr(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getPowerRoomDetail(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getMultiplayerChat(Ship *param_1,int param_2);
void __cdecl ShipTextData::getWaypointETA(Ship *param_1,int param_2);
void __cdecl ShipTextData::getNavCurrentState(Ship *param_1,int param_2);
Ship * __cdecl ShipTextData::getLocalServerStr(Ship *param_1,int param_2);
void __cdecl ShipTextData::getCurrentServerDetails(Ship *param_1,int param_2);
