typedef struct Ship Ship, *PShip;


struct Ship { // PlaceHolder Class Structure
};


bool __thiscall Ship::isSpaceShip(Ship *this);
bool __thiscall Ship::isSpaceStation(Ship *this);
float __thiscall Ship::getSpeed(Ship *this);
int __thiscall Ship::getNextSensorID(Ship *this);
void __thiscall Ship::shipDocking(Ship *this,Ship *param_1);
bool __thiscall Ship::isJumpGate(Ship *this);
Ship * __thiscall Ship::Ship(Ship *this,int param_2,int param_3,basic_string<> *param_4);
void __thiscall Ship::~Ship(Ship *this);
void __thiscall Ship::initialiseBehaviour(Ship *this,CraftPurpose param_1,int param_2,int param_3);
void __thiscall Ship::log(undefined4 param_1,int param_2,char *param_3,...);
void __thiscall Ship::setNoFog(Ship *this);
void __thiscall Ship::setFullFog(Ship *this);
void __thiscall Ship::removeAllFog(Ship *this);
double __thiscall Ship::relativeAngleToLocation(Ship *this,undefined4 param_2,undefined4 param_3);
double __thiscall Ship::relativeAngleToObject(Ship *this,GameObject *param_1);
double __thiscall Ship::trueAngleToPosition(Ship *this,float param_2);
double __thiscall Ship::trueAngleToObject(Ship *this,GameObject *param_1);
SensorData * __thiscall Ship::getMostDangerousSensorObject(Ship *this);
void __thiscall Ship::selectNextValidSensorObject(Ship *this);
void __thiscall Ship::selectPrevValidSensorObject(Ship *this);
void __thiscall Ship::setEmcon(Ship *this,bool param_1);
bool __thiscall Ship::hullDamaged(Ship *this);
bool __thiscall Ship::isDestroyed(Ship *this);
HullDamageState __thiscall Ship::getDamageStateForHullSection(Ship *this,HullLocation param_1);
int __thiscall Ship::getHullDamagePercent(Ship *this);
int __thiscall Ship::getDamageAmountForHullSection(Ship *this,HullLocation param_1);
void __thiscall Ship::setSector(Ship *this,int param_1);
void __thiscall Ship::giveFullPower(Ship *this);
void __thiscall Ship::addModulesWithConfig(Ship *this,void *param_2);
void __thiscall Ship::setDefaultEMCONSettings(Ship *this);
bool __thiscall Ship::reactorOnline(Ship *this);
SensorData * __thiscall Ship::getSensorDataNear(Ship *this);
SensorData * __thiscall Ship::getSensorDataForShipID(Ship *this,int param_1);
SensorData * __thiscall Ship::getSensorDataForSyntheticObjectID(Ship *this,int param_1);
SensorData * __thiscall Ship::getSensorData(Ship *this,int param_1);
bool __thiscall Ship::getLinkedProbeDetectionOf(Ship *this,Ship *param_1);
bool __thiscall Ship::canCurrentlyDetect(Ship *this,Ship *param_1);
void __thiscall Ship::removeSensorDataForSyntheticID(Ship *this,int param_1);
void __thiscall Ship::removeSensorData(Ship *this,SensorData *param_1);
void __thiscall Ship::clearSensorData(Ship *this);
bool __thiscall Ship::alwaysKnown(Ship *this,Ship *param_1);
void __thiscall Ship::runPassiveSensorLogic(Ship *this,float param_1);
float __thiscall Ship::getWaveform(Ship *this,float param_1);
bool __thiscall Ship::isDisabled(Ship *this,bool param_1);
Ship * __thiscall Ship::performSensorScan(Ship *this,float param_1);
bool __thiscall Ship::canUseWeapons(Ship *this);
void __thiscall Ship::removeWeapon(Ship *this,Weapon *param_1);
int __thiscall Ship::maxWeapons(Ship *this);
bool __thiscall Ship::weaponSpunUp(Ship *this);
bool __thiscall Ship::hasWeaponFired(Ship *this,char *param_2);
int __thiscall Ship::addWeapon(Ship *this,WeaponClass *param_1,int param_2);
void __thiscall Ship::fireWeapon(Ship *this,int param_1);
HullLocation __thiscall Ship::getDamageLocationForAngle(Ship *this,DamageAngle param_1);
void __thiscall Ship::destroy(Ship *this);
bool __thiscall Ship::damage(Ship *this,int param_1,float param_2,DamageType param_3,Ship *param_4);
void __thiscall Ship::repairConsoleDamage(Ship *this);
void __thiscall Ship::damageConsole(Ship *this);
ConsoleDamage * __thiscall Ship::getConsoleDamage(Ship *this,char *param_2);
int __thiscall Ship::getValue(Ship *this);
bool __thiscall Ship::hasCargo(Ship *this);
bool __thiscall Ship::hasEmptyPodSlot(Ship *this);
int __thiscall Ship::getNextEmptyCargoPod(Ship *this);
void __thiscall Ship::setDocked(Ship *this,Ship *param_1,bool param_2,bool param_3);
void __thiscall Ship::dockWith(Ship *this,Ship *param_1,bool param_2);
void __thiscall Ship::undock(Ship *this,bool param_1);
void __thiscall Ship::detectsWeaponLaunchFiredAtIt(Ship *this,Ship *param_1);
bool __thiscall Ship::isDocked(Ship *this);
bool __thiscall Ship::isUndocking(Ship *this);
void __thiscall Ship::runDockLogic(Ship *this,float param_1);
void __thiscall Ship::runOrbitLogic(Ship *this,float param_1);
void __thiscall Ship::clearSelectPoints(Ship *this);
void __thiscall Ship::beginJump(Ship *this,undefined4 param_1,undefined4 param_3,undefined4 param_4);
void __thiscall Ship::performSectorChange(Ship *this,int param_1);
void __thiscall Ship::dischargeJumpDrive(Ship *this);
void __thiscall Ship::runJumpLogic(Ship *this,float param_1);
void __thiscall Ship::runLogic(Ship *this,float param_1);
void __thiscall Ship::runSensorLogic(Ship *this,float param_1);
bool __thiscall Ship::canDetectPlayerShip(Ship *this);
void __thiscall Ship::addSensorGhost(Ship *this,int param_1,int param_2,int param_3,float param_4);
void __thiscall Ship::takeHazardDamage(Ship *this);
void __thiscall Ship::runCommsLogic(Ship *this,float param_1);
void __thiscall Ship::runHeatLogic(Ship *this,float param_1);
void __thiscall Ship::runHazardLogic(Ship *this,float param_1);
void __thiscall Ship::resetBurnVector(Ship *this);
void __thiscall Ship::switchTravelState(Ship *this,TravelState param_1);
void __thiscall Ship::runMotionLogic(Ship *this,float param_1);
void __thiscall Ship::performAllStopLogic(Ship *this,float param_1);
void __thiscall Ship::setMotionAngle(Ship *this,float param_1);
float __thiscall Ship::getMotionAngle(Ship *this);
void __thiscall Ship::cancelAutopilot(Ship *this);
float __thiscall Ship::distanceToDecelerateFromFull(Ship *this);
void __thiscall Ship::rotateTo(Ship *this,float param_1);
void __thiscall Ship::addWaypoint(Ship *this,undefined4 param_2,undefined4 param_3);
void __thiscall Ship::addWaypoint(Ship *this,GameObject *param_1);
void __thiscall Ship::getNextWaypointLocation(Ship *this);
void __thiscall Ship::getFinalWaypointLocation(Ship *this);
GameObject * __thiscall Ship::getFinalWaypointObject(Ship *this);
Waypoint * __thiscall Ship::getFinalWaypoint(Ship *this);
void __thiscall Ship::setWaypointFlags(Ship *this);
void __thiscall Ship::clearWaypointFlags(Ship *this);
void __thiscall Ship::travelTo(Ship *this,NavPoint *param_1);
void __thiscall Ship::cancelTravel(Ship *this);
void __thiscall Ship::mapCourseTo(Ship *this,undefined4 param_2,undefined4 param_3);
void __thiscall Ship::mapCourseTo(Ship *this,NavPoint *param_1);
void __thiscall Ship::mapCourseTo(Ship *this,Ship *param_1);
void __thiscall Ship::executeCourse(Ship *this,int param_1,int param_2);
void __thiscall Ship::pathComplete(Ship *this,PathNode *param_1);
bool __thiscall Ship::isTravellingByAutopilot(Ship *this);
bool __thiscall Ship::isStopping(Ship *this);
void __thiscall Ship::setSpeed(Ship *this,float param_1);
void __thiscall Ship::accelerate(Ship *this,double param_1);
void __thiscall Ship::allStop(Ship *this);
Conversation * __thiscall Ship::getForcedConversation(Ship *this,bool param_1);
Conversation * __thiscall Ship::getConversation(Ship *this,bool param_1,bool param_2);
void __thiscall Ship::generateSaleDescription(Ship *this,ModuleType param_1,ModuleType param_2);
