typedef struct TradeEngine TradeEngine, *PTradeEngine;


struct TradeEngine { // PlaceHolder Structure
};


void __thiscall TradeEngine::TradeEngine(TradeEngine *this);
TradeLocation * __thiscall TradeEngine::getTradeLocation(TradeEngine *this,char param_2,char *param_3);
void __thiscall TradeEngine::repopulateCurrentContracts(TradeEngine *this);
void __thiscall TradeEngine::getShopHeader(TradeEngine *this,Shop param_1);
void __thiscall TradeEngine::populateCargoItems(TradeEngine *this,vector<> *param_1,bool param_2);
bool __thiscall TradeEngine::checkCargoItems(TradeEngine *this,vector<> *param_1,bool param_2);
void __thiscall TradeEngine::populateCargoComponentItems(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkCargoComponentItems(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateShopItems(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkShopItems(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateWireItems(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkWireItems(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateWireCargoItems(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkWireCargoItems(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateShopComponentItems(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkShopComponentItems(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::clearComponentSelection(TradeEngine *this);
void __thiscall TradeEngine::resetModuleFilter(TradeEngine *this);
void __thiscall TradeEngine::clearModuleSelection(TradeEngine *this);
void __thiscall TradeEngine::resetComponentFilter(TradeEngine *this);
void __thiscall TradeEngine::resetStates(TradeEngine *this);
void __thiscall TradeEngine::regenerateAllShipsForSale(TradeEngine *this);
bool __thiscall TradeEngine::currentCommodityPurchaseValid(TradeEngine *this,TextEngine *param_1);
bool __thiscall TradeEngine::currentBlackMarketPurchaseValid(TradeEngine *this,TextEngine *param_1);
bool __thiscall TradeEngine::currentComponentPurchaseValid(TradeEngine *this,TextEngine *param_1);
bool __thiscall TradeEngine::currentPurchaseValid(TradeEngine *this,Shop param_1,TextEngine *param_2);
bool __thiscall TradeEngine::currentCommoditySaleValid(TradeEngine *this,TextEngine *param_1);
bool __thiscall TradeEngine::currentBlackMarketSaleValid(TradeEngine *this,TextEngine *param_1);
bool __thiscall TradeEngine::currentSaleValid(TradeEngine *this,Shop param_1,TextEngine *param_2);
int __thiscall TradeEngine::maxCanAffordForCurrentTrade(TradeEngine *this,Shop param_1);
int __thiscall TradeEngine::maxForCurrentTrade(TradeEngine *this,Shop param_1);
void __thiscall TradeEngine::selectRightSide(TradeEngine *this,Shop param_1);
void __thiscall TradeEngine::selectLeftSide(TradeEngine *this,Shop param_1);
int __thiscall TradeEngine::getBestAmountToSellOf(TradeEngine *this,int param_1);
void __thiscall TradeEngine::getCurrentTopStr(TradeEngine *this,Shop param_1);
Shop __thiscall TradeEngine::getCurrentIcon(TradeEngine *this,Shop param_1);
void __thiscall TradeEngine::performCommodityTrade(TradeEngine *this,TextEngine *param_1);
void __thiscall TradeEngine::performBlackMarketTrade(TradeEngine *this,TextEngine *param_1);
void __thiscall TradeEngine::performComponentTrade(TradeEngine *this,TextEngine *param_1);
void __thiscall TradeEngine::performTrade(TradeEngine *this,Shop param_1,TextEngine *param_2);
int __thiscall TradeEngine::getMaxLoanSize(TradeEngine *this);
void __thiscall TradeEngine::populateCommerceMenu(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateCompanies(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::getCompanyStr(TradeEngine *this);
bool __thiscall TradeEngine::performPurchaseLicense(TradeEngine *this);
bool __thiscall TradeEngine::canPurchaseLicense(TradeEngine *this);
void __thiscall TradeEngine::populateContracts(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::canTakeCurrentContract(TradeEngine *this);
void __thiscall TradeEngine::getContractStr(TradeEngine *this);
bool __thiscall TradeEngine::canDeliverContract(TradeEngine *this);
bool __thiscall TradeEngine::deliverContract(TradeEngine *this);
bool __thiscall TradeEngine::canTakeContract(TradeEngine *this);
bool __thiscall TradeEngine::takeContract(TradeEngine *this);
void __thiscall TradeEngine::populateBanks(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkBanks(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::getLoanStr(TradeEngine *this);
bool __thiscall TradeEngine::currentLoanValid(TradeEngine *this);
bool __thiscall TradeEngine::currentRepaymentValid(TradeEngine *this);
void __thiscall TradeEngine::takeLoan(TradeEngine *this);
void __thiscall TradeEngine::repayLoan(TradeEngine *this);
bool __thiscall TradeEngine::mechanicCanUpgradePod(TradeEngine *this,int param_1);
bool __thiscall TradeEngine::mechanicCanBuyModule(TradeEngine *this);
void __thiscall TradeEngine::getMechanicStatus(TradeEngine *this);
void __thiscall TradeEngine::getPodStatus(TradeEngine *this);
void __thiscall TradeEngine::getModuleStatus(TradeEngine *this);
void __thiscall TradeEngine::getHullSectionStatus(TradeEngine *this);
bool __thiscall TradeEngine::canBuyArmament(TradeEngine *this,Ship *param_1,int param_2);
bool __thiscall TradeEngine::canSellArmament(TradeEngine *this,Ship *param_1,int param_2);
bool __thiscall TradeEngine::performSellArmament(TradeEngine *this);
void __thiscall TradeEngine::getArmamentStatus(TradeEngine *this);
bool __thiscall TradeEngine::performRepair(TradeEngine *this);
bool __thiscall TradeEngine::performSellPod(TradeEngine *this);
bool __thiscall TradeEngine::performModuleTransaction(TradeEngine *this);
bool __thiscall TradeEngine::performUpgradePod(TradeEngine *this,int param_1);
void __thiscall TradeEngine::populateMechanicMenu(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateMechanicHullParts(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkMechanicHullParts(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateMechanicPods(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkMechanicPods(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateMechanicModules(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkMechanicModules(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateMechanicArmaments(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::populateShips(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::getShipSelectedText(TradeEngine *this);
bool __thiscall TradeEngine::shipCanBuy(TradeEngine *this);
void __thiscall TradeEngine::performBuyShip(TradeEngine *this);
void __thiscall TradeEngine::populatePassengers(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkPassengers(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::getPassengerInfo(TradeEngine *this);
void __thiscall TradeEngine::getCargoViewText(TradeEngine *this);
void __thiscall TradeEngine::populateBountyItems(TradeEngine *this,vector<> *param_1);
bool __thiscall TradeEngine::checkBountyItems(TradeEngine *this,vector<> *param_1);
void __thiscall TradeEngine::getBountyStr(TradeEngine *this);
bool __thiscall TradeEngine::performTakeBounty(TradeEngine *this);
