void __cdecl V12::saveStats(_iobuf *param_1);
void __cdecl V12::saveFogOfWarState(_iobuf *param_1);
void __cdecl V12::saveEmails(_iobuf *param_1);
void __cdecl V12::saveFlags(_iobuf *param_1);
void __cdecl V12::saveFactionStates(_iobuf *param_1);
void __cdecl V12::savePlayerContracts(_iobuf *param_1);
void __cdecl V12::loadPlayerContracts(_iobuf *param_1);
void __cdecl V12::writeBounty(_iobuf *param_1,Bounty *param_2);
void __cdecl V12::saveSpaceStationStates(_iobuf *param_1);
void __cdecl V12::loadSpaceStationStates(_iobuf *param_1);
void __cdecl V12::writeTradeItem(_iobuf *param_1,TradeItemInstance *param_2);
void __cdecl V12::writeContract(_iobuf *param_1,Contract *param_2);
void __cdecl V12::writeCargo(_iobuf *param_1,CargoHold *param_2);
CargoHold * __cdecl V12::readCargo(_iobuf *param_1);
void __cdecl V12::saveShip(_iobuf *param_1,Ship *param_2);
Ship * __cdecl V12::loadShip(_iobuf *param_1);
void __cdecl V12::savePassenger(_iobuf *param_1);
void __cdecl V12::writeShipModule(_iobuf *param_1,ShipModule *param_2);
ShipModule * __cdecl V12::readShipModule(_iobuf *param_1);
