void __thiscall RakNet::BitStream::Write<>(BitStream *this,uint24_t *param_1);
bool __thiscall RakNet::BitStream::Read<>(BitStream *this,uint24_t *param_1);
void __thiscall RakNet::BitStream::Write<>(BitStream *this,ushort *param_1);
bool __thiscall RakNet::BitStream::Read<>(BitStream *this,ushort *param_1);
void __thiscall RakNet::BitStream::Write<>(BitStream *this,__uint64 *param_1);
void __thiscall RakNet::BitStream::Write<>(BitStream *this,uint *param_1);
bool __thiscall RakNet::BitStream::Read<>(BitStream *this,__uint64 *param_1);
BitStream * __thiscall RakNet::BitStream::BitStream(BitStream *this);
void __thiscall RakNet::BitStream::~BitStream(BitStream *this);
void __thiscall RakNet::BitStream::Write(BitStream *this,char *param_1,uint param_2);
void __thiscall RakNet::BitStream::Write(BitStream *this,BitStream *param_1,uint param_2);
void __thiscall RakNet::BitStream::WriteAlignedBytes(BitStream *this,uchar *param_1,uint param_2);
void __thiscall RakNet::BitStream::WriteBits(BitStream *this,uchar *param_1,uint param_2,bool param_3);
bool __thiscall RakNet::BitStream::ReadBits(BitStream *this,uchar *param_1,uint param_2,bool param_3);
void __thiscall RakNet::BitStream::AddBitsAndReallocate(BitStream *this,uint param_1);
void __thiscall RakNet::BitStream::WriteAlignedVar16(BitStream *this,char *param_1);
bool __thiscall RakNet::BitStream::ReadAlignedVar16(BitStream *this,char *param_1);
void __thiscall RakNet::BitStream::WriteAlignedVar32(BitStream *this,char *param_1);
bool __thiscall RakNet::BitStream::ReadAlignedVar32(BitStream *this,char *param_1);
