uint __thiscall RakNet::RakPeer::GetMaximumIncomingConnections(RakPeer *this);
bool __thiscall RakNet::RakPeer::IsNetworkSimulatorActive(RakPeer *this);
void __thiscall RakNet::RakPeer::ApplyNetworkSimulator(RakPeer *this,float param_1,ushort param_2,ushort param_3);
Packet * __thiscall RakNet::RakPeer::AllocPacket(RakPeer *this,uint param_1,char *param_2,uint param_3);
Packet * __thiscall RakNet::RakPeer::AllocPacket(RakPeer *this,uint param_1,uchar *param_2,char *param_3,uint param_4);
RakPeer * __thiscall RakNet::RakPeer::RakPeer(RakPeer *this);
void * __thiscall RakNet::RakPeer::`vector_deleting_destructor'(RakPeer *this,uint param_1);
void __thiscall RakNet::RakPeer::~RakPeer(RakPeer *this);
StartupResult __thiscall RakNet::RakPeer::Startup(RakPeer *this,uint param_1,SocketDescriptor *param_2,uint param_3,int param_4);
bool __thiscall RakNet::RakPeer::InitializeSecurity(RakPeer *this,char *param_1,char *param_2,bool param_3);
void __thiscall RakNet::RakPeer::AddToSecurityExceptionList(RakPeer *this,char *param_1);
void __thiscall RakNet::RakPeer::RemoveFromSecurityExceptionList(RakPeer *this,char *param_1);
bool __thiscall RakNet::RakPeer::IsInSecurityExceptionList(RakPeer *this,char *param_1);
void __thiscall RakNet::RakPeer::SetMaximumIncomingConnections(RakPeer *this,ushort param_1);
ushort __thiscall RakNet::RakPeer::NumberOfConnections(RakPeer *this);
void __thiscall RakNet::RakPeer::SetIncomingPassword(RakPeer *this,char *param_1,int param_2);
void __thiscall RakNet::RakPeer::GetIncomingPassword(RakPeer *this,char *param_1,int *param_2);
ConnectionAttemptResult __thiscall RakNet::RakPeer::Connect(RakPeer *this,char *param_1,ushort param_2,char *param_3,int param_4,PublicKey *param_5,uint param_6,uint param_7,uint param_8,uint param_9);
ConnectionAttemptResult __thiscall RakNet::RakPeer::ConnectWithSocket(RakPeer *this,char *param_1,ushort param_2,char *param_3,int param_4,RakNetSocket2 *param_5,PublicKey *param_6,uint param_7,uint param_8,uint param_9);
void __thiscall RakNet::RakPeer::Shutdown(RakPeer *this,uint param_1,uchar param_2,PacketPriority param_3);
bool __thiscall RakNet::RakPeer::IsActive(RakPeer *this);
bool __thiscall RakNet::RakPeer::GetConnectionList(RakPeer *this,SystemAddress *param_1,ushort *param_2);
uint __thiscall RakNet::RakPeer::GetNextSendReceipt(RakPeer *this);
uint __thiscall RakNet::RakPeer::IncrementNextSendReceipt(RakPeer *this);
uint __thiscall RakNet::RakPeer::Send(RakPeer *this,char *param_1,int param_2,PacketPriority param_3,PacketReliability param_4,char param_5,AddressOrGUID param_6,bool param_7,uint param_8);
void __thiscall RakNet::RakPeer::SendLoopback(RakPeer *this,char *param_1,int param_2);
uint __thiscall RakNet::RakPeer::Send(RakPeer *this,BitStream *param_1,PacketPriority param_2,PacketReliability param_3,char param_4,AddressOrGUID param_5,bool param_6,uint param_7);
uint __thiscall RakNet::RakPeer::SendList(RakPeer *this,char **param_1,int *param_2,int param_3,PacketPriority param_4,PacketReliability param_5,char param_6,AddressOrGUID param_7,bool param_8,uint param_9);
Packet * __thiscall RakNet::RakPeer::Receive(RakPeer *this);
void __thiscall RakNet::RakPeer::DeallocatePacket(RakPeer *this,Packet *param_1);
uint __thiscall RakNet::RakPeer::GetMaximumNumberOfPeers(RakPeer *this);
void __thiscall RakNet::RakPeer::CloseConnection(RakPeer *this,AddressOrGUID param_1,bool param_2,uchar param_3,PacketPriority param_4);
void __thiscall RakNet::RakPeer::CancelConnectionAttempt(RakPeer *this,SystemAddress param_1);
ConnectionState __thiscall RakNet::RakPeer::GetConnectionState(RakPeer *this,AddressOrGUID param_1);
int __thiscall RakNet::RakPeer::GetIndexFromSystemAddress(RakPeer *this,SystemAddress param_1);
SystemAddress * __thiscall RakNet::RakPeer::GetSystemAddressFromIndex(RakPeer *this,SystemAddress *__return_storage_ptr__,uint param_1);
RakNetGUID * __thiscall RakNet::RakPeer::GetGUIDFromIndex(RakPeer *this,RakNetGUID *__return_storage_ptr__,uint param_1);
void __thiscall RakNet::RakPeer::GetSystemList(RakPeer *this,List<> *param_1,List<> *param_2);
void __thiscall RakNet::RakPeer::AddToBanList(RakPeer *this,char *param_1,uint param_2);
void __thiscall RakNet::RakPeer::RemoveFromBanList(RakPeer *this,char *param_1);
void __thiscall RakNet::RakPeer::ClearBanList(RakPeer *this);
void __thiscall RakNet::RakPeer::SetLimitIPConnectionFrequency(RakPeer *this,bool param_1);
bool __thiscall RakNet::RakPeer::IsBanned(RakPeer *this,char *param_1);
void __thiscall RakNet::RakPeer::Ping(RakPeer *this,SystemAddress param_1);
bool __thiscall RakNet::RakPeer::Ping(RakPeer *this,char *param_1,ushort param_2,bool param_3,uint param_4);
int __thiscall RakNet::RakPeer::GetAveragePing(RakPeer *this,AddressOrGUID param_1);
int __thiscall RakNet::RakPeer::GetLastPing(RakPeer *this,AddressOrGUID param_1);
int __thiscall RakNet::RakPeer::GetLowestPing(RakPeer *this,AddressOrGUID param_1);
void __thiscall RakNet::RakPeer::SetOccasionalPing(RakPeer *this,bool param_1);
__uint64 __thiscall RakNet::RakPeer::GetClockDifferential(RakPeer *this,AddressOrGUID param_1);
__uint64 __thiscall RakNet::RakPeer::GetClockDifferentialInt(RakPeer *this,RemoteSystemStruct *param_1);
void __thiscall RakNet::RakPeer::SetOfflinePingResponse(RakPeer *this,char *param_1,uint param_2);
void __thiscall RakNet::RakPeer::GetOfflinePingResponse(RakPeer *this,char **param_1,uint *param_2);
SystemAddress * __thiscall RakNet::RakPeer::GetInternalID(RakPeer *this,SystemAddress *__return_storage_ptr__,SystemAddress param_1,int param_2);
void __thiscall RakNet::RakPeer::SetInternalID(RakPeer *this,SystemAddress param_1,int param_2);
SystemAddress * __thiscall RakNet::RakPeer::GetExternalID(RakPeer *this,SystemAddress *__return_storage_ptr__,SystemAddress param_1);
RakNetGUID * __thiscall RakNet::RakPeer::GetMyGUID(RakPeer *this,RakNetGUID *__return_storage_ptr__);
SystemAddress * __thiscall RakNet::RakPeer::GetMyBoundAddress(RakPeer *this,SystemAddress *__return_storage_ptr__,int param_1);
RakNetGUID * __thiscall RakNet::RakPeer::GetGuidFromSystemAddress(RakPeer *this,SystemAddress param_1);
SystemAddress * __thiscall RakNet::RakPeer::GetSystemAddressFromGuid(RakPeer *this,SystemAddress *__return_storage_ptr__,RakNetGUID param_1);
bool __thiscall RakNet::RakPeer::GetClientPublicKeyFromSystemAddress(RakPeer *this,SystemAddress param_1,char *param_2);
void __thiscall RakNet::RakPeer::SetTimeoutTime(RakPeer *this,uint param_1,SystemAddress param_2);
uint __thiscall RakNet::RakPeer::GetTimeoutTime(RakPeer *this,SystemAddress param_1);
int __thiscall RakNet::RakPeer::GetMTUSize(RakPeer *this,SystemAddress param_1);
uint __thiscall RakNet::RakPeer::GetNumberOfAddresses(RakPeer *this);
char * __thiscall RakNet::RakPeer::GetLocalIP(RakPeer *this,uint param_1);
bool __thiscall RakNet::RakPeer::IsLocalIP(RakPeer *this,char *param_1);
void __thiscall RakNet::RakPeer::AllowConnectionResponseIPMigration(RakPeer *this,bool param_1);
bool __thiscall RakNet::RakPeer::AdvertiseSystem(RakPeer *this,char *param_1,ushort param_2,char *param_3,int param_4,uint param_5);
void __thiscall RakNet::RakPeer::SetSplitMessageProgressInterval(RakPeer *this,int param_1);
int __thiscall RakNet::RakPeer::GetSplitMessageProgressInterval(RakPeer *this);
void __thiscall RakNet::RakPeer::SetUnreliableTimeout(RakPeer *this,uint param_1);
void __thiscall RakNet::RakPeer::SendTTL(RakPeer *this,char *param_1,ushort param_2,int param_3,uint param_4);
void __thiscall RakNet::RakPeer::AttachPlugin(RakPeer *this,PluginInterface2 *param_1);
void __thiscall RakNet::RakPeer::DetachPlugin(RakPeer *this,PluginInterface2 *param_1);
void __thiscall RakNet::RakPeer::PushBackPacket(RakPeer *this,Packet *param_1,bool param_2);
void __thiscall RakNet::RakPeer::ChangeSystemAddress(RakPeer *this,RakNetGUID param_1,SystemAddress *param_2);
Packet * __thiscall RakNet::RakPeer::AllocatePacket(RakPeer *this,uint param_1);
RakNetSocket2 * __thiscall RakNet::RakPeer::GetSocket(RakPeer *this,SystemAddress param_1);
void __thiscall RakNet::RakPeer::GetSockets(RakPeer *this,List<> *param_1);
void __thiscall RakNet::RakPeer::ReleaseSockets(RakPeer *this,List<> *param_1);
void __thiscall RakNet::RakPeer::SetPerConnectionOutgoingBandwidthLimit(RakPeer *this,uint param_1);
void __thiscall RakNet::RakPeer::WriteOutOfBandHeader(RakPeer *this,BitStream *param_1);
void __thiscall RakNet::RakPeer::SetUserUpdateThread(RakPeer *this,_func_void_RakPeerInterface_ptr_void_ptr *param_1,void *param_2);
void __thiscall RakNet::RakPeer::SetIncomingDatagramEventHandler(RakPeer *this,_func_bool_RNS2RecvStruct_ptr *param_1);
bool __thiscall RakNet::RakPeer::SendOutOfBand(RakPeer *this,char *param_1,ushort param_2,char *param_3,uint param_4,uint param_5);
RakNetStatistics * __thiscall RakNet::RakPeer::GetStatistics(RakPeer *this,SystemAddress param_1,RakNetStatistics *param_2);
void __thiscall RakNet::RakPeer::GetStatisticsList(RakPeer *this,List<> *param_1,List<> *param_2,List<> *param_3);
bool __thiscall RakNet::RakPeer::GetStatistics(RakPeer *this,uint param_1,RakNetStatistics *param_2);
uint __thiscall RakNet::RakPeer::GetReceiveBufferSize(RakPeer *this);
int __thiscall RakNet::RakPeer::GetIndexFromSystemAddress(RakPeer *this,SystemAddress param_1,bool param_2);
ConnectionAttemptResult __thiscall RakNet::RakPeer::SendConnectionRequest(RakPeer *this,char *param_1,ushort param_2,char *param_3,int param_4,PublicKey *param_5,uint param_6,uint param_7,uint param_8,uint param_9,uint param_10);
ConnectionAttemptResult __thiscall RakNet::RakPeer::SendConnectionRequest(RakPeer *this,char *param_1,ushort param_2,char *param_3,int param_4,PublicKey *param_5,uint param_6,uint param_7,uint param_8,uint param_9,uint param_10,RakNetSocket2 *param_11);
RemoteSystemStruct * __thiscall RakNet::RakPeer::GetRemoteSystem(RakPeer *this,AddressOrGUID param_1,bool param_2,bool param_3);
RemoteSystemStruct * __thiscall RakNet::RakPeer::GetRemoteSystemFromSystemAddress(RakPeer *this,SystemAddress param_1,bool param_2,bool param_3);
RemoteSystemStruct * __thiscall RakNet::RakPeer::GetRemoteSystemFromGUID(RakPeer *this,RakNetGUID param_1,bool param_2);
void __thiscall RakNet::RakPeer::ParseConnectionRequestPacket(RakPeer *this,RemoteSystemStruct *param_1,SystemAddress *param_2,char *param_3,int param_4);
void __thiscall RakNet::RakPeer::OnConnectionRequest(RakPeer *this,RemoteSystemStruct *param_1,__uint64 param_2);
void __thiscall RakNet::RakPeer::NotifyAndFlagForShutdown(RakPeer *this,SystemAddress param_1,bool param_2,uchar param_3,PacketPriority param_4);
RemoteSystemStruct * __thiscall RakNet::RakPeer::AssignSystemAddressToRemoteSystemList(RakPeer *this,SystemAddress param_1,ConnectMode param_2,RakNetSocket2 *param_3,bool *param_4,SystemAddress param_5,int param_6,RakNetGUID param_7,bool param_8);
void __thiscall RakNet::RakPeer::ReferenceRemoteSystem(RakPeer *this,SystemAddress *param_1,uint param_2);
void __thiscall RakNet::RakPeer::DereferenceRemoteSystem(RakPeer *this,SystemAddress *param_1);
uint __thiscall RakNet::RakPeer::GetRemoteSystemIndex(RakPeer *this,SystemAddress *param_1);
bool __thiscall RakNet::RakPeer::IsLoopbackAddress(RakPeer *this,AddressOrGUID *param_1,bool param_2);
bool __thiscall RakNet::RakPeer::AllowIncomingConnections(RakPeer *this);
void __thiscall RakNet::RakPeer::DeallocRNS2RecvStruct(RakPeer *this,RNS2RecvStruct *param_1,char *param_2,uint param_3);
RNS2RecvStruct * __thiscall RakNet::RakPeer::AllocRNS2RecvStruct(RakPeer *this,char *param_1,uint param_2);
void __thiscall RakNet::RakPeer::ClearBufferedPackets(RakPeer *this);
void __thiscall RakNet::RakPeer::PingInternal(RakPeer *this,SystemAddress param_1,bool param_2,PacketReliability param_3);
void __thiscall RakNet::RakPeer::CloseConnectionInternal(RakPeer *this,AddressOrGUID *param_1,bool param_2,bool param_3,uchar param_4,PacketPriority param_5);
void __thiscall RakNet::RakPeer::SendBuffered(RakPeer *this,char *param_1,uint param_2,PacketPriority param_3,PacketReliability param_4,char param_5,AddressOrGUID param_6,bool param_7,ConnectMode param_8,uint param_9);
void __thiscall RakNet::RakPeer::SendBufferedList(RakPeer *this,char **param_1,int *param_2,int param_3,PacketPriority param_4,PacketReliability param_5,char param_6,AddressOrGUID param_7,bool param_8,ConnectMode param_9,uint param_10);
bool __thiscall RakNet::RakPeer::SendImmediate(RakPeer *this,char *param_1,uint param_2,PacketPriority param_3,PacketReliability param_4,char param_5,AddressOrGUID param_6,bool param_7,bool param_8,__uint64 param_9,uint param_10);
void __thiscall RakNet::RakPeer::OnConnectedPong(RakPeer *this,__uint64 param_1,__uint64 param_2,RemoteSystemStruct *param_3);
void __thiscall RakNet::RakPeer::ClearBufferedCommands(RakPeer *this);
void __thiscall RakNet::RakPeer::ClearSocketQueryOutput(RakPeer *this);
void __thiscall RakNet::RakPeer::AddPacketToProducer(RakPeer *this,Packet *param_1);
void __thiscall RakNet::RakPeer::DerefAllSockets(RakPeer *this);
uint __thiscall RakNet::RakPeer::GetRakNetSocketFromUserConnectionSocketIndex(RakPeer *this,uint param_1);
bool __thiscall RakNet::RakPeer::RunUpdateCycle(RakPeer *this,BitStream *param_1);
void __thiscall RakNet::RakPeer::OnRNS2Recv(RakPeer *this,RNS2RecvStruct *param_1);
void __thiscall RakNet::RakPeer::CallPluginCallbacks(RakPeer *this,List<> *param_1,Packet *param_2);
void __thiscall RakNet::RakPeer::FillIPList(RakPeer *this);
RemoteSystemStruct * __thiscall RakNet::RakPeer::RemoteSystemStruct::RemoteSystemStruct(RemoteSystemStruct *this);
void __thiscall RakNet::RakPeer::RemoteSystemStruct::~RemoteSystemStruct(RemoteSystemStruct *this);
void * __thiscall RakNet::RakPeer::`vector_deleting_destructor'`adjustor{4}'(RakPeer *this,uint param_1);
