ReliabilityLayer * __thiscall RakNet::ReliabilityLayer::ReliabilityLayer(ReliabilityLayer *this);
void __thiscall RakNet::ReliabilityLayer::~ReliabilityLayer(ReliabilityLayer *this);
void __thiscall RakNet::ReliabilityLayer::Reset(ReliabilityLayer *this,bool param_1,int param_2,bool param_3);
void __thiscall RakNet::ReliabilityLayer::InitializeVariables(ReliabilityLayer *this);
void __thiscall RakNet::ReliabilityLayer::FreeThreadSafeMemory(ReliabilityLayer *this);
bool __thiscall RakNet::ReliabilityLayer::HandleSocketReceiveFromConnectedPlayer(ReliabilityLayer *this,char *param_1,uint param_2,SystemAddress *param_3,List<> *param_4,int param_5,RakNetSocket2 *param_6,RakNetRandom *param_7,__uint64 param_8,BitStream *param_9);
bool __thiscall RakNet::ReliabilityLayer::Send(ReliabilityLayer *this,char *param_1,uint param_2,PacketPriority param_3,PacketReliability param_4,uchar param_5,bool param_6,int param_7,__uint64 param_8,uint param_9);
void __thiscall RakNet::ReliabilityLayer::Update(ReliabilityLayer *this,RakNetSocket2 *param_1,SystemAddress *param_2,int param_3,__uint64 param_4,uint param_5,List<> *param_6,RakNetRandom *param_7,BitStream *param_8);
uint __thiscall RakNet::ReliabilityLayer::RemovePacketFromResendListAndDeleteOlderReliableSequenced(ReliabilityLayer *this,uint24_t param_1,__uint64 param_2,List<> *param_3,SystemAddress *param_4);
uint __thiscall RakNet::ReliabilityLayer::WriteToBitStreamFromInternalPacket(ReliabilityLayer *this,BitStream *param_1,InternalPacket *param_2,__uint64 param_3);
InternalPacket * __thiscall RakNet::ReliabilityLayer::CreateInternalPacketFromBitStream(ReliabilityLayer *this,BitStream *param_1,__uint64 param_2);
void __thiscall RakNet::ReliabilityLayer::SplitPacket(ReliabilityLayer *this,InternalPacket *param_1);
void __thiscall RakNet::ReliabilityLayer::InsertIntoSplitPacketList(ReliabilityLayer *this,InternalPacket *param_1,__uint64 param_2);
InternalPacket * __thiscall RakNet::ReliabilityLayer::BuildPacketFromSplitPacketList(ReliabilityLayer *this,ushort param_1,__uint64 param_2,RakNetSocket2 *param_3,SystemAddress *param_4,RakNetRandom *param_5,BitStream *param_6);
RakNetStatistics * __thiscall RakNet::ReliabilityLayer::GetStatistics(ReliabilityLayer *this,RakNetStatistics *param_1);
void __thiscall RakNet::ReliabilityLayer::ClearPacketsAndDatagrams(ReliabilityLayer *this);
void __thiscall RakNet::ReliabilityLayer::SendACKs(ReliabilityLayer *this,RakNetSocket2 *param_1,SystemAddress *param_2,__uint64 param_3,RakNetRandom *param_4,BitStream *param_5);
InternalPacket * __thiscall RakNet::ReliabilityLayer::AllocateFromInternalPacketPool(ReliabilityLayer *this);
void __thiscall RakNet::ReliabilityLayer::ReleaseToInternalPacketPool(ReliabilityLayer *this,InternalPacket *param_1);
MessageNumberNode * __thiscall RakNet::ReliabilityLayer::GetMessageNumberNodeByDatagramIndex(ReliabilityLayer *this,uint24_t param_1,__uint64 *param_2);
void __thiscall RakNet::ReliabilityLayer::RemoveFromDatagramHistory(ReliabilityLayer *this,uint24_t param_1);
void __thiscall RakNet::ReliabilityLayer::AllocInternalPacketData(ReliabilityLayer *this,InternalPacket *param_1,InternalPacketRefCountedData **param_2,uchar *param_3,uchar *param_4);
void __thiscall RakNet::ReliabilityLayer::FreeInternalPacketData(ReliabilityLayer *this,InternalPacket *param_1,char *param_2,uint param_3);
__uint64 __thiscall RakNet::ReliabilityLayer::GetNextWeight(ReliabilityLayer *this,int param_1);
