void __thiscall cocos2d::Node::disableCascadeColor(Node *this);
void __thiscall cocos2d::Node::updateCascadeColor(Node *this);
void __thiscall cocos2d::Node::disableCascadeOpacity(Node *this);
void __thiscall cocos2d::Node::updateCascadeOpacity(Node *this);
void __thiscall cocos2d::Node::setCameraMask(Node *this,ushort param_1,bool param_2);
bool __thiscall cocos2d::Node::isOpacityModifyRGB(Node *this);
void __thiscall cocos2d::Node::setOpacityModifyRGB(Node *this,bool param_1);
void __thiscall cocos2d::Node::setCascadeColorEnabled(Node *this,bool param_1);
bool __thiscall cocos2d::Node::isCascadeColorEnabled(Node *this);
void __thiscall cocos2d::Node::updateDisplayedColor(Node *this,Color3B *param_1);
void __thiscall cocos2d::Node::setColor(Node *this,Color3B *param_1);
Color3B * __thiscall cocos2d::Node::getDisplayedColor(Node *this);
Color3B * __thiscall cocos2d::Node::getColor(Node *this);
void __thiscall cocos2d::Node::setCascadeOpacityEnabled(Node *this,bool param_1);
bool __thiscall cocos2d::Node::isCascadeOpacityEnabled(Node *this);
void __thiscall cocos2d::Node::updateDisplayedOpacity(Node *this,uchar param_1);
void __thiscall cocos2d::Node::setOpacity(Node *this,uchar param_1);
uchar __thiscall cocos2d::Node::getDisplayedOpacity(Node *this);
uchar __thiscall cocos2d::Node::getOpacity(Node *this);
void __thiscall cocos2d::Node::removeAllComponents(Node *this);
bool __thiscall cocos2d::Node::removeComponent(Node *this,basic_string<> *param_1);
bool __thiscall cocos2d::Node::removeComponent(Node *this,Component *param_1);
bool __thiscall cocos2d::Node::addComponent(Node *this,Component *param_1);
void __thiscall cocos2d::Node::getWorldToNodeAffineTransform(Node *this);
void __thiscall cocos2d::Node::getWorldToNodeTransform(Node *this);
void __thiscall cocos2d::Node::getNodeToWorldAffineTransform(Node *this);
void __thiscall cocos2d::Node::getNodeToWorldTransform(Node *this);
void __thiscall cocos2d::Node::getParentToNodeAffineTransform(Node *this);
Mat4 * __thiscall cocos2d::Node::getParentToNodeTransform(Node *this);
void __thiscall cocos2d::Node::setNodeToParentTransform(Node *this,Mat4 *param_1);
void __thiscall cocos2d::Node::getNodeToParentAffineTransform(Node *this);
void __thiscall cocos2d::Node::getNodeToParentAffineTransform(Node *this,Node *param_1);
Mat4 * __thiscall cocos2d::Node::getNodeToParentTransform(Node *this);
void __thiscall cocos2d::Node::getNodeToParentTransform(Node *this,Node *param_1);
void __thiscall cocos2d::Node::updateTransform(Node *this);
void __thiscall cocos2d::Node::pause(Node *this);
void __thiscall cocos2d::Node::resume(Node *this);
void __thiscall cocos2d::Node::setScheduler(Node *this,Scheduler *param_1);
Action * __thiscall cocos2d::Node::runAction(Node *this,Action *param_1);
void __thiscall cocos2d::Node::setActionManager(Node *this,ActionManager *param_1);
void __thiscall cocos2d::Node::setEventDispatcher(Node *this,EventDispatcher *param_1);
void __thiscall cocos2d::Node::getBoundingBox(Node *this);
Scene * __thiscall cocos2d::Node::getScene(Node *this);
void __thiscall cocos2d::Node::visit(Node *this,Renderer *param_1,Mat4 *param_2,uint param_3);
void __thiscall cocos2d::Node::visit(Node *this);
void __thiscall cocos2d::Node::draw(Node *this,Renderer *param_1,Mat4 *param_2,uint param_3);
void __thiscall cocos2d::Node::draw(Node *this);
void __thiscall cocos2d::Node::cleanup(Node *this);
void __thiscall cocos2d::Node::onExitTransitionDidStart(Node *this);
void __thiscall cocos2d::Node::onExit(Node *this);
void __thiscall cocos2d::Node::onEnterTransitionDidFinish(Node *this);
void __thiscall cocos2d::Node::onEnter(Node *this);
bool __thiscall cocos2d::Node::isRunning(Node *this);
void __thiscall cocos2d::Node::setGLProgramState(Node *this,GLProgramState *param_1);
void __thiscall cocos2d::Node::setGLProgram(Node *this,GLProgram *param_1);
void __thiscall cocos2d::Node::setUserObject(Node *this,Ref *param_1);
void __thiscall cocos2d::Node::setUserData(Node *this,void *param_1);
void __thiscall cocos2d::Node::setName(Node *this,basic_string<> *param_1);
basic_string<> * __thiscall cocos2d::Node::getName(Node *this);
void __thiscall cocos2d::Node::setTag(Node *this,int param_1);
int __thiscall cocos2d::Node::getTag(Node *this);
void __thiscall cocos2d::Node::sortAllChildren(Node *this);
void __thiscall cocos2d::Node::reorderChild(Node *this,Node *param_1,int param_2);
void __thiscall cocos2d::Node::removeAllChildrenWithCleanup(Node *this,bool param_1);
void __thiscall cocos2d::Node::removeAllChildren(Node *this);
void __thiscall cocos2d::Node::removeChildByName(Node *this,basic_string<> *param_1,bool param_2);
void __thiscall cocos2d::Node::removeChildByTag(Node *this,int param_1,bool param_2);
void __thiscall cocos2d::Node::removeChild(Node *this,Node *param_1,bool param_2);
void __thiscall cocos2d::Node::removeFromParentAndCleanup(Node *this,bool param_1);
void __thiscall cocos2d::Node::removeFromParent(Node *this);
void __thiscall cocos2d::Node::setParent(Node *this,Node *param_1);
long __thiscall cocos2d::Node::getChildrenCount(Node *this);
void __thiscall cocos2d::Node::enumerateChildren(void);
Node * __thiscall cocos2d::Node::getChildByName(Node *this,basic_string<> *param_1);
Node * __thiscall cocos2d::Node::getChildByTag(Node *this,int param_1);
void __thiscall cocos2d::Node::addChild(Node *this,Node *param_1);
void __thiscall cocos2d::Node::addChild(Node *this,Node *param_1,int param_2);
void __thiscall cocos2d::Node::addChild(Node *this,Node *param_1,int param_2,int param_3);
void __thiscall cocos2d::Node::addChild(Node *this,Node *param_1,int param_2,basic_string<> *param_3);
bool __thiscall cocos2d::Node::isIgnoreAnchorPointForPosition(Node *this);
void __thiscall cocos2d::Node::setIgnoreAnchorPointForPosition(Node *this,bool param_1);
float __thiscall cocos2d::Node::getRotationSkewY(Node *this);
void __thiscall cocos2d::Node::setRotationSkewY(Node *this,float param_1);
float __thiscall cocos2d::Node::getRotationSkewX(Node *this);
void __thiscall cocos2d::Node::setRotationSkewX(Node *this,float param_1);
void __thiscall cocos2d::Node::getRotationQuat(Node *this);
void __thiscall cocos2d::Node::setRotationQuat(Node *this,Quaternion *param_1);
void __thiscall cocos2d::Node::getRotation3D(Node *this);
void __thiscall cocos2d::Node::setRotation3D(Node *this,Vec3 *param_1);
float __thiscall cocos2d::Node::getRotation(Node *this);
void __thiscall cocos2d::Node::setRotation(Node *this,float param_1);
bool __thiscall cocos2d::Node::isVisible(Node *this);
void __thiscall cocos2d::Node::setVisible(Node *this,bool param_1);
Size * __thiscall cocos2d::Node::getContentSize(Node *this);
void __thiscall cocos2d::Node::setContentSize(Node *this,Size *param_1);
Vec2 * __thiscall cocos2d::Node::getAnchorPointInPoints(Node *this);
Vec2 * __thiscall cocos2d::Node::getAnchorPoint(Node *this);
void __thiscall cocos2d::Node::setAnchorPoint(Node *this,Vec2 *param_1);
float __thiscall cocos2d::Node::getSkewY(Node *this);
void __thiscall cocos2d::Node::setSkewY(Node *this,float param_1);
float __thiscall cocos2d::Node::getSkewX(Node *this);
void __thiscall cocos2d::Node::setSkewX(Node *this,float param_1);
float __thiscall cocos2d::Node::getPositionZ(Node *this);
void __thiscall cocos2d::Node::setPositionZ(Node *this,float param_1);
void __thiscall cocos2d::Node::getPosition3D(Node *this);
void __thiscall cocos2d::Node::setPosition3D(Node *this,Vec3 *param_1);
float __thiscall cocos2d::Node::getPositionY(Node *this);
void __thiscall cocos2d::Node::setPositionY(Node *this,float param_1);
float __thiscall cocos2d::Node::getPositionX(Node *this);
void __thiscall cocos2d::Node::setPositionX(Node *this,float param_1);
Vec2 * __thiscall cocos2d::Node::getPositionNormalized(Node *this);
Vec2 * __thiscall cocos2d::Node::getPosition(Node *this);
void __thiscall cocos2d::Node::getPosition(Node *this,float *param_1,float *param_2);
void __thiscall cocos2d::Node::setPositionNormalized(Node *this,Vec2 *param_1);
void __thiscall cocos2d::Node::setPosition(Node *this,Vec2 *param_1);
void __thiscall cocos2d::Node::setPosition(Node *this,float param_1,float param_2);
float __thiscall cocos2d::Node::getScale(Node *this);
void __thiscall cocos2d::Node::setScale(Node *this,float param_1);
void __thiscall cocos2d::Node::setScale(Node *this,float param_1,float param_2);
float __thiscall cocos2d::Node::getScaleZ(Node *this);
void __thiscall cocos2d::Node::setScaleZ(Node *this,float param_1);
float __thiscall cocos2d::Node::getScaleY(Node *this);
void __thiscall cocos2d::Node::setScaleY(Node *this,float param_1);
float __thiscall cocos2d::Node::getScaleX(Node *this);
void __thiscall cocos2d::Node::setScaleX(Node *this,float param_1);
void __thiscall cocos2d::Node::setGlobalZOrder(Node *this,float param_1);
void __thiscall cocos2d::Node::_setLocalZOrder(Node *this,int param_1);
void __thiscall cocos2d::Node::setLocalZOrder(Node *this,int param_1);
void __thiscall cocos2d::Node::updateColor(Node *this);
void __thiscall cocos2d::Node::worldToNodeTransform(Node *this);
void __thiscall cocos2d::Node::nodeToWorldTransform(Node *this);
void __thiscall cocos2d::Node::parentToNodeTransform(Node *this);
void __thiscall cocos2d::Node::nodeToParentTransform(Node *this);
Scheduler * __thiscall cocos2d::Node::getScheduler(Node *this);
Scheduler * __thiscall cocos2d::Node::getScheduler(Node *this);
ActionManager * __thiscall cocos2d::Node::getActionManager(Node *this);
ActionManager * __thiscall cocos2d::Node::getActionManager(Node *this);
EventDispatcher * __thiscall cocos2d::Node::getEventDispatcher(Node *this);
void __thiscall cocos2d::Node::boundingBox(Node *this);
Ref * __thiscall cocos2d::Node::getUserObject(Node *this);
Ref * __thiscall cocos2d::Node::getUserObject(Node *this);
void * __thiscall cocos2d::Node::getUserData(Node *this);
void * __thiscall cocos2d::Node::getUserData(Node *this);
Node * __thiscall cocos2d::Node::getParent(Node *this);
Node * __thiscall cocos2d::Node::getParent(Node *this);
Vector<> * __thiscall cocos2d::Node::getChildren(Node *this);
Vector<> * __thiscall cocos2d::Node::getChildren(Node *this);
void __thiscall cocos2d::Node::ignoreAnchorPointForPosition(Node *this,bool param_1);
float __thiscall cocos2d::Node::getRotationY(Node *this);
void __thiscall cocos2d::Node::setRotationY(Node *this,float param_1);
float __thiscall cocos2d::Node::getRotationX(Node *this);
void __thiscall cocos2d::Node::setRotationX(Node *this,float param_1);
float __thiscall cocos2d::Node::getVertexZ(Node *this);
void __thiscall cocos2d::Node::setVertexZ(Node *this,float param_1);
Vec2 * __thiscall cocos2d::Node::getNormalizedPosition(Node *this);
void __thiscall cocos2d::Node::setNormalizedPosition(Node *this,Vec2 *param_1);
float __thiscall cocos2d::Node::getGlobalZOrder(Node *this);
int __thiscall cocos2d::Node::getZOrder(Node *this);
int __thiscall cocos2d::Node::getLocalZOrder(Node *this);
void __thiscall cocos2d::Node::setZOrder(Node *this,int param_1);
bool __thiscall cocos2d::Node::init(Node *this);
void __thiscall cocos2d::Node::update(Node *this,float param_1);
void __thiscall cocos2d::Node::getDescription(Node *this);
