void _StartAddress_005a9c80(int *param_1);
void _StartAddress_005abca0(int param_1);
void __fastcall __security_check_cookie(int param_1);
void __ArrayUnwind(void *param_1,uint param_2,uint param_3,_func_void_void_ptr *param_4);
uint __cdecl __crt_fast_encode_pointer<>(uint param_1);
void __cdecl __scrt_initialize_thread_safe_statics_platform_specific(void);
void __Init_thread_abort(undefined4 *param_1);
void __Init_thread_notify(void);
void __cdecl __Init_thread_wait(DWORD param_1);
undefined4 ___scrt_acquire_startup_lock(void);
int __cdecl ___scrt_initialize_crt(int param_1);
undefined4 __cdecl ___scrt_initialize_onexit_tables(int param_1);
uint __cdecl ___scrt_is_nonwritable_in_current_image(int param_1);
int __cdecl ___scrt_release_startup_lock(char param_1);
undefined1 __cdecl ___scrt_uninitialize_crt(undefined4 param_1,char param_2);
_onexit_t __cdecl __onexit(_onexit_t _Func);
int __cdecl _atexit(_func_4879 *param_1);
void __cdecl ___raise_securityfailure(_EXCEPTION_POINTERS *param_1);
void __cdecl ___report_gsfailure(void);
void ___report_rangecheckfailure(void);
void __cdecl ___report_securityfailure(undefined4 param_1);
void __cdecl __SEH_prolog4(undefined4 param_1,int param_2);
void ___scrt_fastfail(void);
WORD ___scrt_get_show_window_mode(void);
undefined4 ___isa_available_init(void);
bool ___scrt_is_ucrt_dll_in_use(void);
uint ___get_entropy(void);
void __cdecl ___security_init_cookie(void);
void __std_exception_copy(void);
void __std_exception_destroy(void);
void _CxxThrowException(void *pExceptionObject,ThrowInfo *pThrowInfo);
int __cdecl _callnewh(size_t _Size);
void _configure_narrow_argv(void);
void _initialize_narrow_environment(void);
void __cdecl _cexit(void);
void _set_app_type(void);
void __setusermatherr(void);
void __cdecl _exit(int _Code);
errno_t __cdecl _set_fmode(int _Mode);
int __cdecl _configthreadlocale(int _Flag);
void _set_new_mode(void);
void __p__commode(void);
errno_t __cdecl _controlfp_s(uint *_CurrentState,uint _NewValue,uint _Mask);
undefined8 __alldvrm(uint param_1,uint param_2,uint param_3,uint param_4);
void __alloca_probe(void);
uint __alloca_probe_16(void);
uint __alloca_probe_8(void);
undefined8 __aulldiv(uint param_1,uint param_2,uint param_3,uint param_4);
void _CIatan2(void);
void _CIfmod(void);
