typedef struct _devicemodeW _devicemodeW, *P_devicemodeW;


typedef ulong DWORD;


struct _devicemodeW {
    WCHAR dmDeviceName[32];
    WORD dmSpecVersion;
    WORD dmDriverVersion;
    WORD dmSize;
    WORD dmDriverExtra;
    DWORD dmFields;
    union _union_660 field6_0x4c;
    short dmColor;
    short dmDuplex;
    short dmYResolution;
    short dmTTOption;
    short dmCollate;
    WCHAR dmFormName[32];
    WORD dmLogPixels;
    DWORD dmBitsPerPel;
    DWORD dmPelsWidth;
    DWORD dmPelsHeight;
    union _union_663 field17_0xb4;
    DWORD dmDisplayFrequency;
    DWORD dmICMMethod;
    DWORD dmICMIntent;
    DWORD dmMediaType;
    DWORD dmDitherType;
    DWORD dmReserved1;
    DWORD dmReserved2;
    DWORD dmPanningWidth;
    DWORD dmPanningHeight;
};


typedef struct _devicemodeW DEVMODEW;


typedef struct _DCB _DCB, *P_DCB;


struct _DCB {
    DWORD DCBlength;
    DWORD BaudRate;
    DWORD fBinary:1;
    DWORD fParity:1;
    DWORD fOutxCtsFlow:1;
    DWORD fOutxDsrFlow:1;
    DWORD fDtrControl:2;
    DWORD fDsrSensitivity:1;
    DWORD fTXContinueOnXoff:1;
    DWORD fOutX:1;
    DWORD fInX:1;
    DWORD fErrorChar:1;
    DWORD fNull:1;
    DWORD fRtsControl:2;
    DWORD fAbortOnError:1;
    DWORD fDummy2:17;
    WORD wReserved;
    WORD XonLim;
    WORD XoffLim;
    BYTE ByteSize;
    BYTE Parity;
    BYTE StopBits;
    char XonChar;
    char XoffChar;
    char ErrorChar;
    char EofChar;
    char EvtChar;
    WORD wReserved1;
};


typedef struct DotNetPdbInfo DotNetPdbInfo, *PDotNetPdbInfo;


struct DotNetPdbInfo {
    char signature[4];
    GUID guid;
    dword age;
    char pdbpath[50];
};


typedef void *destructor_type;


typedef __uint64 DWORD64;


typedef enum DISPLAYCONFIG_SCANLINE_ORDERING {
    DISPLAYCONFIG_SCANLINE_ORDERING_FORCE_UINT32=-1,
    DISPLAYCONFIG_SCANLINE_ORDERING_UNSPECIFIED=0,
    DISPLAYCONFIG_SCANLINE_ORDERING_PROGRESSIVE=1,
    DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED=2,
    DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_UPPERFIELDFIRST=2,
    DISPLAYCONFIG_SCANLINE_ORDERING_INTERLACED_LOWERFIELDFIRST=3
} DISPLAYCONFIG_SCANLINE_ORDERING;


// WARNING! conflicting data type names: /ois.pdb/LPSTARTUPINFOW - /winbase.h/LPSTARTUPINFOW
typedef enum DefaultMessageIDTypes {
    ID_CONNECTED_PING=0,
    ID_UNCONNECTED_PING=1,
    ID_UNCONNECTED_PING_OPEN_CONNECTIONS=2,
    ID_CONNECTED_PONG=3,
    ID_DETECT_LOST_CONNECTIONS=4,
    ID_OPEN_CONNECTION_REQUEST_1=5,
    ID_OPEN_CONNECTION_REPLY_1=6,
    ID_OPEN_CONNECTION_REQUEST_2=7,
    ID_OPEN_CONNECTION_REPLY_2=8,
    ID_CONNECTION_REQUEST=9,
    ID_REMOTE_SYSTEM_REQUIRES_PUBLIC_KEY=10,
    ID_OUR_SYSTEM_REQUIRES_SECURITY=11,
    ID_PUBLIC_KEY_MISMATCH=12,
    ID_OUT_OF_BAND_INTERNAL=13,
    ID_SND_RECEIPT_ACKED=14,
    ID_SND_RECEIPT_LOSS=15,
    ID_CONNECTION_REQUEST_ACCEPTED=16,
    ID_CONNECTION_ATTEMPT_FAILED=17,
    ID_ALREADY_CONNECTED=18,
    ID_NEW_INCOMING_CONNECTION=19,
    ID_NO_FREE_INCOMING_CONNECTIONS=20,
    ID_DISCONNECTION_NOTIFICATION=21,
    ID_CONNECTION_LOST=22,
    ID_CONNECTION_BANNED=23,
    ID_INVALID_PASSWORD=24,
    ID_INCOMPATIBLE_PROTOCOL_VERSION=25,
    ID_IP_RECENTLY_CONNECTED=26,
    ID_TIMESTAMP=27,
    ID_UNCONNECTED_PONG=28,
    ID_ADVERTISE_SYSTEM=29,
    ID_DOWNLOAD_PROGRESS=30,
    ID_REMOTE_DISCONNECTION_NOTIFICATION=31,
    ID_REMOTE_CONNECTION_LOST=32,
    ID_REMOTE_NEW_INCOMING_CONNECTION=33,
    ID_FILE_LIST_TRANSFER_HEADER=34,
    ID_FILE_LIST_TRANSFER_FILE=35,
    ID_FILE_LIST_REFERENCE_PUSH_ACK=36,
    ID_DDT_DOWNLOAD_REQUEST=37,
    ID_TRANSPORT_STRING=38,
    ID_REPLICA_MANAGER_CONSTRUCTION=39,
    ID_REPLICA_MANAGER_SCOPE_CHANGE=40,
    ID_REPLICA_MANAGER_SERIALIZE=41,
    ID_REPLICA_MANAGER_DOWNLOAD_STARTED=42,
    ID_REPLICA_MANAGER_DOWNLOAD_COMPLETE=43,
    ID_RAKVOICE_OPEN_CHANNEL_REQUEST=44,
    ID_RAKVOICE_OPEN_CHANNEL_REPLY=45,
    ID_RAKVOICE_CLOSE_CHANNEL=46,
    ID_RAKVOICE_DATA=47,
    ID_AUTOPATCHER_GET_CHANGELIST_SINCE_DATE=48,
    ID_AUTOPATCHER_CREATION_LIST=49,
    ID_AUTOPATCHER_DELETION_LIST=50,
    ID_AUTOPATCHER_GET_PATCH=51,
    ID_AUTOPATCHER_PATCH_LIST=52,
    ID_AUTOPATCHER_REPOSITORY_FATAL_ERROR=53,
    ID_AUTOPATCHER_CANNOT_DOWNLOAD_ORIGINAL_UNMODIFIED_FILES=54,
    ID_AUTOPATCHER_FINISHED_INTERNAL=55,
    ID_AUTOPATCHER_FINISHED=56,
    ID_AUTOPATCHER_RESTART_APPLICATION=57,
    ID_NAT_PUNCHTHROUGH_REQUEST=58,
    ID_NAT_CONNECT_AT_TIME=59,
    ID_NAT_GET_MOST_RECENT_PORT=60,
    ID_NAT_CLIENT_READY=61,
    ID_NAT_TARGET_NOT_CONNECTED=62,
    ID_NAT_TARGET_UNRESPONSIVE=63,
    ID_NAT_CONNECTION_TO_TARGET_LOST=64,
    ID_NAT_ALREADY_IN_PROGRESS=65,
    ID_NAT_PUNCHTHROUGH_FAILED=66,
    ID_NAT_PUNCHTHROUGH_SUCCEEDED=67,
    ID_READY_EVENT_SET=68,
    ID_READY_EVENT_UNSET=69,
    ID_READY_EVENT_ALL_SET=70,
    ID_READY_EVENT_QUERY=71,
    ID_LOBBY_GENERAL=72,
    ID_RPC_REMOTE_ERROR=73,
    ID_RPC_PLUGIN=74,
    ID_FILE_LIST_REFERENCE_PUSH=75,
    ID_READY_EVENT_FORCE_ALL_SET=76,
    ID_ROOMS_EXECUTE_FUNC=77,
    ID_ROOMS_LOGON_STATUS=78,
    ID_ROOMS_HANDLE_CHANGE=79,
    ID_LOBBY2_SEND_MESSAGE=80,
    ID_LOBBY2_SERVER_ERROR=81,
    ID_FCM2_NEW_HOST=82,
    ID_FCM2_REQUEST_FCMGUID=83,
    ID_FCM2_RESPOND_CONNECTION_COUNT=84,
    ID_FCM2_INFORM_FCMGUID=85,
    ID_FCM2_UPDATE_MIN_TOTAL_CONNECTION_COUNT=86,
    ID_FCM2_VERIFIED_JOIN_START=87,
    ID_FCM2_VERIFIED_JOIN_CAPABLE=88,
    ID_FCM2_VERIFIED_JOIN_FAILED=89,
    ID_FCM2_VERIFIED_JOIN_ACCEPTED=90,
    ID_FCM2_VERIFIED_JOIN_REJECTED=91,
    ID_UDP_PROXY_GENERAL=92,
    ID_SQLite3_EXEC=93,
    ID_SQLite3_UNKNOWN_DB=94,
    ID_SQLLITE_LOGGER=95,
    ID_NAT_TYPE_DETECTION_REQUEST=96,
    ID_NAT_TYPE_DETECTION_RESULT=97,
    ID_ROUTER_2_INTERNAL=98,
    ID_ROUTER_2_FORWARDING_NO_PATH=99,
    ID_ROUTER_2_FORWARDING_ESTABLISHED=100,
    ID_ROUTER_2_REROUTED=101,
    ID_TEAM_BALANCER_INTERNAL=102,
    ID_TEAM_BALANCER_REQUESTED_TEAM_FULL=103,
    ID_TEAM_BALANCER_REQUESTED_TEAM_LOCKED=104,
    ID_TEAM_BALANCER_TEAM_REQUESTED_CANCELLED=105,
    ID_TEAM_BALANCER_TEAM_ASSIGNED=106,
    ID_LIGHTSPEED_INTEGRATION=107,
    ID_XBOX_LOBBY=108,
    ID_TWO_WAY_AUTHENTICATION_INCOMING_CHALLENGE_SUCCESS=109,
    ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_SUCCESS=110,
    ID_TWO_WAY_AUTHENTICATION_INCOMING_CHALLENGE_FAILURE=111,
    ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_FAILURE=112,
    ID_TWO_WAY_AUTHENTICATION_OUTGOING_CHALLENGE_TIMEOUT=113,
    ID_TWO_WAY_AUTHENTICATION_NEGOTIATION=114,
    ID_CLOUD_POST_REQUEST=115,
    ID_CLOUD_RELEASE_REQUEST=116,
    ID_CLOUD_GET_REQUEST=117,
    ID_CLOUD_GET_RESPONSE=118,
    ID_CLOUD_UNSUBSCRIBE_REQUEST=119,
    ID_CLOUD_SERVER_TO_SERVER_COMMAND=120,
    ID_CLOUD_SUBSCRIPTION_NOTIFICATION=121,
    ID_LIB_VOICE=122,
    ID_RELAY_PLUGIN=123,
    ID_NAT_REQUEST_BOUND_ADDRESSES=124,
    ID_NAT_RESPOND_BOUND_ADDRESSES=125,
    ID_FCM2_UPDATE_USER_CONTEXT=126,
    ID_RESERVED_3=127,
    ID_RESERVED_4=128,
    ID_RESERVED_5=129,
    ID_RESERVED_6=130,
    ID_RESERVED_7=131,
    ID_RESERVED_8=132,
    ID_RESERVED_9=133,
    ID_USER_PACKET_ENUM=134
} DefaultMessageIDTypes;


typedef struct DatagramHistoryNode DatagramHistoryNode, *PDatagramHistoryNode;


struct DatagramHistoryNode {
};


typedef struct DockingRequest DockingRequest, *PDockingRequest;


struct DockingRequest { // PlaceHolder Structure
};


typedef enum DifficultyMode {
} DifficultyMode;


typedef enum DamageAngle {
} DamageAngle;


typedef enum DamageType {
} DamageType;


typedef struct __Double __Double, *P__Double;


struct __Double { // PlaceHolder Structure
};


typedef struct Director Director, *PDirector;


struct Director { // PlaceHolder Structure
};


typedef struct DirectionLight DirectionLight, *PDirectionLight;


struct DirectionLight { // PlaceHolder Structure
};


typedef struct DelayTime DelayTime, *PDelayTime;


struct DelayTime { // PlaceHolder Structure
};


typedef enum DispatchMode {
} DispatchMode;
