typedef enum JOB_OBJECT_IO_RATE_CONTROL_FLAGS {
    JOB_OBJECT_IO_RATE_CONTROL_ENABLE=1,
    JOB_OBJECT_IO_RATE_CONTROL_STANDALONE_VOLUME=2,
    JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS=3
} JOB_OBJECT_IO_RATE_CONTROL_FLAGS;


typedef enum JOB_OBJECT_NET_RATE_CONTROL_FLAGS {
    JOB_OBJECT_NET_RATE_CONTROL_ENABLE=1,
    JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH=2,
    JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG=4,
    JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS=7
} JOB_OBJECT_NET_RATE_CONTROL_FLAGS;


typedef struct Junk Junk, *PJunk;


struct Junk { // PlaceHolder Structure
};


typedef struct JumpPoint JumpPoint, *PJumpPoint;


struct JumpPoint { // PlaceHolder Structure
};
