// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class AIDesire {
public:
    void removeDesireTarget(GameObject * param_1);
    void removeSensorObject(SensorData * param_1);
    ~AIDesire();
    std::string * describe();
    AIDesire(undefined4 param_1, void * param_3);
};
