// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class AIHunt {
public:
    void recalculateLogic();
    void enterState();
    void hitTravelLocation();
    void doneAtLocation();
    void runTravelLogic(float param_1);
    void runLurkLogic(float param_1);
    void runLogic(float param_1);
    static undefined4 vftable;  // data symbol used as AIHunt::vftable
};
