// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class AIPatrol {
public:
    void doneAtLocation();
    void enterState();
    void leaveState();
    void runLogic(float param_1);
    void runZoneBreachLogic(float param_1);
    void removeDesireTarget(GameObject * param_1);
    bool hasBeenWarned(void * param_2);
    void vesselFailedHackingMe(Ship * param_1);
    void vesselHackedMe(Ship * param_1);
    static undefined4 vftable;  // data symbol used as AIPatrol::vftable
};
