// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class AIPiracy {
public:
    int shipWeight(SensorData * param_1);
    void ignoreVessel(void * param_2);
    void recalculateLogic();
    void runLogic(float param_1);
    void enterState();
    void leaveState();
    void runApproachTargetLogic(float param_1);
    void removeDesireTarget(GameObject * param_1);
    void removeSensorObject(SensorData * param_1);
    char * describe();
    static undefined4 vftable;  // data symbol used as AIPiracy::vftable
};
