// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ButtonElement {
public:
    ButtonElement(undefined4 param_1, void * param_3);
    void render(int param_1, ghidra::vector * param_2, ghidra::vector * param_3, Node * param_4);
};
