// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class CargoHold {
public:
    void describePod(int param_1, bool param_2);
    void configureSlots(int param_1, int param_2);
    int totalUnitsFree();
    std::string * describeCargo(bool param_1);
    bool addToHold(int param_1, int param_2, int param_3);
    void removeFromHold(int param_1, int param_2, int param_3);
    void removeFromHold(Good * param_1, int param_2, int param_3);
    int getPodSellCost(int param_1);
    bool addPod(int param_1);
    bool podExists(int param_1);
    void removePod(int param_1);
    void addOption(int param_1, GoodContainmentOption param_2);
    int amountCanHold(Good * param_1);
    int amountCanHold(GoodContainmentOption param_1);
    int totalBaseValue();
    int amountHeld(int param_1);
    int amountHeld(GoodContainmentOption param_1);
    void addComponent(ShipComponent * param_1);
    bool hasComponent(int param_1);
    void removeComponent(ShipComponent * param_1);
};
