// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class CharacterAnimationManager {
public:
    void addAnimation(std::string * param_2);
    std::string * getRandomAnimation(std::string * param_2, void * param_3);
    AnimationSet * getSet(char * param_2);
};
