// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ComponentInterfaceInstance {
public:
    int getComponentCount();
    void applyConfiguration(ModuleConfiguration * param_1);
    bool setActive(int param_1);
    int damagePercent();
    void damageAtLocation(int param_1, DamageType param_2, int param_3, int param_4);
    void damage(int param_1, DamageType param_2);
    int getEfficiencyPercent();
    float getEmissionsModifier();
    float getPowerModifier();
};
