// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ComputerSystem {
public:
    void renderArticle(CommsData * param_1, int param_2);
    void sendCurrentDraft();
    void doneWithDraft();
    void showDrafts();
    void doneWithEmail();
    void showEmails();
    void doneWithArticle();
    void showArticles();
    void doneWithFile();
    Article * getArticle(char * param_2);
    void renderEmail(CommsData * param_1, int param_2);
    int getMostRecentArticles(int param_1, bool param_2);
    void renderArticles(CommsData * param_1);
    void selectedArticle(int param_1);
    void renderEmails(CommsData * param_1);
    void renderDraft(CommsData * param_1, int param_2);
    void renderDrafts(int param_1, std::string * param_3);
    void selectedEmail(int param_1);
    void selectedDraft(int param_1);
    void runArticleLogic(float param_1);
    void syncArticles(CommsData * param_1, uint param_2);
    void renderFiles(int param_1);
};
