// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Contract {
public:
    int hoursLeft();
    void describeThreeLines(bool param_1, bool param_2);
    void describeShort();
    void describeShortToVector();
    void performContractCompletion();
    void performContractFailure();
};
