// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ContractManager {
public:
    ContractClass * getRandomContractClassForLocation(undefined4 param_1_00, uint param_1, int param_3, int param_4, undefined4 param_5, void * param_6);
    ContractClass * getContractClassForIdentifier(undefined4 param_1, char * param_2);
    Contract * generateContract();
    static int m_contractNumber;  // data symbol used as ContractManager::m_contractNumber
};
