// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ConversationManager {
public:
    ConversationElement * addConversationElement(void * param_2);
    void addConversationReq(void * param_2);
    ConversationOption * addConversationOption(void * param_2);
    void addConversationOptionReq(void * param_2);
    void addConversationOptionAction(void * param_2);
    void addConversationElementAction(void * param_2);
    Conversation * getConversation(int param_2, char param_3, char * param_4);
    int hasConversationToForce(char * param_2);
    void keyHit(KeyCode param_1);
    void performElementActions(ConversationElement * param_1);
};
