// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ConversationOption {
public:
    ConversationOption(undefined4 param_1, undefined4 param_2, void * param_4);
    bool checkReq(CargoHold * param_1, BankAccount * param_2);
};
