// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class DataLoader {
public:
    static bool loadNewsArticle(undefined4 * param_1);
    static bool loadInfoArticle(void * param_1);
    static void loadChatter(void * param_1);
    static void loadAllChatter();
    static void createSector();
    static void createGameState();
    static void createJunkSpawn();
    static void createPlanet();
    static void createTextMarker();
    static void createNebula();
    static void createAsteroidField();
    static void createMoon();
    static void createPassengerQuirk();
    static void createPassenger(void * param_1);
    static void createPassengers();
    static void createJunk();
    static void createJumpPoint();
    static void createSpawnPoint();
    static void createZone();
    static void createNavpoint();
    static void createStar();
    static void addBootElement(void * param_1);
    static void addModuleConfiguration(void * param_1);
    static void createModule();
    static void createHazard();
    static void createGood();
    static void createTradeLocation();
    static void addDockingElement(void * param_1);
    static void addHullDamageChanceElement(std::string * param_1, int param_2);
    static void addHullStrengthElement(std::string * param_1, int param_2);
    static void createShipClass();
    static void addComponentInterfaceSlot(void * param_1);
    static void addComponentInterfaceLine(void * param_1);
    static void createComponentInterface();
    static void createComponentClass();
    static void addCharacterOverlay(void * param_1);
    static void addCharacterComponent(void * param_1);
    static void addCharacterAddition(void * param_1);
    static void createTrack();
    static void createAds();
    static void createEmotes();
    static void createAnimationFrames();
    static void createCharacterClass();
    static void createCharacter();
    static void createConversation();
    static void createConversationElement();
    static void createConversationOption();
    static void createContract();
    static void createWeaponClass();
    static void createDepot();
    static void createSpaceStation();
    static void createJumpgate();
    static void configureLocations(LocationManager * param_1);
    static void configureWidgetExistValues(std::string * param_1);
    static void configureTextDataForWidget(void * param_1);
    static void createWidget(void * param_1);
    static void checkAndCreateWidget(void * param_1);
    static void createScreen();
    static void createScenario();
    static void createNavMarker();
    static void addShipDestination(void ** param_1);
    static void createShip();
    static void createCharacterAnimationSet();
    static void createStats();
    static void createTimedFlags();
    static void createTimedFlag();
    static void createEmailFileMetaData();
    static void createEmail();
    static void createDraftSet();
    static void createDraft();
    static void createSynthetic();
    static void createFaction();
    static void createStoryNote();
    static void createRoom();
    static void createRoomObject();
    static void parseGeneric(uchar * param_1);
};
