// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class DatagramHeaderFormat {
public:
    void Serialize(BitStream * param_1);
    void Deserialize(BitStream * param_1);
};
