// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class DummyObject {
public:
    static undefined4 vftable_for_cocos2d__Node_;  // data symbol used as DummyObject::vftable_for_cocos2d__Node_
    static undefined4 vftable_for_cocos2d__TextureProtocol_;  // data symbol used as DummyObject::vftable_for_cocos2d__TextureProtocol_
};
