// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class EmailManager {
public:
    void resetState();
    Email * getEmail(char * param_2);
    EmailDraftSet * getDraftSet(char * param_2);
    void markEmailSent(char * param_2);
    void sendEmail(CommsData * param_1, Email * param_2);
    void getEmailStateText();
    void runLogic(CommsData * param_1, float param_2, bool param_3);
    int getUnsentEmailCount();
    int getUnreadEmailCount();
    int getUnreadNewsArticleCount();
    int getDraftCount();
    void syncEmails(CommsData * param_1);
    void addCustomEmail(std::string * param_2);
};
