// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Faction {
public:
    ~Faction();
    void getAccess();
    bool officeAtLocation(char * param_2);
    void modifyState(int param_1);
    int getCurrentTier();
    int amountCanBorrow();
    void runDayEndLogic();
    void repay(int param_1);
};
