// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class FlagManager {
public:
    void setFlag(char * param_2);
    bool flagSet(void * param_2);
    void reset();
    void runFlagLogic(float param_1, FlagTimeToSet * param_2);
    void runLogic(float param_1);
    FlagTimeToSet * addFlagToSet();
};
