// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class FogInstance {
public:
    void resetFog();
    static int getChunk(float param_1);
    bool removeFogInRadius(int param_1, int param_2, undefined4 param_4, undefined4 param_5, float param_6);
    bool fogObscuresPoint(float param_2, float param_3);
};
