// GENERATED free-function prototypes (Ghidra types; hand-edit as they are understood).
#pragma once
#include "ois/ois_fwd.hpp"

float angleInDegreesFrom(float param_1, undefined4 param_2, float param_3);
ComparisonCheckType comparisonFromString(void * param_1);
long crashHandler(_EXCEPTION_POINTERS * param_1);
void _dynamic_initializer_for__firstTimeBonusStr__();
__uint64 * ___local_stdio_printf_options();
int __vsnprintf_l(char * _DstBuf, size_t _MaxCount, char * _Format, _locale_t _Locale, va_list _ArgList);
int _sprintf(char * _Dest, char * _Format, ...);
int __vfprintf_l(FILE * _File, char * _Format, _locale_t _Locale, va_list _ArgList);
int _printf(char * _Format, ...);
int _vsnprintf(char * _Dest, size_t _Count, char * _Format, va_list _Args);
int _fprintf(FILE * _File, char * _Format, ...);
char * _Itoa(int param_1, char * param_2);
void __security_check_cookie(int param_1);
void __ArrayUnwind(void * param_1, uint param_2, uint param_3, _func_void_void_ptr * param_4);
undefined4 __scrt_initialize_thread_safe_statics();
void __scrt_initialize_thread_safe_statics_platform_specific();
void __scrt_uninitialize_thread_safe_statics();
void __Init_thread_abort(undefined4 * param_1);
void __Init_thread_footer(int * param_1);
void __Init_thread_header(int * param_1);
void __Init_thread_notify();
void __Init_thread_wait(DWORD param_1);
undefined4 ___scrt_acquire_startup_lock();
int ___scrt_initialize_crt(int param_1, int param_2);
undefined4 ___scrt_initialize_onexit_tables(int param_1);
uint ___scrt_is_nonwritable_in_current_image(int param_1);
int ___scrt_release_startup_lock(char param_1);
undefined1 ___scrt_uninitialize_crt(Ship * param_1, char param_2);
_onexit_t __onexit(_onexit_t _Func);
int _atexit(_func_4879 * param_1);
void ___raise_securityfailure(_EXCEPTION_POINTERS * param_1);
void ___report_gsfailure();
void ___report_rangecheckfailure();
void ___report_securityfailure(undefined4 param_1);
int __scrt_common_main_seh();
void _WinMainCRTStartup();
void __scrt_throw_std_bad_alloc();
void __scrt_throw_std_bad_array_new_length();
void __SEH_prolog4(undefined4 param_1, int param_2);
void __SEH_epilog4();
void __except_handler4(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void ___scrt_fastfail();
ushort ___scrt_get_show_window_mode();
int ___scrt_initialize_mta(_exception * _Except);
int ___scrt_exe_initialize_mta(_exception * _Except);
uint ___scrt_is_managed_app();
void ___scrt_set_unhandled_exception_filter();
void __crt_debugger_hook(int param_1);
undefined4 ___isa_available_init();
undefined4 __get_startup_argv_mode();
bool ___scrt_is_ucrt_dll_in_use();
uint __get_entropy();
void ___security_init_cookie();
undefined4 __get_startup_file_mode();
void __scrt_initialize_type_info();
void __initialize_default_precision();
__uint64 * ___local_stdio_scanf_options();
void ___scrt_initialize_default_local_stdio_options();
bool ___scrt_is_user_matherr_present();
undefined * ___scrt_get_dyn_tls_init_callback();
undefined * ___scrt_get_dyn_tls_dtor_callback();
void __RTC_Initialize();
void __RTC_Terminate();
void ___std_terminate();
void __purecall();
void ___std_exception_copy();
void ___std_exception_destroy();
void __except_handler4_common();
int __callnewh(size_t _Size);
void __configure_narrow_argv();
void __initialize_narrow_environment();
void __initialize_onexit_table();
void __register_onexit_function();
void __crt_atexit();
void __cexit();
void __set_app_type();
void ___setusermatherr();
void __get_narrow_winmain_command_line();
void __initterm();
void __initterm_e();
void __exit(int _Code);
errno_t __set_fmode(int _Mode);
void __register_thread_local_exe_atexit_callback();
int __configthreadlocale(int _Flag);
void __set_new_mode();
void ___p__commode();
errno_t __controlfp_s(uint * _CurrentState, uint _NewValue, uint _Mask);
undefined8 __alldvrm(uint param_1, uint param_2, uint param_3, uint param_4);
void __alloca_probe();
uint __alloca_probe_16();
uint __alloca_probe_8();
undefined8 __aulldiv(uint param_1, uint param_2, uint param_3, uint param_4);
ulonglong __ftoui3();
ulonglong __ftoul3();
ulonglong __ftol3();
ulonglong __ftol3_NaN(int param_1);
ulonglong __ftol3_work(int param_1);
ulonglong __ftol3_common(undefined4 param_1);
undefined8 __ftol3_arg_error(undefined4 param_1);
void __ftol3_except(undefined4 param_1, int param_2);
void __dtoui3();
void __dtoul3();
uint __dtol3();
uint __dtol3_NaN(int param_1);
ulonglong __dtol3_work(int param_1);
void __ultod3();
void __ltod3();
ulonglong __ftol2_sse(undefined4 param_1, undefined4 param_2);
int __ftol2_pentium4();
ulonglong __ftol2_sse_excpt(undefined4 param_1, undefined4 param_2);
ulonglong __ftol2();
void __CIatan2();
void __CIfmod();
void __libm_sse2_cos_precise();
void __libm_sse2_sin_precise();
void __except1();
void debugPrint(char * param_1, char * param_2, ...);
int diceRoll(Dice * param_1);
int diceRoll(int param_1, int param_2, int param_3);
float differenceBetweenAngles(float param_1, float param_2);
float fastDistance(Vec2 * param_1, Vec2 * param_2);
void firstWordSeparated(char * param_1);
int find_pe_section(int param_1, uint param_2);
DifficultyMode getDifficulty(void * param_1);
Quadrant getQuadrant(void * param_1);
ModuleSlotType getModuleSlotTypeForString(void * param_1);
ScenarioCategory getScenarioCategory(void * param_1);
ScenarioType getScenarioType(void * param_1);
ShipDataType getShipDataType(void * param_1);
ShipDataCheckType getShipCheckDataType(void * param_1);
ShipTextDataType getShipTextDataType(void * param_1);
ShipDataInputType getShipDataInputType(undefined4 * param_1);
void * getShipCheckDataPointer(ShipDataInputType param_1);
void getShipCheckDataPossibleValues(ShipDataInputType param_1);
ShipCommand getShipCommandType(void * param_1);
CaptainStyle getCaptainStyle(void * param_1);
CaptainExperience getCaptainExperience(void * param_1);
ShipLook getShipLookup(void * param_1);
GoodContainmentOption getContainmentOption(void * param_1);
HullLocation getHullLocationForString(undefined4 * param_1);
CharacterMouthState getCharacterMouthState(void * param_1);
CharacterEyeState getCharacterEyeState(void * param_1);
OverlaySegment getOverlaySegment(void * param_1);
CharacterPosition getCharacterPosition(void * param_1);
Sound getSound(void * param_1);
__uint64 GetTimeUS_Windows();
SimpleMutex * GetPoolMutex();
Quadrant invertQuadrant(Quadrant param_1);
bool isShipDataType(void * param_1);
bool isShipTextDataType(void * param_1);
Sprite * loadSprite(void * param_1);
void loadMapFromFile(void * param_1);
void loadLinesFromFile(void * param_1);
void * operator_new(uint param_1);
void operator_delete(void * param_1, nothrow_t * param_2);
void * operator_new(uint param_1, nothrow_t * param_2);
void operator_delete(void * param_1);
void parseLines(char * param_1, _func_void_uchar_ptr * param_2, bool param_3);
void positionFromPoint();
void positionDelta(float param_1, float param_2);
void printFloatAsMinsAndSeconds(float param_1);
void pre_c_initialization(int param_1, int param_2, int param_3);
undefined4 post_pgo_initialization();
void pre_cpp_initialization();
Quadrant quadrantFor(float param_1, float param_2);
void runDataInputSync(ShipDataInputType param_1);
int random(int param_1);
void replaceCharactersInString(undefined4 * param_1);
void randomPositionWithinRadius(undefined4 param_1, undefined4 param_2);
bool stringStartsWith(uchar * param_1, char * param_2);
bool shipDataCanPrev(ShipDataInputType param_1);
bool shipDataCanNext(ShipDataInputType param_1);
void shipDataChangePrev(ShipDataInputType param_1);
void shipDataChangeNext(ShipDataInputType param_1);
void shipDataChangeTo(ShipDataInputType param_1, int param_2);
int shipDataMax(ShipDataInputType param_1);
void SteamInternal_OnContextInit(void * param_1);
void safeStrCpy(char * param_1);
void strWithMaxLength(word * param_1);
void setTexParams(Texture2D * param_1);
void strUsingArgs(char * param_1, ...);
void stripWhiteSpaceFromBeginning(char * param_1);
bool stringContains(void * param_1);
void splitStringBy(undefined4 * param_1);
uint SuperFastHashIncremental(char * param_1, int param_2, uint param_3);
void terminate();
void unpackDiceFromString(void * param_1);
void unpackDiceString(void * param_1);
void unpackReadableDiceString(void * param_1);
void writeTextToFile(undefined4 * param_1);
void writeString(undefined4 * param_1);
void writeBoolean(undefined4 param_1, undefined4 * param_2);
void writeMetaDataStr(void * param_1);
void FUN_00401110();
void FUN_00401230();
void FUN_00401370();
void FUN_004014f0();
void FUN_00401760();
void FUN_004019b0();
void FUN_00474d49(undefined4 * param_1, undefined4 param_2, uint param_3);
void FUN_0053bf8e();
void FUN_0054098f();
void FUN_0056720f(double param_1, double param_2);
void FUN_00595000(char * param_1, uint param_2, char * param_3);
void FUN_005af900();
void FUN_005af9ec();
void FUN_005b0188();
void FUN_005b0202();
void FUN_005cdd60();
void FUN_005cddc0();
void FUN_005cde20();
void FUN_005cde30();
void FUN_005cde90();
void FUN_005cdef0();
void FUN_005cdf50();
void FUN_005cdfb0();
void FUN_005ce060();
void FUN_005ce070();
void FUN_005ce0d0();
void FUN_005ce130();
void FUN_005ce190();
void FUN_005ce1f0();
void FUN_005ce250();
void FUN_005ce2b0();
void FUN_005ce310();
void FUN_005ce370();
void FUN_005ce3d0();
void FUN_005ce430();
void FUN_005ce490();
void FUN_005ce4f0();
void FUN_005ce550();
void FUN_005ce5b0();
void FUN_005ce610();
void FUN_005ce620();
void FUN_005ce680();
void FUN_005ce6e0();
void FUN_005ce740();
void FUN_005ce7a0();
void FUN_005ce7b0();
void FUN_005ce820();
