// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class GameLogic {
public:
    GameLogic();
    SpaceStation * getNearestTowLocation();
    void createWorld();
    void initialiseClient(bool param_1);
    void shutDownCurrentScenario();
    void initialiseScenario();
    void completeMultiplayerScenario(int param_1);
    void completeSingleplayerScenario(bool param_1);
    void runPlayerDockLogic();
    void addSyntheticInstances();
    void resetSyntheticInstances();
    void clearShipsInScenario(bool param_1);
    void removeNonPlayedShips();
    void resetShipsInScenario(bool param_1);
    void recheckStoryShips();
    void spawnShip(ShipInstance * param_1);
    float getOrbitChangeTime(OrbitState param_1, Ship * param_2);
    bool runShipLogic(Ship * param_1, float param_2, bool param_3);
    bool safeForTimeCompression(std::string * param_1);
    void runStateCheckLogic();
    void runTimeLogic(float param_1);
    void runServerLogic(float param_1);
    void runClientLogic(float param_1);
    void dropDebrisFromShip(Ship * param_1);
    void removeShipOnSettingFlag(undefined4 param_1, char * param_2);
    void entirelyRemoveShip(Ship * param_1, bool param_2);
    int convertedTimeInHours();
    void setHazardState(undefined4 param_1_00, int param_1);
    int calculateJumpDestination(int param_1, int param_2);
    SpaceStation * generateSpaceStation(undefined4 param_1, std::string * param_2);
    Ship * generateShip(undefined4 param_1, undefined4 param_2, int param_3, void * param_4);
    void switchPlayerShipTo(Ship * param_1);
    ModuleType getModuleTypeForIdentifier(undefined4 param_1, void * param_2);
    void addComponentFilter(int param_1, ComponentCategory param_2);
    void addComponentFilterData(int param_1, std::string * param_3);
    void removeSyntheticObject(SyntheticObject * param_1);
    void removeSensorDataFor(Ship * param_1);
    void addCountermeasure(int param_1, float param_3, float param_4, undefined4 param_5, undefined4 param_6, std::string * param_7);
    CounterMeasure * getClosestCounterMeasureTo(undefined4 param_1_00, CounterMeasure * param_1, undefined4 param_3, undefined4 param_4, char * param_5);
    void addExplosionSensorData(undefined4 param_1_00, undefined4 param_1, float param_3, float param_4);
    void explosion(undefined4 param_1_00, int param_1, int param_2, int param_4, undefined4 param_5, float param_6, float param_7);
    void clearPlayerBounties();
    void clearPlayerContracts();
    bool playerHasContract();
    int contractAmountLeftToDeliver(undefined4 param_1, char * param_2);
    bool hasPassenger();
    int getDeliveringGoodValueInPlayerContracts(undefined4 param_1, char * param_2);
    int getPurchaseGoodValueInPlayerContracts(undefined4 param_1, char * param_2);
    void trackGoodsBought(undefined4 param_1, int param_2, char * param_3);
    void checkContracts();
    bool playerHostilePiratesInSector(int param_1);
    bool zoneActive(Zone * param_1);
    void writeObituary();
    void skipIntroSequence();
    void setTimeCompressionText(undefined4 param_1, std::string * param_2);
    void setCombatDifficulty(int param_1);
    void setEconomyDifficulty(int param_1);
    void setStartBonus(int param_1);
    void setStartLocation(int param_1);
    void reportSmuggler();
    void reportPirate(undefined4 param_1, void * param_2);
    void reportPirate(int param_1);
    void getCurrentLocalServers();
    void setLocalServer(char * param_2);
    void getCurrentPlayersAndShips();
    bool canTakeShip();
};
