// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class GameData {
public:
    GameData();
    Ship * getShipWithinDistance(undefined4 param_1_00, int param_1, int param_3, char param_4);
    Ship * getShipWithID(int param_1);
    SpaceStation * getSpaceStation(undefined4 param_1, char * param_2);
    Sector * getSectorOfShip(undefined4 param_1, char * param_2);
    Ship * getShipWithRego(undefined4 param_1, char * param_2);
    Sector * getSectorWithID(int param_1);
    Sector * getSectorWithShortName(undefined4 param_1, char * param_2);
    HazardCategory * getNebulaHazardCategory(int param_1);
    HazardCategory * getAsteroidHazardCategory(int param_1);
    Structure * getStructure(char param_2, char * param_3);
    Room * getRoom(undefined4 param_1, void * param_2);
    GameCharacter * getCharacter(undefined4 param_1, char * param_2);
    GameCharacter * getExtraWithTag(undefined4 param_1, void * param_2);
    void setUniqueObjects(undefined4 param_1, int param_2, byte param_3, void * param_4);
    GameCharacter * getCharacterAtSpawnPoint(undefined4 param_1, char * param_2);
    CharacterLocation * getCharacterLocationAtSpawnPoint(undefined4 param_1, char * param_2);
    ShipModuleClass * getModuleClassWithIdentifier(undefined4 param_1, char * param_2);
    ShipClass * getShipClassWithIdentifier(undefined4 param_1, char * param_2);
    WeaponClass * getWeaponClassWithIdentifier(undefined4 param_1, char * param_2);
    ScreenLayout * getScreenLayout(undefined4 param_1, char * param_2);
    Scenario * getScenario(undefined4 param_1, char * param_2);
    Good * getGoodWithShortName(undefined4 param_1, char * param_2);
    Good * getGood(int param_1);
    StellarObject * getStellarObjectWithinDistance(undefined4 param_1_00, int param_1, undefined4 param_3, undefined4 param_4, float param_5);
    StateModifier * getStateModifier(undefined4 param_1, char * param_2);
    void resetStateModifiers();
    static int s_nextAdID;  // data symbol used as GameData::s_nextAdID
};
