// GENERATED by scripts/ghidra_lower.py -- do not edit.
// Placeholders for library template instances whose template arguments Ghidra erased.
// Declared, never defined: replacing each one with the real std::/cocos2d:: call is the
// work still to do.  `grep -rn ghidra::lib reconstruct/src` finds every use.
#pragma once
#include "ois/ghidra_compat.h"

namespace ghidra { namespace lib {

struct _Binder_t { unsigned char _opaque[16]; };
struct _Compressed_pair_t { unsigned char _opaque[16]; };
struct _Destroy_range_t { unsigned char _opaque[16]; };
struct _Find_unchecked_t { unsigned char _opaque[16]; };
struct _Func_base_t { unsigned char _opaque[16]; };
struct _Func_impl_no_alloc_t { unsigned char _opaque[16]; };
struct _String_val_t { unsigned char _opaque[16]; };
struct _Traits_equal_t { unsigned char _opaque[16]; };
struct _Tree_t { unsigned char _opaque[16]; };
struct _Tree_comp_alloc_t { unsigned char _opaque[16]; };
struct _Tree_node_t { unsigned char _opaque[16]; };
struct _Tree_unchecked_const_iterator_t { unsigned char _opaque[16]; };
struct _Tree_val_t { unsigned char _opaque[16]; };
struct _func_bool_Ship_ptr_int_basic_string_t { unsigned char _opaque[16]; };
struct allocator_t { unsigned char _opaque[16]; };
struct bool____cdecl_____Ship__int_std__basic_string_t { unsigned char _opaque[16]; };
struct class_std__basic_string_t { unsigned char _opaque[16]; };
struct function_t { unsigned char _opaque[16]; };
struct map_t { unsigned char _opaque[16]; };
struct pair_t { unsigned char _opaque[16]; };
struct tuple_t { unsigned char _opaque[16]; };

template <class... A> any_value Read___x28_x29(A&&...);
template <class... A> any_value Write___x28_x29(A&&...);
template <class... A> any_value _Default_allocator_traits__construct(A&&...);
template <class... A> any_value _Destroy_range___x28_x29(A&&...);
template <class... A> any_value _Find_unchecked___x28_x29(A&&...);
template <class... A> any_value _Func_class___Reset(A&&...);
template <class... A> any_value _Func_class___Set(A&&...);
template <class... A> any_value _Func_class___Swap(A&&...);
template <class... A> any_value _Func_class__operator_x28_x29(A&&...);
template <class... A> any_value _Global_new___x28_x29(A&&...);
template <class... A> any_value _Move_unchecked___x28_x29(A&&...);
template <class... A> any_value _String_val___String_val(A&&...);
template <class... A> any_value _String_val___Xran(A&&...);
template <class... A> any_value _Traits_equal___x28_x29(A&&...);
template <class... A> any_value _Traits_find___x28_x29(A&&...);
template <class... A> any_value _Tree___Eqrange(A&&...);
template <class... A> any_value _Tree___Erase(A&&...);
template <class... A> any_value _Tree___Insert_hint(A&&...);
template <class... A> any_value _Tree___Insert_nohint(A&&...);
template <class... A> any_value _Tree__clear(A&&...);
template <class... A> any_value _Tree__count(A&&...);
template <class... A> any_value _Tree__erase(A&&...);
template <class... A> any_value _Tree_comp_alloc___Buyheadnode(A&&...);
template <class... A> any_value _Tree_comp_alloc___Buynode(A&&...);
template <class... A> any_value _Tree_unchecked_const_iterator__operator_x2b_x2b(A&&...);
template <class... A> any_value _Tree_val___Extract(A&&...);
template <class... A> any_value basic_string___Construct_lv_contents(A&&...);
template <class... A> any_value basic_string___Equal(A&&...);
template <class... A> any_value basic_string___Reallocate_grow_by(A&&...);
template <class... A> any_value basic_string___Tidy_init(A&&...);
template <class... A> any_value basic_string__begin(A&&...);
template <class... A> any_value basic_string__end(A&&...);
template <class... A> any_value basic_string__erase(A&&...);
template <class... A> any_value basic_string__find(A&&...);
template <class... A> any_value basic_string__operator_x3d(A&&...);
template <class... A> any_value basic_string__operator_x5b_x5d(A&&...);
template <class... A> any_value basic_string__push_back(A&&...);
template <class... A> any_value basic_string__substr(A&&...);
template <class... A> any_value function__function(A&&...);
template <class... A> any_value function__operator_x3d(A&&...);
template <class... A> any_value function__operator_x3d_x3c_x3e(A&&...);
template <class... A> any_value function__operator_bool(A&&...);
template <class... A> any_value function___x7efunction(A&&...);
template <class... A> any_value map___Try_emplace(A&&...);
template <class... A> any_value map__operator_x5b_x5d(A&&...);
template <class... A> any_value move___x28_x29(A&&...);
template <class... A> any_value pair___x7epair(A&&...);
template <class... A> any_value remove___x28_x29(A&&...);
template <class... A> any_value transform___x28_x29(A&&...);
template <class... A> any_value vector___Assign_range(A&&...);
template <class... A> any_value vector___Emplace_back_with_unused_capacity(A&&...);
template <class... A> any_value vector___Emplace_reallocate(A&&...);
template <class... A> any_value vector___Range_construct_or_tidy(A&&...);
template <class... A> any_value vector___Reallocate_exactly(A&&...);
template <class... A> any_value vector___Tidy(A&&...);
template <class... A> any_value vector___Unchecked_begin(A&&...);
template <class... A> any_value vector___Unchecked_end(A&&...);
template <class... A> any_value vector__clear(A&&...);
template <class... A> any_value vector__emplace_back(A&&...);
template <class... A> any_value vector__erase(A&&...);
template <class... A> any_value vector__insert(A&&...);
template <class... A> any_value vector__operator_x3d(A&&...);
template <class... A> any_value vector__operator_x5b_x5d(A&&...);
template <class... A> any_value vector__push_back(A&&...);
template <class... A> any_value vector__size(A&&...);
template <class... A> any_value vector__vector(A&&...);
template <class... A> any_value vector___x7evector(A&&...);

}}  // namespace ghidra::lib
