// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class HardwareOutput {
public:
    static HardwareOutput * getInstance();
    void shutdown();
    void findPorts();
    void initialisePort(int param_1);
    void addPort(char * param_2);
    static GameLogic * m_instance;  // data symbol used as HardwareOutput::m_instance
};
