// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class HardwareInterface {
public:
    ~HardwareInterface();
    void sendElementData(char param_1, int param_2);
    void sendLine(char * param_1, ...);
    void runSyncLogic(float param_1);
    void runActiveLogic(float param_1);
    void updateDataRequests(float param_1);
    void forceUpdateDataRequests();
    void runLogic(float param_1);
    static undefined4 vftable;  // data symbol used as HardwareInterface::vftable
};
