// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class InputConfiguration {
public:
    InputConfiguration();
    void setOption(ShipCommand param_1, KeyCode param_2);
    void populateInputConfig(ghidra::vector * param_1);
};
