// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class JunkManager {
public:
    Junk * getRandomJunkForSector(Sector * param_1);
    void generateJunkForSector(Sector * param_1, undefined4 param_3, undefined4 param_4);
};
