// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class LogSystem {
public:
    void runLogic(float param_1);
    void renderWarning();
    void addLogLine(LogPriority param_1, char * param_2, ...);
    void cleanupWarning();
    void setHistoryItem(int param_1);
    std::string * getLogAsStr();
};
