// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class MenuConfiguration {
public:
    static void configureMenus();
    static bool saveSlotIsSelected(void * param_1);
    static void updateWithSaveSlots(Menu * param_1);
    static void updateWithMultiplayerOptions(Menu * param_1);
    static void updateWithSinglePlayerScenarioCategories(Menu * param_1);
    static bool scenarioIsSelected(void * param_1);
};
