// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ModManager {
public:
    void initialise();
    Mod * getModInfo(undefined4 param_1, std::string * param_2);
    void getFolders(undefined4 param_1, ghidra::vector * param_2, char * param_3, int param_4, int param_5, int param_6, undefined8 param_7);
};
