// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class MultiplayerTabletManager {
public:
    void render(TabletScreenType param_1);
    void keyHit(KeyCode param_1);
    void renderStatus();
    void renderScenario();
    static undefined4 vftable;  // data symbol used as MultiplayerTabletManager::vftable
};
