// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class NameManager {
public:
    void loadNames();
    void generateFreighterName();
    void generatePirateName();
    void generatePoliceName();
    void loadLinesFromFile(undefined4 param_1, undefined4 * param_2, void * param_3);
    void generateBuyableName();
    void addRego(void * param_2);
    void generateGeneralRego();
    void getLocationForRego(undefined4 param_1, std::string * param_2, char * param_3);
    void generatePoliceRego();
    bool regoExists(char * param_2);
};
