// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class NetworkClient {
public:
    void initialise();
    bool validServer(undefined4 param_1, void * param_2);
    void connectToServer(char * param_1, int param_2);
    void disconnectFromServer();
    void runLogic(float param_1);
    void addChatLogItem(void * param_2);
};
