// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class NetworkServer {
public:
    bool shipHasConnectedClient(char * param_2);
    void sendSound(undefined4 param_2, undefined4 param_3, char * param_4);
    void sendLog(LogLine * param_2, char * param_3);
    void sendShipDetailsToClient(int param_1, int param_3, undefined4 param_4, int param_5, void * param_6);
    void recheckShipsToSync();
    ShipSyncNode * startSyncingShip(std::string * param_2);
    void addOrRemoveComponent(char * param_2);
    void removeWeapon(int param_2, char * param_3);
    void stopSyncingModule(int param_2, char * param_3);
    void startSyncingCargoState(ShipSyncNode * param_1);
    void startSyncingWaypoints(ShipSyncNode * param_1);
    void startSyncingModuleState(ShipSyncNode * param_1, ShipModule * param_2);
    void startSyncingHullState(ShipSyncNode * param_1, int param_2);
    void startSyncingServerInfoState();
    void startSyncingWeapon(ShipSyncNode * param_1, int param_2, Weapon * param_3);
    void startSyncingSensorDataState(ShipSyncNode * param_1, SensorData * param_2);
    void runLogic(float param_1);
    void runSyncCheck(float param_1, bool param_2);
    ClientInfo * addClientInfo(int param_1, int param_3, undefined4 param_4, undefined4 param_5, std::string * param_6);
    void removeClientInfo(RakNetGUID param_1);
    void parseRemoteCommand(undefined4 param_1_00, undefined1 * param_1, void * param_3);
    void forceSessionToBegin();
};
