// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class NetworkData {
public:
    void sendSetClientInfo(undefined4 param_1, void * param_2);
    void sendShipCommand(int param_1, double param_2, double param_3, double param_4);
    void sendAddShip(undefined4 param_1_00, undefined4 param_1, undefined4 param_3, undefined4 param_4, undefined4 param_5, void * param_6);
    void sendSync(RakNetGUID param_1, SyncNode * param_2);
    void sendSetModule(undefined4 param_1_00, int param_1, int param_3_00, undefined4 param_4, undefined4 param_5, undefined4 param_2, undefined4 param_3, undefined4 * param_8);
    void sendSetModuleBasicSettings(RakNetGUID param_1, int param_2, int param_3, ShipModule * param_4);
    void sendSetModuleDetails(RakNetGUID param_1, int param_2, int param_3, ShipModule * param_4);
    void sendSetComponent(RakNetGUID param_1, ShipModule * param_2, int param_3);
    void sendServerInfoBasic(undefined4 param_1_00, undefined4 param_1, undefined4 param_3, undefined4 param_4, undefined4 param_5, void * param_6);
    void sendServerInfoAdvanced(undefined4 param_1_00, undefined4 param_1, undefined4 param_3, undefined4 param_4, undefined4 param_5, void * param_6);
    void sendSetAddon(RakNetGUID param_1, ShipModule * param_2, int param_3);
    void sendUpdateSensorDataBasic(RakNetGUID param_1, SensorData * param_2);
    void sendUpdateSensorDataAdvanced(RakNetGUID param_1, SensorData * param_2);
    void sendUpdateSensorWaveform(RakNetGUID param_1, SensorData * param_2);
    void sendLog(RakNetGUID param_1, LogLine * param_2);
    void sendChatLineToServer(undefined4 param_1, undefined4 * param_2);
    void sendPresentationCommand(RakNetGUID param_1, int param_2, float param_3, float param_4);
    void unpackSetScenario(Packet_SetScenario * param_1);
    void sendChatLineFromServer(undefined4 param_1, void * param_2);
    void sendMessageToClient(undefined4 param_1_00, undefined4 * param_1, undefined4 * param_3);
    void unpackSetScenarioState(Packet_SetScenarioState * param_1);
    void unpackSetCargoComponents(Packet_CargoState * param_1);
    void unpackSetModuleBasicSettings(Packet_SetModuleBasicSettings * param_1);
    void unpackSetModuleDetails(Packet_SetModuleDetails * param_1);
    void unpackSetComponent(Packet_SetComponent * param_1);
    void unpackSetAddon(Packet_SetAddon * param_1);
    void unpackUpdateSensorDataAdvanced(Packet_UpdateSensorDataAdvanced * param_1);
    void unpackUpdateSensorWaveform(Packet_UpdateSensorWaveform * param_1);
    void unpackDataRequest(RakNetGUID param_1, Packet_DataRequest * param_2);
    void unpackServerAdmin(RakNetGUID param_1, Packet_ServerAdmin * param_2);
    void unpackSetGoLiveState(RakNetGUID param_1, Packet_SetGoLiveState * param_2);
    void unpackSetClientInfo(RakNetGUID param_1, Packet_SetClientInfo * param_2);
    void unpackReceiveMessageFromServer(Packet_SendMessage * param_1);
    void unpackReceiveMessageFromClient(RakNetGUID param_1, Packet_SendMessage * param_2);
    void unpackWeaponCommand(Packet_WeaponCommand * param_1);
    void unpackSetHullState(Packet_HullState * param_1);
    void unpackServerInfoAdvanced(Packet_ServerInfoAdvanced * param_1);
    void unpackAddShip(RakNetGUID param_1, Packet_AddShip * param_2);
    void unpackRunCommand(RakNetGUID param_1, Packet_RunCommand * param_2);
    void unpackSyncNumerical(Packet_SyncValueNumerical * param_1);
};
