// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class NPCShipManager {
public:
    void generateNewFreighter(int param_1);
    void setFreighterDestination(Ship * param_1, SpaceStation * param_2);
    void generateNewPoliceVessel(int param_1);
    Ship * generateNewMilitaryVessel(int param_1);
    Ship * generateNewPirateVessel(int param_1);
    Ship * generateVesselFromBounty(Bounty * param_1);
    SpaceStation * getRandomSpaceStation(int param_1, Ship * param_2);
    void removeAllShipsInSector(int param_1);
    void reset();
    void runSectorLogic(int param_1);
    void runPoliceVesselLogic(Ship * param_1);
};
