// Forward declarations and namespace imports shared by every reconstructed header.
#pragma once
#include "ois/ghidra_compat.h"
#include "cocos2d.h"
#include <string>

using cocos2d::AABB;
using cocos2d::ActionInterval;
using cocos2d::AmbientLight;
using cocos2d::Animate3D;
using cocos2d::Animation;
using cocos2d::Animation3D;
using cocos2d::BaseLight;
using cocos2d::CallFunc;
using cocos2d::Camera;
using cocos2d::Color3B;
using cocos2d::Component;
using cocos2d::Configuration;
using cocos2d::Console;


using cocos2d::Data;
using cocos2d::DelayTime;

using cocos2d::DirectionLight;
using cocos2d::Director;


using cocos2d::Event;
using cocos2d::EventDispatcher;
using cocos2d::EventListener;
using cocos2d::EventListenerKeyboard;
using cocos2d::EventListenerMouse;
using cocos2d::EventMouse;
using cocos2d::FadeIn;
using cocos2d::FadeOut;
using cocos2d::FileUtils;
using cocos2d::FiniteTimeAction;
using cocos2d::Follow;

using cocos2d::GLView;
using cocos2d::GLViewImpl;
using cocos2d::Hide;
using cocos2d::Image;
using cocos2d::Label;
using cocos2d::Layer;
using cocos2d::Mesh;

using cocos2d::Node;
using cocos2d::PointLight;
using cocos2d::Quaternion;
using cocos2d::Ray;
using cocos2d::Rect;
using cocos2d::Ref;
using cocos2d::RenderTexture;
using cocos2d::RepeatForever;
using cocos2d::RotateTo;

using cocos2d::Scene;
using cocos2d::Sequence;
using cocos2d::Show;
using cocos2d::Size;

using cocos2d::Spawn;
using cocos2d::Speed;
using cocos2d::SpotLight;
using cocos2d::Sprite;
using cocos2d::Sprite3D;
using cocos2d::SpriteFrameCache;



using cocos2d::Texture2D;



using cocos2d::Value;
using cocos2d::Vec2;
using cocos2d::Vec3;
using KeyCode = cocos2d::EventKeyboard::KeyCode;

class AIAttack;
class AIDesire;
class AIFollow;
class AIHunt;
class AIPatrol;
class AIPiracy;
class AIScan;
class AIScavenge;
class AITravel;
class Analytics;
class AppDelegate;
class Article;
class AuthorityManager;
class BankAccount;
class BankEngine;
class BankTransaction;
class Beacon;
class Bounty;
class BountyClass;
class BountyManager;
class ButtonElement;
class CSteamAPIContext;
class CameraPos;
class CargoHold;
class CargoManager;
class CargoPod;
class CargoState;
class CharacterAnimationManager;
class CharacterLocation;
class ClientInfo;
class Command;
class CommsCommand;
class CommsData;
class CommsManager;
class ComponentClass;
class ComponentInterface;
class ComponentInterfaceInstance;
class ComputerSystem;
class ComputerSystemInterface;
class ConsoleDamage;
class Contract;
class ContractCargoInstance;
class ContractClass;
class ContractManager;
class Conversation;
class ConversationElement;
class ConversationManager;
class ConversationOption;
class CounterMeasure;
class DataLoader;
class DataRequest;
class DatagramHeaderFormat;
class DateTime;
class Destination;
class Dice;
class DockProcessElement;
class DummyObject;
class Email;
class EmailDraft;
class EmailInstance;
class EmailManager;
class EngineeringSlotLocation;
class ExtraSpawned;
class Faction;
class FictionData;
class FlagManager;
class FlagTimeToSet;
class FogInstance;
class Game;
class GameCharacter;
class GameData;
class GameLogic;
class GameObject;
class HackEngine;
class HardwareInterface;
class HardwareOutput;
class IllegalGood;
class Infopedia;
class InputCommand;
class InputConfiguration;
class InputOption;
class Interface;
class JumpGateRoute;
class JunkManager;
class Key;
class LineData;
class ListData;
class LiveMessage;
class LocationManager;
class LogLine;
class LogSystem;
class Menu;
class MenuConfiguration;
class MenuItem;
class MenuManager;
class Message;
class MetaGameAction;
class ModManager;
class ModuleRenderData;
class MouseCursor;
class MultiplayerTabletManager;
class NM_MapObject;
class NPCShipManager;
class NameManager;
class NavPoint;
class NetworkClient;
class NetworkData;
class NetworkServer;
class NotesManager;
class OISConfiguration;
class OSInterface;
class OiSStackWalker;
class Packet_SyncValueString;
class ParticleEngine;
class Passenger;
class PassengerInstance;
class PassengerManager;
class PathContext;
class Pather;
class PlayerGuidedToPort;
class PossibleLocation;
class PowerManager;
class PresentationData;
class PresentationInterface;
class PrivateComm;
class PrivateCommElement;
class PrivateCommOption;
class PrivateCommsManager;
class Requirement;
class Room;
class RoomCharacter;
class RoomEditor;
class RoomObject;
class SaveHandler;
class SaveMetaData;
class Scenario;
class ScreenData;
class ScreenElement;
class ScreenInterface;
class Screen_ContractTerminal;
class Screen_Custom;
class Screen_PC;
class Screen_RTComms;
class Screen_Renderer;
class Screen_Terminal;
class Screen_TradeTerminal;
class Screen_UpgradeTerminal;
class Screen_WeaponTerminal;
class Sector;
class SectorEditor;
class Selectable;
class SensorData;
class SensorDataStates;
class SensorManager;
class ServerInfoState;
class ServerMenu;
class ServerMenuItem;
class ServerPresentationInterface;
class ServerShipState;
class ServerUserState;
class Ship;
class ShipBehaviour;
class ShipChatter;
class ShipClass;
class ShipComponent;
class ShipData;
class ShipInstance;
class ShipInterface;
class ShipMechanics;
class ShipModule;
class ShipModuleClass;
class ShipNumericalData;
class ShipSale;
class ShipSaleSet;
class ShipSyncNode;
class ShipTextData;
class Shop;
class SoundEngine;
class SoundLet;
class SpaceStation;
class StackWalker;
class StackWalkerInternal;
class Stats;
class StellarObject;
class Structure;
class SyncNode;
class SyntheticObject;
class SyntheticObjectCargoInstance;
class SystemManager;
class TabletInterface;
class TabletManager;
class TabletOmega;
class TerminalEngine;
class TextEngine;
class TextField;
class TopBar;
class TradeEngine;
class TradeItemInstance;
class TradeLocation;
class UIAnimatedSprite;
class UIRectangle;
class UIText;
class UI_AdShell;
class UI_BDBar;
class UI_Border;
class UI_Button;
class UI_Checkbox;
class UI_ComponentStorage;
class UI_DMenu;
class UI_Data;
class UI_DockVisualisation;
class UI_EngPanel;
class UI_HelmControl;
class UI_IconTray;
class UI_Image;
class UI_IntroSequence;
class UI_Menu;
class UI_ModuleRepair;
class UI_Multimeter;
class UI_NavMap;
class UI_NewsTicker;
class UI_PowerDetailScreen;
class UI_PowerScreen;
class UI_SelectTray;
class UI_SelectedObjectSummary;
class UI_Selector;
class UI_SensorDisplay;
class UI_SensorSelect;
class UI_SensorWaveform;
class UI_Sheet;
class UI_ShipHullState;
class UI_Slider;
class UI_StatusBar;
class UI_SystemBar;
class UI_Text;
class UI_TextBox;
class UI_TextField;
class UI_WeaponTubes;
class UpgradeCommand;
class V10;
class V11;
class V12;
class V6;
class V7;
class V8;
class V9;
class WSAStartupSingleton;
class WaveformData;
class WaypointState;
class Weapon;
class WeaponState;
class Widget;
class Zone;
class switchD_0041b083;
class type_info;

// Types referenced by Ghidra prototypes that are neither game classes nor cocos2d types.
// Forward-declared as structs; define them properly when their layout is known.
struct Alignment { unsigned char _unknown_layout; };
struct AnimationFrames { unsigned char _unknown_layout; };
struct AnimationSet { unsigned char _unknown_layout; };
struct BitStream { unsigned char _unknown_layout; };
struct CallstackEntry { unsigned char _unknown_layout; };
struct CallstackEntryType { unsigned char _unknown_layout; };
struct CaptainExperience { unsigned char _unknown_layout; };
struct CaptainStyle { unsigned char _unknown_layout; };
struct CharacterEyeState { unsigned char _unknown_layout; };
struct CharacterMouthState { unsigned char _unknown_layout; };
struct CharacterPosition { unsigned char _unknown_layout; };
struct ComparisonCheckType { unsigned char _unknown_layout; };
struct ComponentCategory { unsigned char _unknown_layout; };
struct CraftPurpose { unsigned char _unknown_layout; };

struct DamageAngle { unsigned char _unknown_layout; };
struct DamageType { unsigned char _unknown_layout; };
struct DifficultyMode { unsigned char _unknown_layout; };
struct DockingRequest { unsigned char _unknown_layout; };
struct EmailDraftSet { unsigned char _unknown_layout; };

struct FollowMode { unsigned char _unknown_layout; };
struct Good { unsigned char _unknown_layout; };
struct GoodContainmentOption { unsigned char _unknown_layout; };

struct HazardCategory { unsigned char _unknown_layout; };
struct HullDamageState { unsigned char _unknown_layout; };
struct HullLocation { unsigned char _unknown_layout; };
struct IMAGEHLP_MODULE64_V3 { unsigned char _unknown_layout; };
struct Junk { unsigned char _unknown_layout; };
struct LPCRITICAL_SECTION { unsigned char _unknown_layout; };
struct LPVOID { unsigned char _unknown_layout; };
struct List { unsigned char _unknown_layout; };
struct LogPriority { unsigned char _unknown_layout; };
struct MeshCategory { unsigned char _unknown_layout; };
struct Mod { unsigned char _unknown_layout; };
struct ModuleConfiguration { unsigned char _unknown_layout; };
struct ModuleSaleInstance { unsigned char _unknown_layout; };
struct ModuleSlotType { unsigned char _unknown_layout; };
struct ModuleType { unsigned char _unknown_layout; };
struct NavPointType { unsigned char _unknown_layout; };
struct OrbitState { unsigned char _unknown_layout; };
struct OverlaySegment { unsigned char _unknown_layout; };
struct Packet_AddShip { unsigned char _unknown_layout; };
struct Packet_CargoState { unsigned char _unknown_layout; };
struct Packet_DataRequest { unsigned char _unknown_layout; };
struct Packet_HullState { unsigned char _unknown_layout; };
struct Packet_RunCommand { unsigned char _unknown_layout; };
struct Packet_SendMessage { unsigned char _unknown_layout; };
struct Packet_ServerAdmin { unsigned char _unknown_layout; };
struct Packet_ServerInfoAdvanced { unsigned char _unknown_layout; };
struct Packet_SetAddon { unsigned char _unknown_layout; };
struct Packet_SetClientInfo { unsigned char _unknown_layout; };
struct Packet_SetComponent { unsigned char _unknown_layout; };
struct Packet_SetGoLiveState { unsigned char _unknown_layout; };
struct Packet_SetModuleBasicSettings { unsigned char _unknown_layout; };
struct Packet_SetModuleDetails { unsigned char _unknown_layout; };
struct Packet_SetScenario { unsigned char _unknown_layout; };
struct Packet_SetScenarioState { unsigned char _unknown_layout; };
struct Packet_SyncValueNumerical { unsigned char _unknown_layout; };
struct Packet_UpdateSensorDataAdvanced { unsigned char _unknown_layout; };
struct Packet_UpdateSensorWaveform { unsigned char _unknown_layout; };
struct Packet_WeaponCommand { unsigned char _unknown_layout; };
struct PathNode { unsigned char _unknown_layout; };
struct Quadrant { unsigned char _unknown_layout; };
struct RakNet { unsigned char _unknown_layout; };
struct RakNetGUID { unsigned char _unknown_layout; };
struct Resolution { unsigned char _unknown_layout; };
struct ScenarioCategory { unsigned char _unknown_layout; };
struct ScenarioType { unsigned char _unknown_layout; };
struct ScreenLayout { unsigned char _unknown_layout; };
struct ScreenType { unsigned char _unknown_layout; };
struct SharedString { unsigned char _unknown_layout; };
struct ShipCommand { unsigned char _unknown_layout; };
struct ShipConfiguration { unsigned char _unknown_layout; };
struct ShipDataCheckType { unsigned char _unknown_layout; };
struct ShipDataInputType { unsigned char _unknown_layout; };
struct ShipDataType { unsigned char _unknown_layout; };
struct ShipLook { unsigned char _unknown_layout; };
struct ShipTextDataType { unsigned char _unknown_layout; };
struct SimpleMutex { unsigned char _unknown_layout; };
struct Sound { unsigned char _unknown_layout; };
struct SoundSpace { unsigned char _unknown_layout; };
struct StateModifier { unsigned char _unknown_layout; };
struct StellarCategory { unsigned char _unknown_layout; };
struct SyncVarType { unsigned char _unknown_layout; };
struct SyntheticObjectType { unsigned char _unknown_layout; };
struct System { unsigned char _unknown_layout; };
struct SystemAddress { unsigned char _unknown_layout; };
struct TabletScreenType { unsigned char _unknown_layout; };
struct TabletTab { unsigned char _unknown_layout; };
struct ThrowInfo { unsigned char _unknown_layout; };
struct TravelState { unsigned char _unknown_layout; };
struct TypeDescriptor { unsigned char _unknown_layout; };
struct UserStatsReceived_t { unsigned char _unknown_layout; };
struct UserStatsStored_t { unsigned char _unknown_layout; };
struct VesselType { unsigned char _unknown_layout; };
struct Waypoint { unsigned char _unknown_layout; };
struct WeaponClass { unsigned char _unknown_layout; };
struct _ { unsigned char _unknown_layout; };
struct _CONTEXT { unsigned char _unknown_layout; };
struct _EXCEPTION_POINTERS { unsigned char _unknown_layout; };
struct _TexParams { unsigned char _unknown_layout; };
struct __type_info_node { unsigned char _unknown_layout; };
struct __uint64 { unsigned char _unknown_layout; };
struct _const_ { unsigned char _unknown_layout; };
struct _exception { unsigned char _unknown_layout; };
struct _func_4879 { unsigned char _unknown_layout; };
struct _func_int_void_ptr___uint64_void_ptr_ulong_ulong_ptr_void_ptr { unsigned char _unknown_layout; };
struct _func_void_uchar_ptr { unsigned char _unknown_layout; };
struct _func_void_void_ptr { unsigned char _unknown_layout; };
struct _iobuf { unsigned char _unknown_layout; };
struct _locale_t { unsigned char _unknown_layout; };
struct _onexit_t { unsigned char _unknown_layout; };
struct basic_string { unsigned char _unknown_layout; };
struct class_std { unsigned char _unknown_layout; };
struct errno_t { unsigned char _unknown_layout; };
struct int_const_ { unsigned char _unknown_layout; };
struct map { unsigned char _unknown_layout; };
struct nothrow_t { unsigned char _unknown_layout; };
struct pointer { unsigned char _unknown_layout; };
struct struct_std { unsigned char _unknown_layout; };
