// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class OISConfiguration {
public:
    static void configure();
    static void setOptimalResolution();
    static void setRes();
    static void dumpCommands();
    static void load();
    static void save();
    static bool alernateTextRendering;  // data symbol used as OISConfiguration::alernateTextRendering
    static bool alwaysShowMenu;  // data symbol used as OISConfiguration::alwaysShowMenu
    static undefined4 currentResolutionStr;  // data symbol used as OISConfiguration::currentResolutionStr
    static int difficulty;  // data symbol used as OISConfiguration::difficulty
    static bool displayChanged;  // data symbol used as OISConfiguration::displayChanged
    static bool displayFullscreen;  // data symbol used as OISConfiguration::displayFullscreen
    static int displayHeight;  // data symbol used as OISConfiguration::displayHeight
    static int displayWidth;  // data symbol used as OISConfiguration::displayWidth
    static bool hardwareCRLF;  // data symbol used as OISConfiguration::hardwareCRLF
    static bool hardwareEnabled;  // data symbol used as OISConfiguration::hardwareEnabled
    static bool ignoreCom12;  // data symbol used as OISConfiguration::ignoreCom12
    static bool keySounds;  // data symbol used as OISConfiguration::keySounds
    static undefined4 lastVersionPlayed;  // data symbol used as OISConfiguration::lastVersionPlayed
    static bool multiDebug;  // data symbol used as OISConfiguration::multiDebug
    static bool noCameraMotion;  // data symbol used as OISConfiguration::noCameraMotion
    static undefined4 rconPassword;  // data symbol used as OISConfiguration::rconPassword
    static undefined4 scenario;  // data symbol used as OISConfiguration::scenario
    static bool scrollWheel;  // data symbol used as OISConfiguration::scrollWheel
    static undefined4 serverIP;  // data symbol used as OISConfiguration::serverIP
    static undefined4 serverPort;  // data symbol used as OISConfiguration::serverPort
    static bool skipIntro;  // data symbol used as OISConfiguration::skipIntro
    static bool tooltips;  // data symbol used as OISConfiguration::tooltips
    static undefined4 username;  // data symbol used as OISConfiguration::username
};
