// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class OSInterface {
public:
    static void initialiseOSFunctions();
    static void getSoundLocationForAsset(char * param_1);
    static void getLocationForAsset(char * param_1);
    static uchar * getDataFromFile(std::string * param_1);
    static void getBaseDirectory();
    static void getModDirectory();
    static void getSaveDirectory();
    static void listFiles(void * param_1);
    static void getCorrectedWorldPosition();
    static float cameraScale;  // data symbol used as OSInterface::cameraScale
    static Size designSize;  // data symbol used as OSInterface::designSize
    static float renderScale;  // data symbol used as OSInterface::renderScale
    static Size screenSize;  // data symbol used as OSInterface::screenSize
};
