// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Pather {
public:
    Pather();
    void runLogic(float param_1);
    void resetSector();
    PathNode * calculatePath(PathContext * param_1, uint param_2, bool param_3);
};
