// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class PresentationData {
public:
    static bool checkRoomObjectState(int param_1, int param_2, void * param_3);
    static bool checkHasSelectedDirection(int param_1, undefined4 param_2, void * param_3);
    static bool checkNavMapLockedToShip(int param_1, int param_2, void * param_3);
    static bool doMoveMapLeft(Ship * param_1, double param_2, double param_3, double param_4);
    static bool doMoveMapRight(Ship * param_1, double param_2, double param_3, double param_4);
    static bool doMoveMapUp(Ship * param_1, double param_2, double param_3, double param_4);
    static bool doMoveMapDown(Ship * param_1, double param_2, double param_3, double param_4);
    static bool doMapZoomIn(Ship * param_1, double param_2, double param_3, double param_4);
    static bool doMapZoomOut(Ship * param_1, double param_2, double param_3, double param_4);
    static bool doRecenterMapOnShip(Ship * param_1, double param_2, double param_3, double param_4);
    static void moveMap(float param_1, float param_2);
    static bool isLocalCommand(int param_1);
    static void getShipCommandFunction(int param_1);
    static bool m_lockToShip;  // data symbol used as PresentationData::m_lockToShip
    static Vec2 m_mapCenterPoint;  // data symbol used as PresentationData::m_mapCenterPoint
    static int m_mapZoomLevel;  // data symbol used as PresentationData::m_mapZoomLevel
    static double m_selectedHeading;  // data symbol used as PresentationData::m_selectedHeading
    static undefined4 m_tabletFooter;  // data symbol used as PresentationData::m_tabletFooter
    static undefined4 m_tabletHeader;  // data symbol used as PresentationData::m_tabletHeader
    static bool m_tabletLockToShip;  // data symbol used as PresentationData::m_tabletLockToShip
    static Vec2 m_tabletMapCenterPoint;  // data symbol used as PresentationData::m_tabletMapCenterPoint
    static int m_tabletMapSelectedSector;  // data symbol used as PresentationData::m_tabletMapSelectedSector
    static int m_tabletMapZoomLevel;  // data symbol used as PresentationData::m_tabletMapZoomLevel
    static undefined4 m_tabletScreen;  // data symbol used as PresentationData::m_tabletScreen
    static bool m_talkMode;  // data symbol used as PresentationData::m_talkMode
    static undefined4 m_talkingTo;  // data symbol used as PresentationData::m_talkingTo
};
