// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class PresentationInterface {
public:
    PresentationInterface();
    ~PresentationInterface();
    void configureSoundForShip();
    void runFullFadeLogic(float param_1);
    void update(float param_1);
    void boardDockedVessel(Ship * param_1);
    void leaveDockedVessel(Ship * param_1);
    void boardMooredStructure(Ship * param_1);
    void setAirlockStates(Ship * param_1, bool param_2);
    void changeRoom(int param_1);
    void cleanupCurrentRoom();
    void showRoom(int param_1);
    void onKeyPressed(KeyCode param_1, Event * param_2);
    void switchToConsoleID(int param_1);
    void quitToMenu();
    void onKeyReleased(KeyCode param_1, Event * param_2);
    void resetSpaceStationScreens();
    bool tabletActive();
    void showTablet(int param_1);
    void setTabletScreen(int param_1);
    void hideTablet(bool param_1);
    void hideTabletInstantly();
    void switchToPComms();
    void setMessageFocus(RoomObject * param_1);
    void switchToHelmControlAfterUndocking();
    void moveToRTCommsStation();
    char keycodeToChar(KeyCode param_1, bool param_2, bool param_3);
    void eventLocationToLocation(EventMouse * param_1);
    void onMouseMove(Event * param_1);
    void onMouseUp(Event * param_1);
    void onMouseDown(Event * param_1);
    void onMouseScroll(Event * param_1);
    static bool doToggleRoomObject(Ship * param_1, double param_2, double param_3, double param_4);
    void moveToCameraPos(int param_1, float param_2);
    std::string * getConsoleToDamage();
    void addShake(char * param_2);
    void switchJumpMode(bool param_1);
    void switchEmconMode(bool param_1);
    void runCameraLogic(float param_1);
    void runLightLogic(float param_1);
    void giveEmoteToCharacter(char * param_2);
    bool talkToCharacter(undefined4 param_2, char * param_3);
    void flicker(int param_1);
    void exitGame();
    bool hasForcedConversationPending();
};
