// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class PrivateComm {
public:
    void reset();
    std::string * describeSource();
    void render(std::string * param_1, std::string * param_2);
    void changeElement(int param_1);
    int getNextValidElement();
    int getValidatedElement();
    int selectElement();
    ~PrivateComm();
};
