// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class PrivateCommOption {
public:
    PrivateCommOption(undefined4 param_1, undefined4 param_2, void * param_4);
    void setActionFunction(void * param_2);
    void setExistFunction(void * param_2);
    ~PrivateCommOption();
    PrivateCommOption(PrivateCommOption * param_1);
};
