// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class PrivateCommsManager {
public:
    void reset();
    bool keyPressed(KeyCode param_1);
    int firstValidConversationOption();
    void activateCurrentConversationElement();
    void switchTo(int param_1);
    void cancelCurrentHail();
    void goBackToList();
    bool runSecureSpaceStationBBSLogic(float param_1);
    bool runSecureShipHailLogic(float param_1);
    void runLogic(float param_1);
    void renderConversation(float param_1);
    void renderComm(float param_1);
    void addGarbageChar(char param_1);
    void render(bool param_1, bool param_2);
    void renderList();
    void renderCurrentConversationElement();
    bool hasValidOptionInCurrentElement();
    bool regenerateList();
    void generateSpaceStationComms(PrivateComm * param_1, SpaceStation * param_2);
    void generateShipComms(Ship * param_1);
};
