// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class RoomObject {
public:
    bool isCharacter();
    RoomObject();
    void cleanupObject();
    bool spawnPointCheck();
    void updateRotationForCamera();
    void render(Node * param_1);
    void setMesh(bool param_2, Texture2D * param_3, char * param_4);
    void setMesh(bool param_2, void * param_3);
    void runAnimation();
    void animationDoneCallback();
    void switchToScreen(int param_1);
    void recheckValidScreens();
    void nextValidScreen();
    void renderAllScreens();
    void generateScreen(int param_1);
    bool isInteractAble();
    void resetScreen(bool param_1);
    void resetTopBars(bool param_1);
    void resetTopBar(bool param_1);
    std::string * describe();
    void resetPosition();
    void movePosition();
    void updatePosition();
    void recheckTabs();
    void runLogic(float param_1);
    void clearTextureElements();
    void addTextureElement(undefined4 param_2, undefined4 * param_3);
    Sprite * getTextureElement(char * param_2);
    void unsetCharacter();
    void setCharacter(int param_2, void * param_3);
};
