// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class RoomCharacter {
public:
    RoomCharacter(void * param_2);
    void renderHeadOverlays(RoomObject * param_1);
    void renderOverlay(RoomObject * param_1, int param_2);
    void renderCharacterOverlays(RoomObject * param_1);
    void renderCharacter(RoomObject * param_1);
    void setTextures(RoomObject * param_1);
};
