// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Room {
public:
    bool recheckCharacterRenders();
    void render(float param_1, Node * param_2);
    void cleanupRoom();
    RoomObject * newObject();
    void runLogic(float param_1);
    ScreenInterface * getConsoleInterface(int param_1);
    Screen_Renderer * getConsole(int param_1);
    RoomObject * getObjectForScreenID(int param_1);
    RoomObject * getObject(int param_1);
    RoomObject * getObjectClickedOn(float param_2, float param_3);
    std::string * getObjectTooltipText(undefined4 param_1, std::string * param_2, float param_3, float param_4);
};
