// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class SaveHandler {
public:
    void loadLocalStats();
    void saveLocalStats();
    bool saveExists(int param_1);
    SaveMetaData * unpackMetaData(_iobuf * param_1);
    void packMetaData(_iobuf * param_1);
    SaveMetaData * metadataForSave(int param_1);
    void loadGame();
    void saveGame();
    static void writeLengthString(undefined4 * param_1);
    static void readLengthString(_iobuf * param_1);
    void saveGameV12(_iobuf * param_1);
    void loadGameV12(_iobuf * param_1);
    void loadGameV6(_iobuf * param_1);
    void loadGameV7(_iobuf * param_1);
    void loadGameV8(_iobuf * param_1);
    void loadGameV9(_iobuf * param_1);
    void loadGameV10(_iobuf * param_1);
    void loadGameV11(_iobuf * param_1);
};
