// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ScreenElement {
public:
    bool keyUp(KeyCode param_1);
    void mouseDown();
    bool canDrag();
    int getDragID();
    std::string * getDragLook(undefined4 param_1, std::string * param_2);
    int getDragValue();
    void dragOnto();
    ScreenElement(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~ScreenElement();
    void setActive(bool param_1);
    bool containsPoint();
    static undefined4 vftable;  // data symbol used as ScreenElement::vftable
};
