// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Screen_Custom {
public:
    void cleanup();
    void configure();
    void configureElements();
    void render();
    ScreenElement * renderPercentileBar(Widget * param_1);
    ScreenElement * renderBDBar(Widget * param_1);
    ScreenElement * renderButton(Widget * param_1, bool param_2);
    ScreenElement * renderEngPanel(Widget * param_1);
    ScreenElement * renderComponentStorage(Widget * param_1);
    ScreenElement * renderWeaponTubes(Widget * param_1);
    ScreenElement * renderImage(Widget * param_1);
    ScreenElement * renderIntroSequence(Widget * param_1);
    ScreenElement * renderAdShell(Widget * param_1);
    ScreenElement * renderNewsTicker(Widget * param_1);
    ScreenElement * renderShipHullState(Widget * param_1);
    ScreenElement * renderSensorWaveform(Widget * param_1);
    ScreenElement * renderSensorDisplay(Widget * param_1);
    ScreenElement * renderSelectedObjectSummary(Widget * param_1);
    ScreenElement * renderText(Widget * param_1);
    ScreenElement * renderHelmControl(Widget * param_1);
    ScreenElement * renderSlider(Widget * param_1);
    ScreenElement * renderTextBox(Widget * param_1);
    ScreenElement * renderCheckbox(Widget * param_1);
    ScreenElement * renderSystemBar(Widget * param_1);
    ScreenElement * renderSelector(Widget * param_1);
    ScreenElement * renderSelectTray(Widget * param_1);
    void clickOnObject(int param_1);
    void updateExistence(Widget * param_1, int param_2);
    void update(float param_1);
    bool onKeyPressed(KeyCode param_1, Event * param_2);
    bool onKeyReleased(KeyCode param_1, Event * param_2);
    void cancelAllKeys();
};
