// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Screen_ContractTerminal {
public:
    void configure();
    void cmd_Cargo(char param_1);
    bool onKeyReleased(KeyCode param_1, Event * param_2);
    void executeCommand(char * param_2);
    void renderWelcomeMessage();
    void updateScreenCall();
    void renderBottomLine();
    void showCommandList();
    void reset();
    void cmd_List(char param_1);
    void cmd_Drop(char param_1);
    void cmd_Faction(char param_1, std::string * param_3, int param_4);
    void cmd_License(char param_1, int param_3, int param_4);
    void cmd_Take(MetaGameAction * param_1, char * param_3, int param_4);
    void cmd_Current(char param_1);
    void cmd_Info(char param_1, char * param_3, int param_4);
};
