// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Screen_UpgradeTerminal {
public:
    void cleanup();
    void configure();
    void executeCommand(char * param_2);
    void renderWelcomeMessage();
    void updateScreenCall();
    void renderBottomLine();
    void showCommandList();
    void reset();
    void describeModule(ModuleSaleInstance * param_1);
    void cmd_List(char param_1, int param_3, int param_4);
    void cmd_Repair(ShipMechanics * param_1, ShipMechanics * param_3, int param_4);
    void cmd_Info(char param_1, int param_3, int param_4);
    void cmd_Pods(char param_1, int param_3, int param_4);
    void cmd_Buy(char param_1, undefined4 * param_3, int param_4);
    void cmd_Sell(char param_1, int param_3, int param_4);
    void cmd_Confirm(char param_1);
    void cmd_Cancel(char param_1);
    void cmd_Components(char param_1);
    void cmd_Modules(char param_1);
};
