// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Screen_TradeTerminal {
public:
    void update(float param_1);
    void configure();
    void executeCommand(char * param_2);
    void renderWelcomeMessage();
    void updateScreenCall();
    void renderBottomLine();
    void cmd_List(char param_1, int param_3, int param_4);
    void cmd_Info(char param_1, std::string * param_3, int param_4);
    void cmd_Buy(char param_1, char * param_3, int param_4);
    void cmd_Confirm();
    void cmd_Cancel();
    void cmd_Weapons(char param_1, int param_3, int param_4);
    void cmd_Sell(char param_1, char * param_3, int param_4);
    void cmd_Cargo(char param_1);
    void cmd_Passengers(char param_1);
    void cmd_Take(char param_1, char * param_3, int param_4);
    void showCommandList();
    void reset();
};
