// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Screen_Terminal {
public:
    void configure();
    bool onKeyReleased(KeyCode param_1, Event * param_2);
    void executeCommand(char * param_2);
    void updateScreenCall();
    void cmd_Status(char param_1);
    void cmd_Power(char param_1, int param_3, int param_4);
    void cmd_Inv(char param_1);
    void cmd_Modules(char param_1);
    void cmd_Module(char param_1, char * param_3, int param_4);
    void showCommandList();
    void cmd_Rotate(char param_1, char * param_3, int param_4);
    void cmd_Burn(char param_1, int param_3, int param_4);
};
