// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ScreenInterface {
public:
    ScreenInterface(RoomObject * param_1, ScreenType param_2, bool param_3, Sprite3D * param_4, int param_5, int param_6, ScreenLayout * param_7);
    ~ScreenInterface();
    void setToolTip(std::string * param_2);
    void clearToolTip();
    void cleanupScreen();
    void setMouseCursor(std::string * param_2);
    void setMouseOverlay(void * param_2);
    void updateMouseCursor();
    void onMouseMove(float param_2, float param_3);
    void onMouseUp(float param_2, float param_3);
    void onMouseDown(float param_2, float param_3);
    void updateMousePosition(bool param_1, bool param_2);
    ScreenElement * getElementAtPosition(undefined4 param_2, undefined4 param_3);
    void update(float param_1, bool param_2);
};
