// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Screen_PC {
public:
    Screen_PC(ScreenInterface * param_1, int param_2, int param_3);
    void configure();
    bool onKeyReleased(KeyCode param_1, Event * param_2);
    void renderBottomLine();
    void executeCommand(char * param_2);
    void updateScreenCall();
    void addString(void * param_2);
    void cmd_DIR();
    void cmd_VIEW(char param_1, std::string * param_3, int param_4);
    void cmd_DEL(char param_1, std::string * param_3, int param_4);
    void cmd_News(char param_1);
    void cmd_Email(char param_1);
    std::string * getCurrentBootString();
};
