// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Sector {
public:
    Faction * getMainFaction();
    Zone * getZone(float param_2, float param_3, char param_4);
    SyntheticObject * getSyntheticObjectWithID(int param_1);
    SyntheticObject * addSyntheticObject(int param_1);
    void removeSyntheticObject(SyntheticObject * param_1);
    void addStellarObject(StellarObject * param_1);
    StellarObject * getStellarObjectNear();
    void removeWeapon(Weapon * param_1);
    void removeAllWeapons();
    void removeShip(Ship * param_1);
    Ship * getShip(int param_1);
    Ship * getShip(char * param_2);
    Ship * getShipClosestTo(int param_2);
    Ship * getSpaceStationClosestTo();
    float getAngleToNearestStar(undefined4 param_2, undefined4 param_3);
    float getSolarRadiationAt();
    void clearBounties();
    void setNewBounties();
    NavPoint * getNavPointNear();
    NavPoint * getNavPointNearZoneSet(char * param_2);
    int getNavMeshIDClosestTo(undefined4 param_2, undefined4 param_3, char param_4);
    NavPoint * getNavPoint(int param_1, NavPointType param_2);
    NavPoint * getNavPoint(int param_1);
    NavPoint * getRandomNavPoint(MeshCategory param_1);
    NavPoint * getRandomNavPointNotNear(int param_1);
    void repopulateTradeLocations();
    static int s_zoneID;  // data symbol used as Sector::s_zoneID
};
