// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class SensorData {
public:
    ~SensorData();
    SensorData(int param_1, int param_2, float param_3);
    void getSolutionString();
    Vec2 * getPresumedLocation();
    void describeDetail(bool param_1);
    void describe(bool param_1, char param_2);
    bool canBeMooredWith();
    bool isSynthetic();
    bool analysed();
};
