// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class SensorManager {
public:
    void down(Ship * param_1);
    void up(Ship * param_1);
    void left(Ship * param_1);
    void right(Ship * param_1);
    bool keyPressed(KeyCode param_1);
    static undefined4 vftable;  // data symbol used as SensorManager::vftable
};
