// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ServerPresentationInterface {
public:
    ~ServerPresentationInterface();
    void renderOutlines();
    void update(float param_1);
    void configureMenus();
    void renderServerMenu();
    void quit(int param_1);
    void forceStart(int param_1);
    void setScenario(int param_1);
    bool difficultySelected(int param_1);
    void setDifficulty(int param_1);
};
