// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ShipClass {
public:
    ShipClass(VesselType param_1);
    ShipConfiguration * getShipConfiguration(char * param_2);
    void unpackAndAddConfiguration(char * param_2, undefined4 param_3, undefined4 param_4, char * param_5, undefined8 param_6);
    void hullStrengthForSection(HullLocation param_1);
    bool canBeDockedWith();
};
