// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ShipModule {
public:
    bool isAtHighPower();
    bool hasBooted();
    ShipModule(ShipModuleClass * param_1);
    void resetDefaultEMCONState();
    int getWidth();
    int getHeight();
    void drainPower(float param_1);
    float getCurrentPowerDrain();
    void generatePower(float param_1);
    bool isDestroyed();
    bool isDamaged();
    int getValue();
    float getInvertedEfficiencyFloat();
    int getFreeHousingSlots();
    void removeAllHousedObjects();
    int getHousedObjectCount();
    bool validHousedWeaponInSlot(int param_1);
    float actualMaxPowerStorage();
    float getCurrentGenerationRate();
    float getCurrentLADARRange();
    float getCurrentJumpRange();
    void damageModule(int param_1, int param_2);
    bool isFunctional(bool param_1);
    void disconnect(Ship * param_1);
    void connect(Ship * param_1);
    float runLogic(float param_1, Ship * param_2);
    static undefined4 vftable;  // data symbol used as ShipModule::vftable
};
