// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ShipBehaviour {
public:
    ShipBehaviour(Ship * param_1, CraftPurpose param_2);
    ~ShipBehaviour();
    void configureShipDesires();
    void detectWeaponLaunch(Ship * param_1, Weapon * param_2);
    void forgetPiracyTarget(Ship * param_1);
    void runLogic(float param_1);
    bool hasSentMessageForFlag(char * param_2);
    void updateSurroundingData();
    void giveTravelTask(GameObject * param_1, bool param_2);
    void merchant_runLogic(float param_1);
    bool respondToPirateDemand(Ship * param_1);
    void general_runLogic(float param_1);
    void runGeneralDestinationLogic(float param_1);
    int getNextTubeWithValidWeapon();
    void correctWaypointsToFlyWith(Ship * param_1, FollowMode param_2);
};
