// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ShipChatter {
public:
    void runLogic(float param_1);
    int getCurrentTransmissionQuality();
    void addMessage(undefined4 param_1, std::string * param_3);
};
