// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ShipMechanics {
public:
    int hullRepairCost(Ship * param_1, HullLocation param_2);
    int getRepairPoints(Ship * param_1);
    void performHullRepairAll(Ship * param_1);
    void itemiseHullRepairCost(Ship * param_1, TextEngine * param_2);
    int moduleRepairCost(Ship * param_1);
};
