// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class ShipNumericalData {
public:
    static void getDataFunction(ShipDataType param_1);
    static double getPowerFlow(Ship * param_1, int param_2);
    static double getPowerFlowPercent(Ship * param_1, int param_2);
    static double getPowerLevel(Ship * param_1, int param_2);
    static double getPowerLevelPercent(Ship * param_1, int param_2);
    static double getPowerGeneration(Ship * param_1, int param_2);
    static double getPowerGenerationPercent(Ship * param_1, int param_2);
    static double getPowerDrain(Ship * param_1, int param_2);
    static double getPowerDrainPercent(Ship * param_1, int param_2);
    static double getDirection(Ship * param_1, int param_2);
    static double getMotionAngle(Ship * param_1, int param_2);
    static double getDesiredDirection(Ship * param_1, int param_2);
    static double getCurrentSpeed(Ship * param_1, int param_2);
    static double getCurrentSpeedPercent(Ship * param_1, int param_2);
    static double returnNothing(Ship * param_1, int param_2);
    static double getInteriorPressure(Ship * param_1, int param_2);
    static double getExteriorPressure(Ship * param_1, int param_2);
    static double getAirlockPressure(Ship * param_1, int param_2);
    static double getCurrentDistanceToNavObject(Ship * param_1, int param_2);
    static double getCurrentBearingToNavObject(Ship * param_1, int param_2);
    static double getNebulaDensity(Ship * param_1, int param_2);
    static double getTubeSelected(Ship * param_1, int param_2);
    static double getTemperature(Ship * param_1, int param_2);
    static double getAmountOwedToDockedStation(Ship * param_1, int param_2);
    static double getAmountOwedToCommsStation(Ship * param_1, int param_2);
    static double getTubeSpinUpPercent(Ship * param_1, int param_2);
    static double getCurrentTubeSpinUpPercent(Ship * param_1, int param_2);
    static double getEngCurrentRepairPercent(Ship * param_1, int param_2);
    static double getJumpSolution(Ship * param_1, int param_2);
    static double getHullHeatTemperature(Ship * param_1, int param_2);
    static double getSolarRadiationPercent(Ship * param_1, int param_2);
    static double getMainDrivePowerLevel(Ship * param_1, int param_2);
    static double getGrappleArmPercentage(Ship * param_1, int param_2);
    static double getHackPercentage(Ship * param_1, int param_2);
    static double getPendingEmails(Ship * param_1, int param_2);
    static double getReadEmails(Ship * param_1, int param_2);
    static double getUnreadEmails(Ship * param_1, int param_2);
    static double getPlayerCredits(Ship * param_1, int param_2);
};
