// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class SoundEngine {
public:
    void shutdown();
    int addSound(int param_1, Sound param_2, int param_3, bool param_4, bool param_5, float param_6);
    void removeAllSounds();
    void playSound(Sound param_1, int param_2);
    void playSound(Ship * param_1, Sound param_2, int param_3);
    void pauseSound(int param_1);
    void unpauseSound(int param_1);
    void setSoundSpace(SoundSpace * param_1);
    void resumeTrack();
    void playNewTrack();
    void resetSoundVolume();
    void setMusicVolume(float param_1);
    void runLogic(float param_1);
    void playRandomKeyPress(Ship * param_1);
};
