// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class SpaceStation {
public:
    SpaceStation(undefined4 param_1, void * param_3);
    void shipUndocking(Ship * param_1);
    void shipDocking(Ship * param_1);
    bool shipHasPaidForUse(char * param_2);
    bool requestUndockingClearance(Ship * param_1, bool param_2);
    void regenerateExtras();
    std::string * getTagFor(std::string * param_2, char * param_3);
    void dockShip(Ship * param_1);
    bool shipHasDockingClearance(Ship * param_1);
    bool shipHasUndockingClearance(Ship * param_1);
    DockingRequest * getDockingRequest(Ship * param_1);
    void runLogic(float param_1);
    void checkExistState();
    void addAmount(int param_1);
    void removeAmount(int param_1);
    int getCurrentAmountOwed();
    void clearPassengers();
    void populatePassengers();
};
