// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class StackWalker {
public:
    ~StackWalker();
    int LoadModules();
    int ShowCallstack(void * param_1, _CONTEXT * param_2, _func_int_void_ptr___uint64_void_ptr_ulong_ulong_ptr_void_ptr * param_3, void * param_4);
    int myReadProcMem(void * param_1, __uint64 param_2, void * param_3, ulong param_4, ulong * param_5);
    void OnLoadModule(char * param_1, char * param_2, __uint64 param_3, ulong param_4, ulong param_5, char * param_6, char * param_7, __uint64 param_8);
    void OnCallstackEntry(CallstackEntryType param_1, CallstackEntry * param_2);
    void OnDbgHelpErr(char * param_1, ulong param_2, __uint64 param_3);
    void OnSymInit(char * param_1, ulong param_2, char * param_3);
    void OnOutput(char * param_1);
    static undefined4 vftable;  // data symbol used as StackWalker::vftable
};
