// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class StackWalkerInternal {
public:
    StackWalkerInternal(StackWalker * param_1, void * param_2);
    int Init(char * param_1);
    int GetModuleListPSAPI(void * param_1);
    ulong LoadModule(void * param_1, char * param_2, char * param_3, __uint64 param_4, ulong param_5);
    int GetModuleInfo(void * param_1, __uint64 param_2, IMAGEHLP_MODULE64_V3 * param_3);
    static undefined4 IMAGEHLP_MODULE64_V3;  // data symbol used as StackWalkerInternal::IMAGEHLP_MODULE64_V3
};
