// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Stats {
public:
    Stats();
    void setBinaryStat(void * param_2);
    void setStat(void * param_2);
    void addStat(int param_2, void * param_3);
    bool storeStats();
    void onUserStatsReceived(UserStatsReceived_t * param_1);
    void onUserStatsStored(UserStatsStored_t * param_1);
    bool hasCustomStat(void * param_2);
    float getCustomStat(void * param_2);
    void setCustomStat(void * param_2);
};
