// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class SystemManager {
public:
    void generatePower(float param_1);
    bool drawPower(float param_1);
    ShipModule * addEmptyModule(int param_1, void * param_3);
    bool addModule(ShipModule * param_1, int param_2);
    void removeModule(ShipModule * param_1);
    bool canAddModule(ShipModule * param_1);
    ShipModule * getModule(ModuleType param_1, bool param_2);
    void connectModulesOfType(ModuleType param_1);
    void disconnectModulesOfType(ModuleType param_1);
    ShipModule * getModule(int param_1);
    int getSlotForType(ModuleType param_1);
    float getMaxBatteryStorage();
    float getMaxTheoreticalPowerGeneration();
    ShipModule * getBattery(int param_1);
    int getCurrentPowerPercentage();
    float totalCurrentPower();
    float totalPossiblePower();
    void resetHardware(int param_1);
    float totalPowerDrain();
    float totalPowerGeneration();
    void runAttritionLogic(float param_1);
    void newDamage(HullLocation param_1, float param_2, DamageType param_3);
    void damage(HullLocation param_1, float param_2, DamageType param_3);
};
