// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class TabletOmega {
public:
    TabletOmega();
    void renderTopFrame(std::string * param_1);
    void renderBottomFrame(std::string * param_1);
    void renderLine(undefined4 param_1_00, std::string * param_1, int param_3, char * param_4);
    void renderCenterLine(undefined4 param_1_00, std::string * param_1, char * param_3);
    void render(bool param_1);
    void renderHeader();
    void renderFooter();
    TabletTab * getTab(int param_1);
    bool keyPressed(KeyCode param_1);
};
