// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class TabletManager {
public:
    void getTabletSummary();
    void getNotes();
    void getTranslateString();
    void selectElement();
    void runLogic(float param_1);
    bool keyPressed(KeyCode param_1);
    void performMetaGameAction(MetaGameAction * param_1, CargoHold * param_2, BankAccount * param_3);
    void setElement(int param_1);
};
