// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class TextEngine {
public:
    TextEngine(TextField * param_1, int param_2, int param_3, int param_4, ghidra::vector * param_5);
    void showDocument(undefined4 * param_2);
    void finishShowingDocument();
    void renderDocument();
    void renderDocumentFooter();
    void showList(undefined4 param_2, undefined4 param_3, undefined4 param_4, int param_5, std::string * param_6);
    void renderList();
    void finishShowingList(bool param_1);
    void render();
    bool lineIsNull(undefined4 param_1, undefined4 * param_2);
    bool lineEndsWithSpace(undefined4 param_1, undefined4 * param_2);
    void addLineWithWrap(uint param_2, undefined4 * param_3);
    void addBlankLine();
    void addLine(void * param_2);
    void addLinef(char * param_1, ...);
    void setBottomText(std::string * param_2);
};
