// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class TextField {
public:
    TextField(ScreenInterface * param_1, Widget * param_2, bool * param_3, int param_4, int param_5, void * param_7);
    void cleanupRender();
    void setText(undefined4 param_1, int param_2, undefined4 * param_4);
    void update();
    void paintBackground(undefined4 param_2, undefined4 param_3, int param_4, int param_5);
};
