// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class TopBar {
public:
    TopBar(bool param_1, bool param_2);
    ~TopBar();
    void cleanupRender();
    void resetTabs(int param_1);
    void runLogic(float param_1);
    void render();
    void updateBarPosition();
};
