// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class TradeLocation {
public:
    ~TradeLocation();
    void addTradeItemInstance(TradeItemInstance * param_1, bool param_2);
    void addContractGoods(char * param_2);
    void removeGoods(int param_1, int param_2);
    void soldGood(int param_1, int param_2);
    int goodAmountWire(int param_1);
    bool doesBuyWire(int param_1);
    void itemiseSaleDetailsWire(int param_1, int param_2);
    int goodAmount(char * param_2);
    int goodAmount(int param_1);
    void clearGoods(bool param_1);
    int singleBaseGoodCost(int param_1, bool param_2);
    int singleGoodCost(int param_1, bool param_2);
    int goodCost(int param_1, int param_2, bool param_3);
    int singleGoodCostWire(int param_1, bool param_2);
    int goodCostWire(int param_1, int param_2, bool param_3);
    void itemiseSaleDetails(int param_1, int param_2);
    void getCurrentTradeSummary();
    void getCurrentBuyPrices();
    void getCurrentContractSummary();
    void getCurrentPassengerSummary();
    bool doesBuy(int param_1);
    void resetAndRepopulate();
    void resetContracts();
    void clearContracts();
    void populateContracts();
    void restockWithContracts();
    void addRandomComponents();
    void addRandomModules();
    void clearShipsForSale();
    void regenerateShipsForSale();
    void generateShip(ShipSale * param_1);
};
