// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_BDBar {
public:
    void setValue(double param_1);
    UI_BDBar(ScreenInterface * param_1, Widget * param_2, bool * param_3, float param_4, int param_5, int param_6);
    void cleanupRender();
    void render();
};
