// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_ComponentStorage {
public:
    void cleanupRender();
    std::string * getDragLook(std::string * param_2, undefined4 param_3, undefined4 param_4);
    int getDragValue(undefined4 param_2, undefined4 param_3);
    void dragOnto(undefined4 param_1_00, int param_1, int param_2);
    void specialDataCheckFunction(float param_1);
    void render();
    void mouseUp(float param_2, float param_3);
    int getElement(float param_2, float param_3);
    static undefined4 vftable;  // data symbol used as UI_ComponentStorage::vftable
};
