// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_EngPanel {
public:
    ~UI_EngPanel();
    void cleanupRender();
    bool keyUp(KeyCode param_1);
    void render();
    void mouseUp(float param_2, float param_3);
    void mouseHoverUpdate(float param_2, float param_3);
    void specialDataCheckFunction(float param_1);
    std::string * getDragLook(std::string * param_2, float param_3, float param_4);
    int getDragValue(float param_2, float param_3);
    void dragOnto(int param_1, int param_2, float param_4, float param_5);
    static undefined4 vftable;  // data symbol used as UI_EngPanel::vftable
};
