// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_Image {
public:
    UI_Image(ScreenInterface * param_1, Widget * param_2, bool * param_3, undefined4 param_5, undefined4 param_6, void * param_7);
    ~UI_Image();
    void cleanupRender();
    void render();
    void cacheFrames();
    void specialDataCheckFunction(float param_1);
};
