// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_IconTray {
public:
    UI_IconTray(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~UI_IconTray();
    void cleanupRender();
    void render();
    void specialDataCheckFunction(float param_1);
    void mouseHoverUpdate(float param_2, float param_3);
    void mouseHoverCancel();
    void mouseMove(float param_2, float param_3);
    void mouseUp(float param_2, float param_3);
    bool canNext();
    std::string * getDragLook(std::string * param_2, float param_3, float param_4);
    int getDragValue(float param_2, float param_3);
    void dragOnto(undefined4 param_1, int param_2, float param_4, float param_5);
};
