// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_ModuleRepair {
public:
    UI_ModuleRepair(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~UI_ModuleRepair();
    void cleanupRender();
    void renderLine(undefined4 param_2, undefined4 param_3, undefined4 param_4, undefined4 param_5, char param_6);
    void renderComponent(int param_1, ShipModule * param_2, bool param_3);
    void renderButton();
    void render();
    void specialDataCheckFunction(float param_1);
    void setScrewState();
    void syncAddonAndComponentStates();
    void setCoverState();
    bool runAnimations(float param_1);
    bool anyScrews();
    void mouseHoverUpdate(undefined4 param_2, float param_3);
    void mouseUp(float param_2, float param_3);
    int getComponentSlot();
    void dragOnto(int param_1, int param_2, undefined4 param_4, float param_5);
    std::string * getDragLook(std::string * param_2, undefined4 param_3, float param_4);
    int getDragValue(undefined4 param_2, float param_3);
};
