// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_Menu {
public:
    UI_Menu(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~UI_Menu();
    void cleanupRender();
    bool recheckButtonPressed(float param_2, float param_3);
    void render();
    void specialDataCheckFunction(float param_1);
    void mouseMove(undefined4 param_2, float param_3);
    void mouseUp(undefined4 param_2, float param_3);
    void mouseHoverCancel();
    bool triggerButton(ButtonElement * param_1);
    void runTrigger(void * param_2);
    void clearMenu();
    void removeButtonData();
    void changedMenu();
    bool canNext();
    void updateButtonSelected();
    void performPrev();
    void performNext();
    bool keyDown(KeyCode param_1);
    bool keyUp(KeyCode param_1);
    bool containsPoint(undefined4 param_2, undefined4 param_3);
};
