// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_NavMap {
public:
    UI_NavMap(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~UI_NavMap();
    void cleanupRender();
    float getIconScale();
    float getStellarScale();
    void render();
    void renderMiniMap();
    void sectorModeClick(float param_2, float param_3);
    void editorModeClick();
    void mouseHoverUpdate(undefined4 param_2, undefined4 param_3);
    void mouseUp(undefined4 param_2, undefined4 param_3);
    void specialDataCheckFunction(float param_1);
    StellarObject * getStellarObjectLook(StellarObject * param_1);
    SensorData * getShipLook(SensorData * param_1, bool param_2);
    Ship * getShipLook(Ship * param_1, bool param_2);
    void centreOfMap();
    float * positionForWorldPosition(float * param_2, float param_3, float param_4);
    float * worldPositionForPosition(float * param_2, float param_3, float param_4);
    void renderDetectionCone(SensorData * param_1, NM_MapObject * param_2, float param_3);
    void renderSensorObject(SensorData * param_1, float param_2);
    void renderCraft(Ship * param_1, SensorData * param_2, float param_3);
    void renderSector();
    void renderCluster();
    bool keyDown(KeyCode param_1);
    bool keyUp(KeyCode param_1);
    void cancelAllKeys();
};
