// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_PowerScreen {
public:
    ~UI_PowerScreen();
    void cleanupRender();
    void render();
    void renderModule(ShipModule * param_1, int param_2, int param_3);
    void updateRender();
    bool updateEmissionState(Sprite * param_1, ShipModule * param_2);
    void specialDataCheckFunction(float param_1);
    void mouseUp(float param_2, float param_3);
    void mouseHoverUpdate(float param_2, float param_3);
    Sprite * renderEmcon(bool param_1);
    static undefined4 vftable;  // data symbol used as UI_PowerScreen::vftable
};
