// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_SelectTray {
public:
    ~UI_SelectTray();
    void cleanupRender();
    void render();
    void mouseMove(undefined4 param_2, undefined4 param_3);
    void mouseUp(float param_2, float param_3);
    void mouseCancel();
    bool checkButtonStates(float param_2, float param_3);
    static undefined4 vftable;  // data symbol used as UI_SelectTray::vftable
};
