// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_ShipHullState {
public:
    UI_ShipHullState(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    void cleanupRender();
    void render();
    bool checkState(float param_1);
    void specialDataCheckFunction(float param_1);
};
