// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_Sheet {
public:
    void mouseCancel();
    UI_Sheet(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~UI_Sheet();
    void cleanupRender();
    void render();
    void specialDataCheckFunction(float param_1);
    void mouseMove(float param_2, float param_3);
    void mouseUp(float param_2, float param_3);
    bool keyUp(KeyCode param_1);
};
