// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_StatusBar {
public:
    void setValue(double param_1);
    UI_StatusBar(ScreenInterface * param_1, Widget * param_2, bool * param_3, float param_4, float param_5, int param_6, int param_7);
    void render();
};
