// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_SensorWaveform {
public:
    void cleanupRender();
    void renderPeak(float * param_1, undefined4 param_2, undefined4 param_3, undefined4 param_5);
    void render();
    void renderDigital();
    void renderAnalog();
    void specialDataCheckFunction(float param_1);
    static undefined4 vftable;  // data symbol used as UI_SensorWaveform::vftable
};
