// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_TextField {
public:
    void cleanup();
    UI_TextField(ScreenInterface * param_1, Widget * param_2, bool * param_3);
    ~UI_TextField();
    void cleanupRender();
    void render();
    void specialDataCheckFunction(float param_1);
    void mouseDown(undefined4 param_2, undefined4 param_3);
    void mouseUp(undefined4 param_2, undefined4 param_3);
    void mouseCancel();
    void resetButtonsValid();
    void updatePressedStates(float param_2, float param_3);
};
