// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UI_WeaponTubes {
public:
    ~UI_WeaponTubes();
    void cleanupRender();
    void render();
    void specialDataCheckFunction(float param_1);
    void mouseHoverUpdate(float param_2);
    void mouseUp(undefined4 param_1, float param_2);
    static undefined4 vftable;  // data symbol used as UI_WeaponTubes::vftable
};
