// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class UIText {
public:
    UIText(int param_1, undefined4 param_2, UIText param_4, void * param_5);
    static UIText * create(undefined1 param_1, void * param_2);
    static UIText * create(void * param_1);
    ~UIText();
    static void translateColour(char param_1);
    void setText(char param_2, char param_3, std::string * param_4);
    void cleanup();
    void cleanupRender();
    static int generateLines(undefined4 * param_1);
    void update();
    static int getRealWidthWithoutMacros(void * param_1);
    static void getTextWithoutMacros(undefined4 * param_1);
    static int getActualTextWidth(void * param_1);
    void setOpacity(uchar param_1);
};
