// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class V11 {
public:
    static TradeItemInstance * readTradeItem(_iobuf * param_1);
    static Contract * readContract(_iobuf * param_1);
    static void loadPassenger(_iobuf * param_1);
    static CargoHold * readCargo(_iobuf * param_1);
    static void loadShips(_iobuf * param_1);
    static void loadSpaceStationStates(_iobuf * param_1);
};
