// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class V12 {
public:
    static void saveStats(_iobuf * param_1);
    static void saveFogOfWarState(_iobuf * param_1);
    static void saveEmails(_iobuf * param_1);
    static void saveFlags(_iobuf * param_1);
    static void saveFactionStates(_iobuf * param_1);
    static void savePlayerContracts(_iobuf * param_1);
    static void loadPlayerContracts(_iobuf * param_1);
    static void writeBounty(_iobuf * param_1, Bounty * param_2);
    static void saveSpaceStationStates(_iobuf * param_1);
    static void loadSpaceStationStates(_iobuf * param_1);
    static void writeTradeItem(_iobuf * param_1, TradeItemInstance * param_2);
    static void writeContract(_iobuf * param_1, Contract * param_2);
    static void writeCargo(_iobuf * param_1, CargoHold * param_2);
    static CargoHold * readCargo(_iobuf * param_1);
    static void saveShip(_iobuf * param_1, Ship * param_2);
    static Ship * loadShip(_iobuf * param_1);
    static void savePassenger(_iobuf * param_1);
    static void writeShipModule(_iobuf * param_1, ShipModule * param_2);
    static ShipModule * readShipModule(_iobuf * param_1);
};
