// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class V9 {
public:
    static void loadFogOfWarState(_iobuf * param_1);
    static void loadEmails(_iobuf * param_1);
    static void loadPlayerContracts(_iobuf * param_1);
    static void loadSpaceStationStates(_iobuf * param_1);
    static void loadShips(_iobuf * param_1);
};
