// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Weapon {
public:
    ~Weapon();
    bool isSpinningUp();
    bool isWeapon();
    Weapon(Ship * param_1, WeaponClass * param_2);
    void getSolutionString();
    bool alwaysKnown(Ship * param_1);
    int getSpinUpPercent(int param_1);
    int getCurrentCalculatedPowerPercantage(int param_1);
    bool canFire();
    bool isDestroyed();
    bool damage(int param_1, float param_2, DamageType param_3);
    void destroy();
    void runHomeLogic(float param_1);
    void detonateWarhead();
    void runEmissionsLogic(float param_1);
    void runLogic(float param_1);
    void updateTarget();
    void runTravelLogic(float param_1);
    void runStopLogic(float param_1);
    void runAimLogic(undefined4 param_1, undefined4 param_3);
    void goActive();
    void setTarget(GameObject * param_1);
    void unsetTarget();
};
