// GENERATED by scripts/gen_class_headers.py from the Ghidra export, then hand-edited.
// Member layout, virtual functions, const-ness and true parameter types are UNKNOWN
// unless noted; parameter types below are Ghidra's guesses.
#pragma once
#include "ois/ois_fwd.hpp"

class Widget {
public:
    Widget();
    ~Widget();
    Widget(Widget * param_1);
    void unpackExistFunction(void * param_2);
    void unpackOptions(int param_2, int param_3, undefined4 param_4, uint param_5);
    bool getOptionAsBool(void * param_2);
    bool hasOption(void * param_2);
    std::string * getOption(std::string * param_2, void * param_3);
};
