#!/usr/bin/env python3
"""Syntax-check the reconstructed sources with clang and report progress.

    python3 scripts/compile_check.py --cocos third_party/cocos2d-x
    python3 scripts/compile_check.py --cocos ... --write-status   # refresh reconstruct/COMPILE_STATUS.md

What is checked
  * every reconstruct/src/*.cpp, as its own translation unit
    (clang++ -fsyntax-only; nothing is linked or run)
  * headers are precompiled once, so a run takes seconds, not minutes

This is a *syntax and type* check on a 32-bit (-m32) Linux target against the real
cocos2d-x 3.15.1 headers.  It proves the code is well-formed C++, not that it
behaves like the original, and it does not check struct sizes (the original is
32-bit).  See reconstruct/README.md.

Exit status is 0 only when every translation unit is clean, so CI can gate on it.
"""

import argparse
import collections
import json
import re
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RECON = REPO / "reconstruct"
ERR = re.compile(r"^(?P<file>.+?):(?P<line>\d+):(?P<col>\d+): (?P<kind>error|fatal error): (?P<msg>.*)$")


def flags(cocos):
    c = Path(cocos)
    return ["-m32", "-DLINUX", "-std=c++14", "-ferror-limit=0", "-Wno-everything", "-fno-color-diagnostics",
            f"-I{RECON / 'include'}", f"-I{c}", f"-I{c / 'cocos'}", f"-I{c / 'cocos/platform/linux'}",
            f"-I{c / 'external'}", f"-I{c / 'extensions'}", "-I/usr/include/GLFW", "-I/usr/include/freetype2"]


def normalise(msg):
    msg = re.sub(r"'[^']*'", "X", msg)
    msg = re.sub(r"\b\d+\b", "N", msg)
    return msg[:90]


def check_one(path, fl, pch):
    cmd = ["clang++", *fl, "-fsyntax-only", "-x", "c++"]
    if pch:
        cmd += ["-include-pch", str(pch)]
    cmd.append(str(path))
    r = subprocess.run(cmd, capture_output=True, text=True)
    errs = []
    for line in r.stderr.splitlines():
        m = ERR.match(line)
        if m:
            errs.append((m["file"], int(m["line"]), m["msg"]))
    return path, errs


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cocos", required=True, help="cocos2d-x 3.15.1 checkout (see scripts/fetch_cocos2d.sh)")
    ap.add_argument("--write-status", action="store_true", help="write reconstruct/COMPILE_STATUS.md")
    ap.add_argument("--jobs", type=int, default=4)
    ap.add_argument("files", nargs="*", help="limit to these files")
    args = ap.parse_args()

    fl = flags(args.cocos)
    umbrella = RECON / "include/ois/ois_all.hpp"
    umbrella.write_text('#include "ois/ois.hpp"\n#include "ois/ois_globals.hpp"\n#include "ois/ghidra_lib_stubs.hpp"\n')
    tmp = Path(tempfile.mkdtemp())
    pch = tmp / "ois.pch"
    r = subprocess.run(["clang++", *fl, "-x", "c++-header", str(umbrella), "-o", str(pch)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print("Headers do not compile; fix these first:\n"
              + "\n".join(l for l in r.stderr.splitlines() if "error" in l)[:3000])
        return 2

    sources = [Path(f) for f in args.files] or sorted((RECON / "src").glob("*.cpp"))
    with ThreadPoolExecutor(args.jobs) as ex:
        results = list(ex.map(lambda p: check_one(p, fl, pch), sources))

    per_file = {p.name: len(e) for p, e in results}
    clean = sorted(n for n, c in per_file.items() if c == 0)
    cats = collections.Counter()
    for _, errs in results:
        for _, _, msg in errs:
            cats[normalise(msg)] += 1
    total = sum(per_file.values())
    # "compiles" is not "understood": count the stand-ins that still need real code
    placeholders = {"ghidra::lib placeholders (unrecovered std/cocos2d calls)": r"ghidra::lib::",
                    "pseudo-variables (unknown register/stack inputs)": r"\[pseudo\]",
                    "any_singleton() (Singleton<T> not yet identified)": r"any_singleton\(\)"}
    ph_counts = {k: 0 for k in placeholders}
    for src in (RECON / "src").glob("*.cpp"):
        text = src.read_text(errors="replace")
        for k, rx in placeholders.items():
            ph_counts[k] += len(re.findall(rx, text))
    print(f"{len(clean)}/{len(sources)} translation units clean, {total} errors")
    for msg, n in cats.most_common(15):
        print(f"{n:7d}  {msg}")

    if args.write_status:
        lines = ["# Compile status", "",
                 "Generated by `scripts/compile_check.py --write-status` (clang `-fsyntax-only`, "
                 "cocos2d-x 3.15.1 headers, 32-bit (-m32) Linux target).", "",
                 f"- translation units clean: **{len(clean)} / {len(sources)}**",
                 f"- errors remaining: **{total}**", "",
                 "## Most common errors", ""]
        lines += [f"- {n} x `{m}`" for m, n in cats.most_common(25)]
        lines += ["", "## Stand-ins still in the code", "",
                  "Code that type-checks is not code that is *understood*. These count the placeholders "
                  "that make it type-check:", ""]
        lines += [f"- {n} x {k}" for k, n in ph_counts.items()]
        lines += ["", "## Files closest to clean", ""]
        lines += [f"- `{n}`: {c}" for n, c in sorted(per_file.items(), key=lambda x: x[1]) if c][:30]
        (RECON / "COMPILE_STATUS.md").write_text("\n".join(lines) + "\n")
        (RECON / "compile_status.json").write_text(json.dumps(
            {"clean": len(clean), "total": len(sources), "errors": total, "per_file": per_file}, indent=1))
    return 0 if total == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
