void _dynamic_initializer_for__firstTimeBonusStr__(void);
__uint64 * ___local_stdio_printf_options(void);
int __cdecl __vsnprintf_l(char *_DstBuf,size_t _MaxCount,char *_Format,_locale_t _Locale,va_list _ArgList);
int __cdecl _sprintf(char *_Dest,char *_Format,...);
int __cdecl __vfprintf_l(FILE *_File,char *_Format,_locale_t _Locale,va_list _ArgList);
int __cdecl _printf(char *_Format,...);
int __cdecl _vsnprintf(char *_Dest,size_t _Count,char *_Format,va_list _Args);
int __cdecl _fprintf(FILE *_File,char *_Format,...);
int __cdecl _snprintf_s<1024>(char *param_1,uint param_2,char *param_3,...);
void _WinMain@16(void);
char * __fastcall _Itoa(int param_1,char *param_2);
void __fastcall __security_check_cookie(int param_1);
void __ArrayUnwind(void *param_1,uint param_2,uint param_3,_func_void_void_ptr *param_4);
undefined4 __scrt_initialize_thread_safe_statics(void);
_func_int__RTL_CONDITION_VARIABLE_ptr__RTL_CRITICAL_SECTION_ptr_ulong * __cdecl __crt_fast_encode_pointer<>(_func_int__RTL_CONDITION_VARIABLE_ptr__RTL_CRITICAL_SECTION_ptr_ulong *param_1);
void __scrt_initialize_thread_safe_statics_platform_specific(void);
void __scrt_uninitialize_thread_safe_statics(void);
void __Init_thread_abort(undefined4 *param_1);
void __Init_thread_footer(int *param_1);
void __cdecl __Init_thread_header(int *param_1);
void __Init_thread_notify(void);
void __cdecl __Init_thread_wait(DWORD param_1);
undefined4 ___scrt_acquire_startup_lock(void);
int __cdecl ___scrt_initialize_crt(int param_1,int param_2);
undefined4 __cdecl ___scrt_initialize_onexit_tables(int param_1);
uint __cdecl ___scrt_is_nonwritable_in_current_image(int param_1);
int __cdecl ___scrt_release_startup_lock(char param_1);
undefined1 __cdecl ___scrt_uninitialize_crt(Ship *param_1,char param_2);
_onexit_t __cdecl __onexit(_onexit_t _Func);
int __cdecl _atexit(_func_4879 *param_1);
void __cdecl ___raise_securityfailure(_EXCEPTION_POINTERS *param_1);
void __cdecl ___report_gsfailure(void);
void ___report_rangecheckfailure(void);
void __cdecl ___report_securityfailure(undefined4 param_1);
int __scrt_common_main_seh(void);
void _WinMainCRTStartup(void);
void __cdecl __scrt_throw_std_bad_alloc(void);
void __cdecl __scrt_throw_std_bad_array_new_length(void);
void __cdecl __SEH_prolog4(undefined4 param_1,int param_2);
void __SEH_epilog4(void);
void __cdecl __except_handler4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void ___scrt_fastfail(void);
ushort ___scrt_get_show_window_mode(void);
int __cdecl ___scrt_initialize_mta(_exception *_Except);
int __cdecl ___scrt_exe_initialize_mta(_exception *_Except);
uint ___scrt_is_managed_app(void);
void ___scrt_set_unhandled_exception_filter(void);
undefined4 ___scrt_unhandled_exception_filter@4(int *param_1);
void __cdecl __crt_debugger_hook(int param_1);
undefined4 ___isa_available_init(void);
undefined4 __get_startup_argv_mode(void);
bool ___scrt_is_ucrt_dll_in_use(void);
uint __get_entropy(void);
void __cdecl ___security_init_cookie(void);
undefined4 __get_startup_file_mode(void);
void __cdecl __scrt_initialize_type_info(void);
void __initialize_default_precision(void);
__uint64 * ___local_stdio_scanf_options(void);
void ___scrt_initialize_default_local_stdio_options(void);
bool ___scrt_is_user_matherr_present(void);
undefined * ___scrt_get_dyn_tls_init_callback(void);
undefined * ___scrt_get_dyn_tls_dtor_callback(void);
void __RTC_Initialize(void);
void __RTC_Terminate(void);
void ___std_terminate(void);
void __cdecl __purecall(void);
void ___std_exception_copy(void);
void ___std_exception_destroy(void);
void __CxxThrowException@8(void *pExceptionObject,ThrowInfo *pThrowInfo);
void __cdecl __except_handler4_common(void);
int __cdecl __callnewh(size_t _Size);
void __cdecl __configure_narrow_argv(void);
void __cdecl __initialize_narrow_environment(void);
void __cdecl __initialize_onexit_table(void);
void __cdecl __register_onexit_function(void);
void __cdecl __crt_atexit(void);
void __cdecl __cexit(void);
void __cdecl __set_app_type(void);
void ___setusermatherr(void);
void __cdecl __get_narrow_winmain_command_line(void);
void __cdecl __initterm(void);
void __cdecl __initterm_e(void);
void __cdecl __exit(int _Code);
errno_t __cdecl __set_fmode(int _Mode);
void __cdecl __register_thread_local_exe_atexit_callback(void);
int __cdecl __configthreadlocale(int _Flag);
void __cdecl __set_new_mode(void);
void ___p__commode(void);
errno_t __cdecl __controlfp_s(uint *_CurrentState,uint _NewValue,uint _Mask);
BOOL _IsProcessorFeaturePresent@4(DWORD ProcessorFeature);
undefined8 __alldvrm(uint param_1,uint param_2,uint param_3,uint param_4);
void __alloca_probe(void);
uint __alloca_probe_16(void);
uint __alloca_probe_8(void);
undefined8 __aulldiv(uint param_1,uint param_2,uint param_3,uint param_4);
ulonglong __ftoui3(void);
ulonglong __ftoul3(void);
ulonglong __ftol3(void);
ulonglong __fastcall __ftol3_NaN(int param_1);
ulonglong __fastcall __ftol3_work(int param_1);
ulonglong __fastcall __ftol3_common(undefined4 param_1);
undefined8 __fastcall __ftol3_arg_error(undefined4 param_1);
void __fastcall __ftol3_except(undefined4 param_1,int param_2);
void __dtoui3(void);
void __dtoul3(void);
uint __dtol3(void);
uint __fastcall __dtol3_NaN(int param_1);
ulonglong __fastcall __dtol3_work(int param_1);
void __ultod3(void);
void __ltod3(void);
ulonglong __fastcall __ftol2_sse(undefined4 param_1,undefined4 param_2);
int __ftol2_pentium4(void);
ulonglong __fastcall __ftol2_sse_excpt(undefined4 param_1,undefined4 param_2);
ulonglong __ftol2(void);
void __CIatan2(void);
void __CIfmod(void);
void __cdecl __libm_sse2_cos_precise(void);
void __cdecl __libm_sse2_sin_precise(void);
void __cdecl __except1(void);
