DifficultyMode __cdecl getDifficulty(void *param_1);
Quadrant __cdecl getQuadrant(void *param_1);
ModuleSlotType __cdecl getModuleSlotTypeForString(void *param_1);
ScenarioCategory __cdecl getScenarioCategory(void *param_1);
ScenarioType __cdecl getScenarioType(void *param_1);
ShipDataType __cdecl getShipDataType(void *param_1);
ShipDataCheckType __cdecl getShipCheckDataType(void *param_1);
ShipTextDataType __cdecl getShipTextDataType(void *param_1);
ShipDataInputType __cdecl getShipDataInputType(undefined4 *param_1);
void * __cdecl getShipCheckDataPointer(ShipDataInputType param_1);
void __cdecl getShipCheckDataPossibleValues(ShipDataInputType param_1);
ShipCommand __cdecl getShipCommandType(void *param_1);
CaptainStyle __cdecl getCaptainStyle(void *param_1);
CaptainExperience __cdecl getCaptainExperience(void *param_1);
ShipLook __cdecl getShipLookup(void *param_1);
GoodContainmentOption __cdecl getContainmentOption(void *param_1);
HullLocation __cdecl getHullLocationForString(undefined4 *param_1);
CharacterMouthState __cdecl getCharacterMouthState(void *param_1);
CharacterEyeState __cdecl getCharacterEyeState(void *param_1);
OverlaySegment __cdecl getOverlaySegment(void *param_1);
CharacterPosition __cdecl getCharacterPosition(void *param_1);
Sound __cdecl getSound(void *param_1);
__uint64 __cdecl GetTimeUS_Windows(void);
SimpleMutex * __cdecl GetPoolMutex(void);
