char * __thiscall std::basic_string<>::c_str(basic_string<> *this);
basic_string<> * __thiscall std::basic_string<>::basic_string<>(basic_string<> *this,char *param_1);
basic_string<> * __thiscall std::basic_string<>::basic_string<>(basic_string<> *this,basic_string<> *param_1);
void __thiscall std::basic_string<>::_Tidy_init(basic_string<> *this);
basic_string<> * __thiscall std::basic_string<>::operator=(basic_string<> *this,char *param_1);
basic_string<> * __thiscall std::basic_string<>::assign(basic_string<> *this,char *param_1,uint param_2);
void __thiscall std::basic_string<>::_Construct_lv_contents(basic_string<> *this,basic_string<> *param_1);
void __cdecl std::basic_string<>::_Xlen(void);
basic_string<> * __thiscall std::basic_string<>::basic_string<>(basic_string<> *this);
bool __thiscall std::basic_string<>::_Equal(basic_string<> *this,char *param_1);
uint __thiscall std::basic_string<>::substr(basic_string<> *this,uint param_1,uint param_2);
char * __thiscall std::basic_string<>::operator[](basic_string<> *this,uint param_1);
basic_string<> * __thiscall std::basic_string<>::append(basic_string<> *this,char *param_1);
basic_string<> * __thiscall std::basic_string<>::append(basic_string<> *this,basic_string<> *param_1);
basic_string<> * __thiscall std::basic_string<>::basic_string<>(basic_string<> *this,basic_string<> *param_1);
void __thiscall std::basic_string<>::push_back(basic_string<> *this,char param_1);
basic_string<> * __thiscall std::basic_string<>::append(basic_string<> *this,char *param_1,uint param_2);
basic_string<> * __thiscall std::basic_string<>::_Reallocate_grow_by<>(basic_string<> *this,uint param_1,undefined4 param_3,void *param_4,size_t param_5);
void __thiscall std::basic_string<>::end(basic_string<> *this);
void __thiscall std::basic_string<>::begin(basic_string<> *this);
basic_string<> * __thiscall std::basic_string<>::operator=(basic_string<> *this,basic_string<> *param_1);
basic_string<> * __thiscall std::basic_string<>::operator=(basic_string<> *this,basic_string<> *param_1);
bool __thiscall std::basic_string<>::_Equal(basic_string<> *this,basic_string<> *param_1);
void __thiscall std::basic_string<>::~basic_string<>(basic_string<> *this);
void __thiscall std::basic_string<>::_Tidy_deallocate(basic_string<> *this);
basic_string<> * __thiscall std::basic_string<>::_Reallocate_grow_by<>(basic_string<> *this,undefined4 param_1,undefined4 param_3,undefined2 param_4);
void __thiscall std::basic_string<>::_Construct<char*>(basic_string<> *this,char *param_1,char *param_2);
basic_string<> * __thiscall std::basic_string<>::_Reallocate_grow_by<>(basic_string<> *this,uint param_1);
void __thiscall std::basic_string<>::erase(basic_string<> *this,int *param_2,int param_3);
basic_string<> * __thiscall std::basic_string<>::operator=(basic_string<> *this,char param_1);
uint __thiscall std::basic_string<>::find(basic_string<> *this,char *param_1,uint param_2);
basic_string<> * __thiscall std::basic_string<>::_Reallocate_grow_by<>(basic_string<> *this);
basic_string<> * __thiscall std::basic_string<>::replace(basic_string<> *this,uint param_1,uint param_2,char *param_3,uint param_4);
basic_string<> * __thiscall std::basic_string<>::_Reallocate_grow_by<>(basic_string<> *this,uint param_1,undefined4 param_3,size_t param_4,int param_5,void *param_6,size_t param_7);
