void __thiscall std::function<>::~function<>(function<> *this);
bool __thiscall std::function<>::operator_bool(function<> *this);
function<> * __thiscall std::function<>::operator=(function<> *this,function<> *param_1);
function<> * __thiscall std::function<>::function<><>(function<> *this);
function<> * __thiscall std::function<>::operator=(function<> *this,function<> *param_1);
function<> * __thiscall std::function<>::function<>(function<> *this);
function<> * __thiscall std::function<>::operator=<>(function<> *this,function<> *param_1);
function<> * __thiscall std::function<>::function<><>(function<> *this,_func_bool_Ship_ptr_int_basic_string<> *param_1);
function<> * __thiscall std::function<>::function<><>(function<> *this,_func_bool_Ship_ptr_int_int_int *param_1);
function<> * __thiscall std::function<>::function<><>(function<> *this);
function<> * __thiscall std::function<>::function<><>(function<> *this,_func_basic_string<>_Ship_ptr_int *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_func_void_Menu_ptr *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
function<> * __thiscall std::function<>::operator=<>(function<> *this,_Binder<> *param_1);
