void __thiscall std::_Func_impl_no_alloc<>::_Delete_this(_Func_impl_no_alloc<> *this,bool param_1);
void * __thiscall std::_Func_impl_no_alloc<>::_Get(_Func_impl_no_alloc<> *this);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
bool __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,double *param_2,double *param_3,double *param_4);
_Func_impl_no_alloc<> * __thiscall std::_Func_impl_no_alloc<>::_Func_impl_no_alloc<><>(_Func_impl_no_alloc<> *this,function<> *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Delete_this(_Func_impl_no_alloc<> *this,bool param_1);
void * __thiscall std::_Func_impl_no_alloc<>::_Get(_Func_impl_no_alloc<> *this);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void,int> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Delete_this(_Func_impl_no_alloc<> *this,bool param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,int *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Delete_this(_Func_impl_no_alloc<> *this,bool param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
bool __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,int *param_2,basic_string<> *param_3);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
bool __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,int *param_2,int *param_3,int *param_4);
bool __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,int *param_2,int *param_3,int *param_4);
_Func_impl_no_alloc<> * __thiscall std::_Func_impl_no_alloc<>::_Func_impl_no_alloc<><>(_Func_impl_no_alloc<> *this,function<> *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
double __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,int *param_2);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,int *param_2);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<bool,void*> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void,Menu*> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Menu **param_1);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
bool __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,double *param_2,double *param_3,double *param_4);
bool __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,Ship **param_1,double *param_2,double *param_3,double *param_4);
void __thiscall std::_Func_impl_no_alloc<>::_Delete_this(_Func_impl_no_alloc<> *this,bool param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<bool,int> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void,int> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,int *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,KeyCode *param_1,Event **param_2);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,bool *param_1,vector<> *param_2);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,basic_string<> *param_1,vector<> *param_2);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
void __thiscall std::_Func_impl_no_alloc<>::_Do_call(_Func_impl_no_alloc<> *this,basic_string<> *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Copy(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<void> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
type_info * __thiscall std::_Func_impl_no_alloc<>::_Target_type(_Func_impl_no_alloc<> *this);
_Func_base<> * __thiscall std::_Func_impl_no_alloc<>::_Move(_Func_impl_no_alloc<> *this,void *param_1);
