void __cdecl std::_Adjust_manually_vector_aligned(void **param_1,uint *param_2);
void __cdecl std::_Deallocate<8,0>(void *param_1,uint param_2);
void __cdecl std::_Destroy_range<>(basic_string<> *param_1,basic_string<> *param_2,allocator<> *param_3);
bool __cdecl std::operator!=<>(basic_string<> *param_1,char *param_2);
bool __cdecl std::operator==<>(basic_string<> *param_1,char *param_2);
bool __cdecl std::_Traits_equal<>(char *param_1,uint param_2,char *param_3,uint param_4);
basic_string<> * __cdecl std::_Uninitialized_move<>(basic_string<> *param_1,basic_string<> *param_2,basic_string<> *param_3,allocator<> *param_4);
bool __cdecl std::operator!=<>(basic_string<> *param_1,basic_string<> *param_2);
void __cdecl std::transform<>(char *param_1,char *param_2,undefined1 *param_3);
void __cdecl std::remove<>(undefined4 param_1,word *param_2);
bool __cdecl std::operator==<>(char *param_1,basic_string<> *param_2);
undefined4 * __cdecl std::remove<>(int *param_1,int *param_2);
basic_string<> * __cdecl std::_Move_unchecked<>(basic_string<> *param_1,basic_string<> *param_2,basic_string<> *param_3);
basic_string<> * __cdecl std::_Find_unchecked<>(basic_string<> *param_1,basic_string<> *param_2,basic_string<> *param_3);
void __cdecl std::_Destroy_range<>(InputCommand *param_1,InputCommand *param_2,allocator<> *param_3);
_Func_impl_no_alloc<> * __cdecl std::_Global_new<>(function<> *param_1);
_Func_impl_no_alloc<> * __cdecl std::_Global_new<>(function<> *param_1);
basic_string<> * __cdecl std::_Copy_unchecked<>(basic_string<> *param_1,basic_string<> *param_2,basic_string<> *param_3);
uint __cdecl std::_Traits_find<>(char *param_1,uint param_2,uint param_3,char *param_4,uint param_5);
PrivateCommElement * __cdecl std::_Uninitialized_move<>(PrivateCommElement *param_1,PrivateCommElement *param_2,PrivateCommElement *param_3,allocator<> *param_4);
void __cdecl std::_Destroy_range<>(NavMarker *param_1,NavMarker *param_2,allocator<NavMarker> *param_3);
void __cdecl std::_Destroy_range<>(Destination *param_1,Destination *param_2,allocator<> *param_3);
void __cdecl std::_Destroy_range<>(DockProcessElement *param_1,DockProcessElement *param_2,allocator<> *param_3);
DockProcessElement * __cdecl std::_Uninitialized_move<>(DockProcessElement *param_1,DockProcessElement *param_2,DockProcessElement *param_3,allocator<> *param_4);
void __cdecl std::_Destroy_range<>(BootElement *param_1,BootElement *param_2,allocator<> *param_3);
BootElement * __cdecl std::_Uninitialized_move<>(BootElement *param_1,BootElement *param_2,BootElement *param_3,allocator<> *param_4);
MouseCursor * __cdecl std::_Uninitialized_copy<>(MouseCursor *param_1,MouseCursor *param_2,MouseCursor *param_3,allocator<> *param_4);
void __cdecl std::_Destroy_range<>(BankTransaction *param_1,BankTransaction *param_2,allocator<> *param_3);
BankTransaction * __cdecl std::_Uninitialized_move<>(BankTransaction *param_1,BankTransaction *param_2,BankTransaction *param_3,allocator<> *param_4);
void __cdecl std::_Destroy_range<>(Shop *param_1,Shop *param_2,allocator<Shop> *param_3);
bool_(__cdecl*&&)(Ship*,int,std::basic_string<>) * __cdecl std::move<>(_func_bool_Ship_ptr_int_basic_string<> **param_1);
_Func_impl_no_alloc<> * __cdecl std::_Global_new<>(function<> *param_1);
_Func_impl_no_alloc<> * __cdecl std::_Global_new<>(function<> *param_1);
void __cdecl std::_Destroy_range<>(ExtraSpawned *param_1,ExtraSpawned *param_2,allocator<> *param_3);
ExtraSpawned * __cdecl std::_Uninitialized_move<>(ExtraSpawned *param_1,ExtraSpawned *param_2,ExtraSpawned *param_3,allocator<> *param_4);
MouseCursor * __cdecl std::_Copy_unchecked<>(MouseCursor *param_1,MouseCursor *param_2,MouseCursor *param_3);
void __cdecl std::_Destroy_range<>(word *param_1,word *param_2,allocator<word> *param_3);
vector<> * __cdecl std::_Uninitialized_move<>(vector<> *param_1,vector<> *param_2,vector<> *param_3,allocator<> *param_4);
word * __cdecl std::_Uninitialized_move<>(word *param_1,word *param_2,word *param_3,allocator<word> *param_4);
void __cdecl std::_Destroy_range<>(ScreenTab *param_1,ScreenTab *param_2,allocator<ScreenTab> *param_3);
ScreenTab * __cdecl std::_Uninitialized_move<>(ScreenTab *param_1,ScreenTab *param_2,ScreenTab *param_3,allocator<ScreenTab> *param_4);
void __cdecl std::_Destroy_range<>(JumpGateRoute *param_1,JumpGateRoute *param_2,allocator<> *param_3);
void __cdecl std::_Destroy_range<>(ModuleRenderData *param_1,ModuleRenderData *param_2,allocator<> *param_3);
ModuleRenderData * __cdecl std::_Uninitialized_move<>(ModuleRenderData *param_1,ModuleRenderData *param_2,ModuleRenderData *param_3,allocator<> *param_4);
SensorSelectionElement * __cdecl std::_Uninitialized_move<>(SensorSelectionElement *param_1,SensorSelectionElement *param_2,SensorSelectionElement *param_3,allocator<> *param_4);
SensorSelectionElement * __cdecl std::_Copy_unchecked<>(SensorSelectionElement *param_1,SensorSelectionElement *param_2,SensorSelectionElement *param_3);
