void __thiscall std::_Tree<>::_Erase(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Erase(_Tree<> *this,_Tree_node<> *param_1);
int * __thiscall std::_Tree<>::erase(undefined4 param_1,int *param_2,_Tree<> *param_3,_Tree<> *param_4);
void __thiscall std::_Tree<>::erase(_Tree<> *this,int *param_2,int *param_3);
void __thiscall std::_Tree<>::_Eqrange<>(_Tree<> *this,basic_string<> *param_1);
void __thiscall std::_Tree<>::lower_bound(_Tree<> *this,basic_string<> *param_1);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,pair<> *param_3,_Tree_node<> *param_4);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,_Tree<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Destroy_if_node(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Destroy_if_node(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,bool param_1,_Tree_node<> *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,bool param_1,pair<> *param_2,_Tree_node<> *param_3);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,bool param_1,_Tree_node<> *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,bool param_1,pair<> *param_2,_Tree_node<> *param_3);
uint __thiscall std::_Tree<>::count(_Tree<> *this,basic_string<> *param_1);
void __thiscall std::_Tree<>::_Tidy(_Tree<> *this);
void __thiscall std::_Tree<>::erase(_Tree<> *this,undefined4 *param_2,_Tree<> *param_3,_Tree<> *param_4);
void __thiscall std::_Tree<>::_Erase(_Tree<> *this,_Tree_node<> *param_1);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Destroy_if_node(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,bool param_1,_Tree_node<> *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,bool param_1,pair<> *param_2,_Tree_node<> *param_3);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Destroy_if_node(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,bool param_1,_Tree_node<> *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,bool param_1,pair<> *param_2,_Tree_node<> *param_3);
uint __thiscall std::_Tree<>::count(_Tree<> *this,basic_string<> *param_1);
void __thiscall std::_Tree<>::_Erase(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Eqrange<>(_Tree<> *this,basic_string<> *param_1);
_Tree<> * __thiscall std::_Tree<>::_Tree<><>(_Tree<> *this,_Tree<> *param_1,allocator<> *param_2);
void __thiscall std::_Tree<>::lower_bound(_Tree<> *this,basic_string<> *param_1);
_Tree_node<> * __thiscall std::_Tree<>::_Copy_nodes<>(_Tree<> *this,undefined4 *param_1,undefined4 param_2,undefined4 param_4);
void __thiscall std::_Tree<>::_Destroy_if_node(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,bool param_1,_Tree_node<> *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,bool param_1,pair<> *param_2,_Tree_node<> *param_3);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,bool param_1,_Tree_node<> *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,bool param_1,pair<> *param_2,_Tree_node<> *param_3);
uint __thiscall std::_Tree<>::count(_Tree<> *this,basic_string<> *param_1);
void __thiscall std::_Tree<>::_Erase(_Tree<> *this,_Tree_node<> *param_1);
void __thiscall std::_Tree<>::erase(_Tree<> *this,undefined4 *param_2,int *param_3,int *param_4);
void __thiscall std::_Tree<>::_Eqrange<int>(_Tree<> *this,int *param_1);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,pair<> *param_3,_Tree_node<> *param_4);
void __thiscall std::_Tree<>::clear(_Tree<> *this);
void __thiscall std::_Tree<>::_Erase(_Tree<> *this,_Tree_node<> *param_1);
undefined4 * __thiscall std::_Tree<>::erase(_Tree<> *this,undefined4 *param_2,int *param_3,int *param_4);
undefined4 * __thiscall std::_Tree<>::_Insert_hint<>(_Tree<> *this,undefined4 *param_2,int *param_3,int *param_4,undefined4 param_5);
void __thiscall std::_Tree<>::_Insert_nohint<>(_Tree<> *this,undefined4 *param_1,char param_2,int *param_4,undefined4 param_5);
void __thiscall std::_Tree<>::_Insert_at<>(_Tree<> *this,undefined4 *param_1,char param_2,undefined4 *param_3,PathNode **param_5);
