basic_string<> * __thiscall std::vector<>::operator[](vector<> *this,uint param_1);
uint __thiscall std::vector<>::size(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Tidy(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,basic_string<> *param_1,basic_string<> *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::push_back(vector<> *this,basic_string<> *param_1);
void __thiscall std::vector<>::push_back(vector<> *this,basic_string<> *param_1);
void __thiscall std::vector<>::_Emplace_back_with_unused_capacity<>(vector<> *this,basic_string<> *param_1);
basic_string<> * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,basic_string<> *param_1,basic_string<> *param_2);
basic_string<> * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,basic_string<> *param_1,basic_string<> *param_2);
void __cdecl std::vector<>::_Xlength(void);
void __thiscall std::vector<>::_Change_array(vector<> *this,basic_string<> *param_1,uint param_2,uint param_3);
void __thiscall std::vector<>::push_back(vector<> *this,UIText **param_1);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::erase(vector<> *this,undefined4 *param_2,void *param_3,void *param_4);
JumpPoint ** __thiscall std::vector<>::operator[](vector<> *this,uint param_1);
uint __thiscall std::vector<>::size(vector<> *this);
void __thiscall std::vector<>::push_back(vector<> *this,InputOption **param_1);
Vec2 * __thiscall std::vector<>::operator[](vector<> *this,uint param_1);
uint __thiscall std::vector<>::size(vector<> *this);
basic_string<> * __thiscall std::vector<>::_Unchecked_end(vector<> *this);
basic_string<> * __thiscall std::vector<>::_Unchecked_begin(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
AnimationFrames ** __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,AnimationFrames **param_1,AnimationFrames **param_2);
MetaGameAction ** __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,MetaGameAction **param_1,MetaGameAction **param_2);
void __thiscall std::vector<>::_Change_array(vector<> *this,PathNode **param_1,uint param_2,uint param_3);
void __thiscall std::vector<>::erase(vector<> *this,undefined4 *param_2,basic_string<> *param_3);
void __thiscall std::vector<>::_Destroy(vector<> *this,InputCommand *param_1,InputCommand *param_2);
InputCommand * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,InputCommand *param_1,InputCommand *param_2);
InputCommand * __thiscall std::vector<>::_Umove(vector<> *this,InputCommand *param_1,InputCommand *param_2,InputCommand *param_3);
Waypoint * __thiscall std::vector<>::operator[](vector<> *this,uint param_1);
uint __thiscall std::vector<>::size(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::clear(vector<> *this);
Waypoint * __thiscall std::vector<>::_Emplace_reallocate<Waypoint>(vector<> *this,Waypoint *param_1,Waypoint *param_2);
HullDamageChance * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,HullDamageChance *param_1,HullDamageChance *param_2);
Waypoint * __thiscall std::vector<>::_Umove(vector<> *this,Waypoint *param_1,Waypoint *param_2,Waypoint *param_3);
vector<> * __thiscall std::vector<>::vector<>(vector<> *this,vector<> *param_1);
HullStrength * __thiscall std::vector<>::operator[](vector<> *this,uint param_1);
uint __thiscall std::vector<>::size(vector<> *this);
void __thiscall std::vector<>::push_back(vector<> *this,Vec2 *param_1);
vector<> * __thiscall std::vector<>::vector<>(vector<> *this);
Vec2 * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,Vec2 *param_1,Vec2 *param_2);
void __thiscall std::vector<>::_Change_array(vector<> *this,Vec2 *param_1,uint param_2,uint param_3);
vector<> * __thiscall std::vector<>::operator=(vector<> *this,vector<> *param_1);
vector<> * __thiscall std::vector<>::vector<>(vector<> *this,vector<> *param_1);
bool __thiscall std::vector<>::_Buy(vector<> *this,uint param_1);
basic_string<> * __thiscall std::vector<>::_Ucopy<>(vector<> *this,basic_string<> *param_1,basic_string<> *param_2,basic_string<> *param_3);
void __thiscall std::vector<>::_Assign_range<>(vector<> *this,basic_string<> *param_1,basic_string<> *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,PrivateCommElement *param_1,PrivateCommElement *param_2);
void __thiscall std::vector<>::_Tidy(vector<> *this);
void __thiscall std::vector<>::_Tidy(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,PrivateCommOption *param_1,PrivateCommOption *param_2);
void __thiscall std::vector<>::emplace_back<>(vector<> *this,PrivateCommElement *param_1);
void __thiscall std::vector<>::clear(vector<> *this);
void __thiscall std::vector<>::push_back(vector<> *this,PrivateCommOption *param_1);
PrivateCommElement * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,PrivateCommElement *param_1,PrivateCommElement *param_2);
PrivateCommOption * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,PrivateCommOption *param_1,PrivateCommOption *param_2);
PrivateCommOption * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,PrivateCommOption *param_1,PrivateCommOption *param_2);
void __thiscall std::vector<>::_Change_array(vector<> *this,PrivateCommOption *param_1,uint param_2,uint param_3);
void __thiscall std::vector<>::_Umove_if_noexcept(vector<> *this,PrivateCommOption *param_1,PrivateCommOption *param_2,PrivateCommOption *param_3);
PrivateCommOption * __thiscall std::vector<>::_Umove(vector<> *this,PrivateCommOption *param_1,PrivateCommOption *param_2,PrivateCommOption *param_3);
vector<> * __thiscall std::vector<>::vector<>(vector<> *this,vector<> *param_1);
vector<> * __thiscall std::vector<>::vector<>(vector<> *this,vector<> *param_1);
ListData * __thiscall std::vector<>::_Emplace_reallocate<ListData>(vector<> *this,ListData *param_1,ListData *param_2);
void __thiscall std::vector<>::_Change_array(vector<> *this,ListData *param_1,uint param_2,uint param_3);
void __thiscall std::vector<>::_Destroy(vector<> *this,ListData *param_1,ListData *param_2);
void __thiscall std::vector<>::push_back(vector<> *this,PlayerGuidedToPort *param_1);
void __thiscall std::vector<>::push_back(vector<> *this,ScreenData *param_1);
void __thiscall std::vector<>::push_back(vector<> *this,Destination *param_1);
void __thiscall std::vector<>::push_back(vector<> *this,EngineeringSlotLocation *param_1);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Tidy(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,MouseCursor *param_1,MouseCursor *param_2);
void __thiscall std::vector<>::_Destroy(vector<> *this,Widget *param_1,Widget *param_2);
NavMarker * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,NavMarker *param_1,NavMarker *param_2);
PlayerGuidedToPort * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,PlayerGuidedToPort *param_1,PlayerGuidedToPort *param_2);
NSMSectorInfo * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,NSMSectorInfo *param_1,NSMSectorInfo *param_2);
ScreenData * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,ScreenData *param_1,ScreenData *param_2);
ComponentInterface ** __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,ComponentInterface **param_1,ComponentInterface **param_2);
Destination * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,Destination *param_1,Destination *param_2);
DockProcessElement * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,DockProcessElement *param_1,DockProcessElement *param_2);
EngineeringSlotLocation * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,EngineeringSlotLocation *param_1,EngineeringSlotLocation *param_2);
MouseCursor * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,MouseCursor *param_1,MouseCursor *param_2);
Widget * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,Widget *param_1,Widget *param_2);
BootElement * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,BootElement *param_1,BootElement *param_2);
void __thiscall std::vector<>::_Destroy(vector<> *this,NavMarker *param_1,NavMarker *param_2);
NavMarker * __thiscall std::vector<>::_Umove(vector<> *this,NavMarker *param_1,NavMarker *param_2,NavMarker *param_3);
uint __thiscall std::vector<>::size(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,ScreenData *param_1,ScreenData *param_2);
ScreenData * __thiscall std::vector<>::_Umove(vector<> *this,ScreenData *param_1,ScreenData *param_2,ScreenData *param_3);
void __thiscall std::vector<>::_Change_array(vector<> *this,Destination *param_1,uint param_2,uint param_3);
void __thiscall std::vector<>::_Destroy(vector<> *this,Destination *param_1,Destination *param_2);
void __thiscall std::vector<>::_Umove_if_noexcept(vector<> *this,Destination *param_1,Destination *param_2,Destination *param_3);
Destination * __thiscall std::vector<>::_Umove(vector<> *this,Destination *param_1,Destination *param_2,Destination *param_3);
void __thiscall std::vector<>::_Destroy(vector<> *this,DockProcessElement *param_1,DockProcessElement *param_2);
EngineeringSlotLocation * __thiscall std::vector<>::_Umove(vector<> *this,EngineeringSlotLocation *param_1,EngineeringSlotLocation *param_2,EngineeringSlotLocation *param_3);
MouseCursor * __thiscall std::vector<>::_Umove(vector<> *this,MouseCursor *param_1,MouseCursor *param_2,MouseCursor *param_3);
Widget * __thiscall std::vector<>::_Umove(vector<> *this,Widget *param_1,Widget *param_2,Widget *param_3);
void __thiscall std::vector<>::_Destroy(vector<> *this,BootElement *param_1,BootElement *param_2);
BankTransaction * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,BankTransaction *param_1,BankTransaction *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
Shop * __thiscall std::vector<>::_Emplace_reallocate<Shop>(vector<> *this,Shop *param_1,Shop *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
ListData * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,ListData *param_1,ListData *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
Resolution * __thiscall std::vector<>::_Emplace_reallocate<Resolution>(vector<> *this,Resolution *param_1,Resolution *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::erase(vector<> *this,undefined4 *param_2,undefined4 *param_3);
Destination * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,Destination *param_1,Destination *param_2);
undefined4 * __thiscall std::vector<>::insert(vector<> *this,undefined4 *param_2,Waypoint *param_3,Waypoint *param_4);
void __thiscall std::vector<>::~vector<>(vector<> *this);
vector<> * __thiscall std::vector<>::operator=(vector<> *this,vector<> *param_1);
vector<> * __thiscall std::vector<>::operator=(vector<> *this,vector<> *param_1);
void __thiscall std::vector<>::_Assign_range<>(vector<> *this,undefined4 *param_1,undefined4 *param_2);
ExtraSpawned * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,ExtraSpawned *param_1,ExtraSpawned *param_2);
void __thiscall std::vector<>::_Destroy(vector<> *this,CameraPos *param_1,CameraPos *param_2);
CameraPos * __thiscall std::vector<>::_Emplace_reallocate<CameraPos>(vector<> *this,CameraPos *param_1,CameraPos *param_2);
CameraPos * __thiscall std::vector<>::_Umove(vector<> *this,CameraPos *param_1,CameraPos *param_2,CameraPos *param_3);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,ContractCommand *param_1,ContractCommand *param_2);
WeaponCommand * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,WeaponCommand *param_1,WeaponCommand *param_2);
ContractCommand * __thiscall std::vector<>::_Umove(vector<> *this,ContractCommand *param_1,ContractCommand *param_2,ContractCommand *param_3);
double * __thiscall std::vector<>::_Emplace_reallocate<double>(vector<> *this,double *param_1,double *param_2);
void __thiscall std::vector<>::_Assign_range<>(vector<> *this,int param_1,int param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,CommsCommand *param_1,CommsCommand *param_2);
CommsCommand * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,CommsCommand *param_1,CommsCommand *param_2);
CommsCommand * __thiscall std::vector<>::_Umove(vector<> *this,CommsCommand *param_1,CommsCommand *param_2,CommsCommand *param_3);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Tidy(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,word *param_1,word *param_2);
void __thiscall std::vector<>::_Destroy(vector<> *this,vector<> *param_1,vector<> *param_2);
vector<> * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,vector<> *param_1,vector<> *param_2);
word * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,word *param_1,word *param_2);
vector<> * __thiscall std::vector<>::vector<>(vector<> *this,vector<> *param_1);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,ScreenTab *param_1,ScreenTab *param_2);
ScreenTab * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,ScreenTab *param_1,ScreenTab *param_2);
void __thiscall std::vector<>::_Range_construct_or_tidy<>(vector<> *this,basic_string<> *param_1,basic_string<> *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,Rect *param_1,Rect *param_2);
Rect * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,Rect *param_1,Rect *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,Selectable *param_1,Selectable *param_2);
Selectable * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,Selectable *param_1,Selectable *param_2);
NavMarker * __thiscall std::vector<>::operator[](vector<> *this,uint param_1);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Destroy(vector<> *this,JumpGateRoute *param_1,JumpGateRoute *param_2);
UI_NavMap ** __thiscall std::vector<>::_Emplace_reallocate<UI_NavMap*>(vector<> *this,UI_NavMap **param_1,UI_NavMap **param_2);
JumpGateRoute * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,JumpGateRoute *param_1,JumpGateRoute *param_2);
JumpGateRoute * __thiscall std::vector<>::_Umove(vector<> *this,JumpGateRoute *param_1,JumpGateRoute *param_2,JumpGateRoute *param_3);
void __thiscall std::vector<>::_Destroy(vector<> *this,ModuleRenderData *param_1,ModuleRenderData *param_2);
ModuleRenderData * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,ModuleRenderData *param_1,ModuleRenderData *param_2);
void __thiscall std::vector<>::~vector<>(vector<> *this);
void __thiscall std::vector<>::_Tidy(vector<> *this);
SensorSelectionElement * __thiscall std::vector<>::_Emplace_reallocate<>(vector<> *this,SensorSelectionElement *param_1,SensorSelectionElement *param_2);
void __thiscall std::vector<>::_Assign_range<>(vector<> *this,SensorSelectionElement *param_1,SensorSelectionElement *param_2);
SensorSelectionElement * __thiscall std::vector<>::_Ucopy<>(vector<> *this,SensorSelectionElement *param_1,SensorSelectionElement *param_2,SensorSelectionElement *param_3);
void __thiscall std::vector<>::_Reallocate_exactly(vector<> *this,uint param_1);
